+incdir+${PROJ_HOME}/wujian100_open_for_debug/soc/params
${PROJ_HOME}/wujian100_open_for_debug/soc/ahb_matrix_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/wujian100_open_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/smu_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sms.v
${PROJ_HOME}/wujian100_open_for_debug/soc/ls_sub_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/retu_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim5.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim.v
${PROJ_HOME}/wujian100_open_for_debug/soc/dmac.v
${PROJ_HOME}/wujian100_open_for_debug/soc/pdu_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim2.v
${PROJ_HOME}/wujian100_open_for_debug/soc/usi1.v
${PROJ_HOME}/wujian100_open_for_debug/soc/aou_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/matrix.v
${PROJ_HOME}/wujian100_open_for_debug/soc/dummy.v
${PROJ_HOME}/wujian100_open_for_debug/soc/pwm.v
${PROJ_HOME}/wujian100_open_for_debug/soc/usi0.v
${PROJ_HOME}/wujian100_open_for_debug/soc/apb0_sub_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/common.v
${PROJ_HOME}/wujian100_open_for_debug/soc/wdt.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim1.v
${PROJ_HOME}/wujian100_open_for_debug/soc/rtc.v
${PROJ_HOME}/wujian100_open_for_debug/soc/E902_20191018.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim7.v
${PROJ_HOME}/wujian100_open_for_debug/soc/apb0.v
${PROJ_HOME}/wujian100_open_for_debug/soc/apb1_sub_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/gpio0.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim4.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim3.v
${PROJ_HOME}/wujian100_open_for_debug/soc/clkgen.v
${PROJ_HOME}/wujian100_open_for_debug/soc/core_top.v
${PROJ_HOME}/wujian100_open_for_debug/soc/tim6.v
${PROJ_HOME}/wujian100_open_for_debug/soc/apb1.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sim_lib/PAD_DIG_IO.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sim_lib/PAD_OSC_IO.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sim_lib/STD_CELL.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sim_lib/fpga_byte_spram.v
${PROJ_HOME}/wujian100_open_for_debug/soc/sim_lib/fpga_spram.v
