+incdir+${PROJ_HOME}/wujian100_open/soc/params
${PROJ_HOME}/wujian100_open/soc/ahb_matrix_top.v
${PROJ_HOME}/wujian100_open/soc/wujian100_open_top.v
${PROJ_HOME}/wujian100_open/soc/smu_top.v
${PROJ_HOME}/wujian100_open/soc/sms.v
${PROJ_HOME}/wujian100_open/soc/ls_sub_top.v
${PROJ_HOME}/wujian100_open/soc/retu_top.v
${PROJ_HOME}/wujian100_open/soc/tim5.v
${PROJ_HOME}/wujian100_open/soc/tim.v
${PROJ_HOME}/wujian100_open/soc/dmac.v
${PROJ_HOME}/wujian100_open/soc/pdu_top.v
${PROJ_HOME}/wujian100_open/soc/tim2.v
${PROJ_HOME}/wujian100_open/soc/usi1.v
${PROJ_HOME}/wujian100_open/soc/aou_top.v
${PROJ_HOME}/wujian100_open/soc/matrix.v
${PROJ_HOME}/wujian100_open/soc/dummy.v
${PROJ_HOME}/wujian100_open/soc/pwm.v
${PROJ_HOME}/wujian100_open/soc/usi0.v
${PROJ_HOME}/wujian100_open/soc/apb0_sub_top.v
${PROJ_HOME}/wujian100_open/soc/common.v
${PROJ_HOME}/wujian100_open/soc/wdt.v
${PROJ_HOME}/wujian100_open/soc/tim1.v
${PROJ_HOME}/wujian100_open/soc/rtc.v
${PROJ_HOME}/wujian100_open/soc/E902_20191018.v
${PROJ_HOME}/wujian100_open/soc/tim7.v
${PROJ_HOME}/wujian100_open/soc/apb0.v
${PROJ_HOME}/wujian100_open/soc/apb1_sub_top.v
${PROJ_HOME}/wujian100_open/soc/gpio0.v
${PROJ_HOME}/wujian100_open/soc/tim4.v
${PROJ_HOME}/wujian100_open/soc/tim3.v
${PROJ_HOME}/wujian100_open/soc/clkgen.v
${PROJ_HOME}/wujian100_open/soc/core_top.v
${PROJ_HOME}/wujian100_open/soc/tim6.v
${PROJ_HOME}/wujian100_open/soc/apb1.v
${PROJ_HOME}/wujian100_open/soc/sim_lib/PAD_DIG_IO.v
${PROJ_HOME}/wujian100_open/soc/sim_lib/PAD_OSC_IO.v
${PROJ_HOME}/wujian100_open/soc/sim_lib/STD_CELL.v
${PROJ_HOME}/wujian100_open/soc/sim_lib/fpga_byte_spram.v
${PROJ_HOME}/wujian100_open/soc/sim_lib/fpga_spram.v
