#!/usr/bin/env python3
"""Emit a SystemVerilog register-definition header from a parsed JSON.

The header is organised as follows:

  typedef union {
      struct packed {
          bit[W-1:0]      name /* name, access, comment */;
          ...
      }bits;
      int unsigned u32 = {W'h0, ..., W'h0};
  } U_<IP>_<REG>;

Bit positions are emitted MSB-first (SystemVerilog convention).  Reserved
fields are emitted as ``const bit[N:0] /* rsvd_HI_LO */;`` so the ``u32``
member can be reassigned without violating the constness.

For every register a matching pair of macros is emitted::

  `define <IP>_<REG>_REG_OFFSET  0x<OFFSET>
  `define <IP>_<REG>_REG_ADDR    (`<IP>_REG_BASE_ADDR + `<IP>_<REG>_REG_OFFSET)

Variable-width fields (``x:N``) have their width resolved by
``resolve_field_width.resolve_field_width`` so the SV ``bit[]`` widths and
the ``u32`` initialiser both reflect the maximum legal width.

Gap-fill: bit positions that no documented field covers are emitted as
reserved fields; both the struct and the initialiser will sum to 32 bits.

Usage::

    python3 gen_sv_header.py --input regs.json --output RegDef.svh --base-addr 0xC0001000
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from resolve_field_width import resolve_field_width  # noqa: E402


# ---------------------------------------------------------------------------
# Bit-range parser (mirror of gen_c_header)
# ---------------------------------------------------------------------------
def parse_bits(bits: str):
    if ":" in bits:
        hi_s, lo_s = bits.split(":")
        is_var = hi_s == "x"
        try:
            hi = int(hi_s) if hi_s != "x" else 0
            lo = int(lo_s) if lo_s != "x" else 0
        except ValueError:
            return None
        return (hi, lo, is_var)
    try:
        bit = int(bits)
    except ValueError:
        return None
    return (bit, bit, False)


def fill_field_gaps(fields: list[dict[str, Any]]):
    annotated = []
    for f in fields:
        bp = parse_bits(f["bits"])
        if bp is None:
            continue
        hi, lo, is_var = bp
        w = (resolve_field_width(f["bits"], f.get("desc", "")) or 4) if is_var else (hi - lo + 1)
        eff_hi = (lo + w - 1) if is_var else hi
        annotated.append((eff_hi, lo, w, f, is_var))

    covered = {b for hi, lo, _w, _f, _v in annotated for b in range(lo, hi + 1)}
    gaps = []
    b = 31
    while b >= 0:
        if b not in covered:
            ghi = b
            while b >= 0 and b not in covered:
                b -= 1
            glo = b + 1
            gaps.append((ghi, glo))
        else:
            b -= 1

    merged = list(annotated)
    for ghi, glo in gaps:
        w = ghi - glo + 1
        merged.append(
            (ghi, glo, w, {
                "bits": f"{ghi}:{glo}" if w > 1 else str(ghi),
                "name": "",
                "access": "",
                "desc": "Reserved Field: Yes (gap-fill)",
                "reserved": True,
            }, False)
        )
    merged.sort(key=lambda x: x[0], reverse=True)
    return merged


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------
def render_sv_header(registers: list[dict[str, Any]], base_addr: int,
                     ip_prefix: str, source_label: str) -> str:
    seen = {}
    unique = []
    for r in registers:
        k = (r.get("section", 0), r.get("name", ""), r.get("meta", {}).get("offset", ""))
        if k in seen:
            continue
        seen[k] = True
        unique.append(r)

    def sort_key(r):
        try:
            off = int(r["meta"]["offset"], 16)
        except (ValueError, KeyError):
            off = 0
        return (r.get("section", 0), off, r.get("name", ""))

    unique.sort(key=sort_key)
    sections = sorted({r.get("section", 0) for r in unique if r.get("section")})

    guard = f"__{ip_prefix.upper().replace('-', '_')}_REG_DEF_SVH__"
    lines: list[str] = []
    lines.append(f"/* {ip_prefix} Register Definition (SystemVerilog Header) */")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("/*")
    lines.append(" * ============================================================================")
    lines.append(f" * {ip_prefix} Register Definition (SystemVerilog)")
    lines.append(" * ---------------------------------------------------------------------------")
    lines.append(f" * Auto-generated by reg-def-gen skill from {source_label}")
    lines.append(" * Layout: byte-addressable, 32-bit data width.")
    lines.append(" *")
    lines.append(f" * Base address: 0x{base_addr:08X}.")
    lines.append(" * ============================================================================")
    lines.append(" */")
    lines.append("")

    current_section = None
    typedef_lines: list[str] = []
    offset_defs: list[str] = []
    addr_defs: list[str] = []
    seen_names: set[str] = set()

    for r in unique:
        sec = r.get("section", 0)
        if sec != current_section:
            current_section = sec
            section_label = f"Section {sec}" if sec else "Common"
            typedef_lines.append("")
            typedef_lines.append(f"/* ===== {section_label} ===== */")
            typedef_lines.append("")

        name = r["name"]
        if name in seen_names:
            continue
        seen_names.add(name)

        offset = r["meta"].get("offset", "0x0")
        typedef_name = f"U_{ip_prefix.upper()}_{name}"

        typedef_lines.append(f"/* {name} ({offset}) - {r['meta'].get('description', '')} */")
        typedef_lines.append("typedef union {")
        typedef_lines.append("    struct packed {")

        concat_parts: list[str] = []
        for hi, lo, w, f, is_var in fill_field_gaps(r["fields"]):
            cparts: list[str] = []
            if f.get("name"):
                cparts.append(f["name"])
            if f.get("access"):
                cparts.append(f["access"])
            if is_var:
                cparts.append(f"variable width (x:N), default={w} bits")
            comment = " /* " + ", ".join(cparts) + " */" if cparts else ""

            if f.get("reserved"):
                if w == 1:
                    typedef_lines.append(f"        const bit            /* rsvd_{hi}_{lo} */{comment};")
                else:
                    typedef_lines.append(f"        const bit[{w-1}:0]   /* rsvd_{hi}_{lo} */{comment};")
            else:
                if w == 1:
                    typedef_lines.append(f"        bit                 {f['name']}{comment};")
                else:
                    typedef_lines.append(f"        bit[{w-1}:0]        {f['name']}{comment};")
            concat_parts.append(f"{w}'h0")

        concat_str = "{" + ", ".join(concat_parts) + "}" if concat_parts else "32'h0"
        typedef_lines.append("    }bits;")
        typedef_lines.append(f"    int unsigned u32 = {concat_str};")
        typedef_lines.append(f"}} {typedef_name};")
        typedef_lines.append("")

        offset_defs.append(f"`define {ip_prefix.upper()}_{name}_REG_OFFSET\t\t\t\t\t{offset}")
        addr_defs.append(
            f"`define {ip_prefix.upper()}_{name}_REG_ADDR\t\t\t\t\t"
            f"(`{ip_prefix.upper()}_REG_BASE_ADDR + `{ip_prefix.upper()}_{name}_REG_OFFSET)"
        )

    out: list[str] = []
    out.append("\n".join(lines))
    out.append("\n")
    out.append("\n".join(typedef_lines))
    out.append("\n")
    out.append("/* Address Base & Per-Register OFFSET / ADDR Macros */")
    out.append("")
    out.append(f"`define {ip_prefix.upper()}_REG_BASE_ADDR\t\t\t\t\t\t'h{base_addr:08X}")
    out.append("")
    out.append("\n".join(offset_defs))
    out.append("")
    out.append("\n".join(addr_defs))
    out.append("")
    out.append("")
    out.append(f"#endif //{guard}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--base-addr", required=True, type=lambda s: int(s, 16))
    p.add_argument("--ip-prefix", default=None)
    p.add_argument("--source-label", default="<unknown>")
    args = p.parse_args()

    data = json.loads(args.input.read_text())
    registers = data.get("registers", [])
    if not registers:
        print("ERROR: input JSON contains no registers", file=sys.stderr)
        return 2

    ip_prefix = args.ip_prefix
    if not ip_prefix:
        names = [r["name"] for r in registers]
        parts = names[0].split("_") if names else ["DW", "IP"]
        common = []
        for idx, part in enumerate(parts):
            if all(n.split("_")[idx] == part for n in names if len(n.split("_")) > idx):
                common.append(part)
            else:
                break
        ip_prefix = "_".join(common).rstrip("_") if common else "DW_IP"

    body = render_sv_header(registers, args.base_addr, ip_prefix, args.source_label)
    args.output.write_text(body)
    print(f"Wrote {args.output} ({len(body)} chars, "
          f"{body.count(chr(10))} lines, {body.count('typedef union')} typedefs)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
