#ifndef __DMA_REG_DEF_H__
#define __DMA_REG_DEF_H__

/*
 * ============================================================================
 * DMA Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x40000000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* SARn (0x00000000) - SARn */
typedef union
{
	struct
	{
		unsigned int sarn /* sarn, R/W, `SARn[31:0]` — Channel n Source read Address. Reset Value: ` */ : 32;
	}bits;
	unsigned int u32;
} U_DMA_SARn;

/* DARn (0x00000004) - DARn */
typedef union
{
	struct
	{
		unsigned int darn /* darn, R/W, `DARn[31:0]` — Channel n Destination write Address. Reset Va */ : 32;
	}bits;
	unsigned int u32;
} U_DMA_DARn;

/* CHn_CTRL_A (0x00000008) - CHn_CTRL_A */
typedef union
{
	struct
	{
		unsigned int dst_tr_width /* dst_tr_width, R/W, `DST_TR_WIDTH[1:0]` — Destination Transfer Width (mapped to  */ : 2;
		unsigned int src_tr_width /* src_tr_width, R/W, `SRC_TR_WIDTH[1:0]` — Source Transfer Width (mapped to AHB ` */ : 2;
		unsigned int dinc /* dinc, R/W, `DINC[1:0]` — Destination Address Increment. `00` = incremen */ : 2;
		unsigned int sinc /* sinc, R/W, `SINC[1:0]` — Source Address Increment. `00` = increment; `0 */ : 2;
		unsigned int /* rsvd_11_8 */ /* R/W, Reserved */ : 4;
		unsigned int block_tl /* block_tl, R/W, `BLOCK_TL[11:0]` — Block Transfer Length. Must be written be */ : 12;
		unsigned int /* rsvd_31_24 */ /* R/W, Reserved */ : 8;
	}bits;
	unsigned int u32;
} U_DMA_CHn_CTRL_A;

/* CHn_CTRL_B (0x0000000c) - CHn_CTRL_B */
typedef union
{
	struct
	{
		unsigned int int_en /* int_en, R/W, `INT_EN` — Interrupt Enable. `0` = all interrupt sources dis */ : 1;
		unsigned int trgtmdc /* trgtmdc, R/W, `TRGTMDC[1:0]` — Trigger transfer mode. `2'b00` = reserved;  */ : 2;
		unsigned int /* rsvd_12_3 */ /* —, Reserved */ : 10;
		unsigned int srcdtlgc /* srcdtlgc, R/W, `SRCDTLGC` — Source read data endian change. `0` = little-en */ : 1;
		unsigned int dstdtlgc /* dstdtlgc, R/W, `DSTDTLGC` — Destination Write data endian change. `0` = lit */ : 1;
		unsigned int protctl /* protctl, R/W, `PROTCTL[3:0]` — Channel n Protection Control; drives AHB `H */ : 4;
		unsigned int /* rsvd_31_19 */ /* —, Reserved */ : 13;
	}bits;
	unsigned int u32;
} U_DMA_CHn_CTRL_B;

/* CHn_INT_MASK (0x00000010) - CHn_INT_MASK */
typedef union
{
	struct
	{
		unsigned int maskerr /* maskerr, R/W, `maskErr` — Mask for transfer error interrupt. `0` = mask; ` */ : 1;
		unsigned int masktfr /* masktfr, R/W, `masktfr` — Mask for transfer complete interrupt. `0` = mask */ : 1;
		unsigned int maskhtfr /* maskhtfr, R/W, `maskhtfr` — Mask for transfer half complete interrupt. `0`  */ : 1;
		unsigned int masktrgetcmpfr /* masktrgetcmpfr, R/W, `masktrgetcmpfr` — Mask for trigger event complete interrupt */ : 1;
		unsigned int /* rsvd_31_4 */ : 28;
	}bits;
	unsigned int u32;
} U_DMA_CHn_INT_MASK;

/* CHn_INT_STATUS (0x00000014) - CHn_INT_STATUS */
typedef union
{
	struct
	{
		unsigned int statuserr /* statuserr, R, `statusErr` — Status for transfer error (only detects AHB `H */ : 1;
		unsigned int statustfr /* statustfr, R, `statustfr` — Status for block-length transfer complete. Res */ : 1;
		unsigned int statushtfr /* statushtfr, R, `statushtfr` — Status for half-of-block-length transfer comp */ : 1;
		unsigned int statustrgetcmpfr /* statustrgetcmpfr, R, `statustrgetcmpfr` — Status for trigger event complete. Rese */ : 1;
		unsigned int /* rsvd_31_4 */ : 28;
	}bits;
	unsigned int u32;
} U_DMA_CHn_INT_STATUS;

/* CHn_INT_CLEAR (0x00000018) - CHn_INT_CLEAR */
typedef union
{
	struct
	{
		unsigned int clearerr /* clearerr, W, `clearErr` — Clear `statusErr`. `0` = no clear; `1` = clear. */ : 1;
		unsigned int cleartfr /* cleartfr, W, `cleartfr` — Clear `statustfr`. `0` = no clear; `1` = clear. */ : 1;
		unsigned int clearhtfr /* clearhtfr, W, `clearhtfr` — Clear `statushtfr`. `0` = no clear; `1` = clea */ : 1;
		unsigned int cleartrgetcmpfr /* cleartrgetcmpfr, W, `cleartrgetcmpfr` — Clear `statustrgetcmpif`. `0` = no clear */ : 1;
		unsigned int /* rsvd_31_4 */ : 28;
	}bits;
	unsigned int u32;
} U_DMA_CHn_INT_CLEAR;

/* CHn_SOFT_REQ (0x0000001c) - CHn_SOFT_REQ */
typedef union
{
	struct
	{
		unsigned int soft_req /* soft_req, W, `soft_req` — Software Request. Reset: `0x0` */ : 1;
		unsigned int /* rsvd_31_1 */ : 31;
	}bits;
	unsigned int u32;
} U_DMA_CHn_SOFT_REQ;

/* CHn_EN (0x00000020) - CHn_EN */
typedef union
{
	struct
	{
		unsigned int chn_en /* chn_en, R/W, `chn_en` — Channel n Enable. When set to `1`, `DARn`/`SARn`/ */ : 1;
		unsigned int /* rsvd_31_1 */ : 31;
	}bits;
	unsigned int u32;
} U_DMA_CHn_EN;

/* CHSR (0x00000338) - CHSR */
typedef union
{
	struct
	{
		unsigned int ch0bsy /* ch0bsy, R, `ch0bsy` */ : 1;
		unsigned int ch1bsy /* ch1bsy, R, `ch1bsy` */ : 1;
		unsigned int ch2bsy /* ch2bsy, R, `ch2bsy` */ : 1;
		unsigned int ch3bsy /* ch3bsy, R, `Ch3bsy` */ : 1;
		unsigned int ch4bsy /* ch4bsy, R, `Ch4bsy` */ : 1;
		unsigned int ch5bsy /* ch5bsy, R, `Ch5bsy` */ : 1;
		unsigned int ch6bsy /* ch6bsy, R, `Ch6bsy` */ : 1;
		unsigned int ch7bsy /* ch7bsy, R, `Ch7bsy` */ : 1;
		unsigned int ch8bsy /* ch8bsy, R, `Ch8bsy` */ : 1;
		unsigned int ch9bsy /* ch9bsy, R, `Ch9bsy` */ : 1;
		unsigned int ch10bsy /* ch10bsy, R, `ch10bsy` */ : 1;
		unsigned int ch11bsy /* ch11bsy, R, `Ch11bsy` */ : 1;
		unsigned int ch12bsy /* ch12bsy, R, `Ch12bsy` */ : 1;
		unsigned int ch13bsy /* ch13bsy, R, `ch12bsy`（User Guide 拼写为 ch12bsy 但对应 bit13 = Channel 13）；注：U */ : 1;
		unsigned int ch14bsy /* ch14bsy, R, `Ch14bsy` */ : 1;
		unsigned int ch15bsy /* ch15bsy, R, `Ch15bsy` — Channel 15 busy (owns data bus) */ : 1;
		unsigned int /* rsvd_23_16 */ /* —, Reserved */ : 8;
		unsigned int /* rsvd_31_24 */ : 8;
	}bits;
	unsigned int u32;
} U_DMA_CHSR;

/* DMACCFG (0x0000033c) - DMACCFG */
typedef union
{
	struct
	{
		unsigned int dmacen /* dmacen, R/W, `DMACEN` — Global DMAC enable. After this bit is set, all ch */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved */ : 31;
	}bits;
	unsigned int u32;
} U_DMA_DMACCFG;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define DMA_REG_BASE_ADDR						0x40000000

#define DMA_SARn_REG_OFFSET					0x00000000
#define DMA_DARn_REG_OFFSET					0x00000004
#define DMA_CHn_CTRL_A_REG_OFFSET					0x00000008
#define DMA_CHn_CTRL_B_REG_OFFSET					0x0000000c
#define DMA_CHn_INT_MASK_REG_OFFSET					0x00000010
#define DMA_CHn_INT_STATUS_REG_OFFSET					0x00000014
#define DMA_CHn_INT_CLEAR_REG_OFFSET					0x00000018
#define DMA_CHn_SOFT_REQ_REG_OFFSET					0x0000001c
#define DMA_CHn_EN_REG_OFFSET					0x00000020
#define DMA_CHSR_REG_OFFSET					0x00000338
#define DMA_DMACCFG_REG_OFFSET					0x0000033c

#define DMA_SARn_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_SARn_REG_OFFSET)
#define DMA_DARn_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_DARn_REG_OFFSET)
#define DMA_CHn_CTRL_A_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_CTRL_A_REG_OFFSET)
#define DMA_CHn_CTRL_B_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_CTRL_B_REG_OFFSET)
#define DMA_CHn_INT_MASK_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_INT_MASK_REG_OFFSET)
#define DMA_CHn_INT_STATUS_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_INT_STATUS_REG_OFFSET)
#define DMA_CHn_INT_CLEAR_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_INT_CLEAR_REG_OFFSET)
#define DMA_CHn_SOFT_REQ_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_SOFT_REQ_REG_OFFSET)
#define DMA_CHn_EN_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHn_EN_REG_OFFSET)
#define DMA_CHSR_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_CHSR_REG_OFFSET)
#define DMA_DMACCFG_REG_ADDR						(DMA_REG_BASE_ADDR + DMA_DMACCFG_REG_OFFSET)

#endif //__DMA_REG_DEF_H__
