/* DMA Register Definition (SystemVerilog Header) */
#ifndef __DMA_REG_DEF_SVH__
#define __DMA_REG_DEF_SVH__

/*
 * ============================================================================
 * DMA Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x40000000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* SARn (0x00000000) - SARn */
typedef union {
    struct packed {
        bit[31:0]        sarn /* sarn, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_DMA_SARn;

/* DARn (0x00000004) - DARn */
typedef union {
    struct packed {
        bit[31:0]        darn /* darn, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_DMA_DARn;

/* CHn_CTRL_A (0x00000008) - CHn_CTRL_A */
typedef union {
    struct packed {
        const bit[7:0]   /* rsvd_31_24 */ /* R/W */;
        bit[11:0]        block_tl /* block_tl, R/W */;
        const bit[3:0]   /* rsvd_11_8 */ /* R/W */;
        bit[1:0]        sinc /* sinc, R/W */;
        bit[1:0]        dinc /* dinc, R/W */;
        bit[1:0]        src_tr_width /* src_tr_width, R/W */;
        bit[1:0]        dst_tr_width /* dst_tr_width, R/W */;
    }bits;
    int unsigned u32 = {8'h0, 12'h0, 4'h0, 2'h0, 2'h0, 2'h0, 2'h0};
} U_DMA_CHn_CTRL_A;

/* CHn_CTRL_B (0x0000000c) - CHn_CTRL_B */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* — */;
        bit[3:0]        protctl /* protctl, R/W */;
        bit                 dstdtlgc /* dstdtlgc, R/W */;
        bit                 srcdtlgc /* srcdtlgc, R/W */;
        const bit[9:0]   /* rsvd_12_3 */ /* — */;
        bit[1:0]        trgtmdc /* trgtmdc, R/W */;
        bit                 int_en /* int_en, R/W */;
    }bits;
    int unsigned u32 = {13'h0, 4'h0, 1'h0, 1'h0, 10'h0, 2'h0, 1'h0};
} U_DMA_CHn_CTRL_B;

/* CHn_INT_MASK (0x00000010) - CHn_INT_MASK */
typedef union {
    struct packed {
        const bit[27:0]   /* rsvd_31_4 */;
        bit                 masktrgetcmpfr /* masktrgetcmpfr, R/W */;
        bit                 maskhtfr /* maskhtfr, R/W */;
        bit                 masktfr /* masktfr, R/W */;
        bit                 maskerr /* maskerr, R/W */;
    }bits;
    int unsigned u32 = {28'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_DMA_CHn_INT_MASK;

/* CHn_INT_STATUS (0x00000014) - CHn_INT_STATUS */
typedef union {
    struct packed {
        const bit[27:0]   /* rsvd_31_4 */;
        bit                 statustrgetcmpfr /* statustrgetcmpfr, R */;
        bit                 statushtfr /* statushtfr, R */;
        bit                 statustfr /* statustfr, R */;
        bit                 statuserr /* statuserr, R */;
    }bits;
    int unsigned u32 = {28'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_DMA_CHn_INT_STATUS;

/* CHn_INT_CLEAR (0x00000018) - CHn_INT_CLEAR */
typedef union {
    struct packed {
        const bit[27:0]   /* rsvd_31_4 */;
        bit                 cleartrgetcmpfr /* cleartrgetcmpfr, W */;
        bit                 clearhtfr /* clearhtfr, W */;
        bit                 cleartfr /* cleartfr, W */;
        bit                 clearerr /* clearerr, W */;
    }bits;
    int unsigned u32 = {28'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_DMA_CHn_INT_CLEAR;

/* CHn_SOFT_REQ (0x0000001c) - CHn_SOFT_REQ */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */;
        bit                 soft_req /* soft_req, W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_DMA_CHn_SOFT_REQ;

/* CHn_EN (0x00000020) - CHn_EN */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */;
        bit                 chn_en /* chn_en, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_DMA_CHn_EN;

/* CHSR (0x00000338) - CHSR */
typedef union {
    struct packed {
        const bit[7:0]   /* rsvd_31_24 */;
        const bit[7:0]   /* rsvd_23_16 */ /* — */;
        bit                 ch15bsy /* ch15bsy, R */;
        bit                 ch14bsy /* ch14bsy, R */;
        bit                 ch13bsy /* ch13bsy, R */;
        bit                 ch12bsy /* ch12bsy, R */;
        bit                 ch11bsy /* ch11bsy, R */;
        bit                 ch10bsy /* ch10bsy, R */;
        bit                 ch9bsy /* ch9bsy, R */;
        bit                 ch8bsy /* ch8bsy, R */;
        bit                 ch7bsy /* ch7bsy, R */;
        bit                 ch6bsy /* ch6bsy, R */;
        bit                 ch5bsy /* ch5bsy, R */;
        bit                 ch4bsy /* ch4bsy, R */;
        bit                 ch3bsy /* ch3bsy, R */;
        bit                 ch2bsy /* ch2bsy, R */;
        bit                 ch1bsy /* ch1bsy, R */;
        bit                 ch0bsy /* ch0bsy, R */;
    }bits;
    int unsigned u32 = {8'h0, 8'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_DMA_CHSR;

/* DMACCFG (0x0000033c) - DMACCFG */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 dmacen /* dmacen, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_DMA_DMACCFG;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define DMA_REG_BASE_ADDR						'h40000000

`define DMA_SARn_REG_OFFSET					0x00000000
`define DMA_DARn_REG_OFFSET					0x00000004
`define DMA_CHn_CTRL_A_REG_OFFSET					0x00000008
`define DMA_CHn_CTRL_B_REG_OFFSET					0x0000000c
`define DMA_CHn_INT_MASK_REG_OFFSET					0x00000010
`define DMA_CHn_INT_STATUS_REG_OFFSET					0x00000014
`define DMA_CHn_INT_CLEAR_REG_OFFSET					0x00000018
`define DMA_CHn_SOFT_REQ_REG_OFFSET					0x0000001c
`define DMA_CHn_EN_REG_OFFSET					0x00000020
`define DMA_CHSR_REG_OFFSET					0x00000338
`define DMA_DMACCFG_REG_OFFSET					0x0000033c

`define DMA_SARn_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_SARn_REG_OFFSET)
`define DMA_DARn_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_DARn_REG_OFFSET)
`define DMA_CHn_CTRL_A_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_CTRL_A_REG_OFFSET)
`define DMA_CHn_CTRL_B_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_CTRL_B_REG_OFFSET)
`define DMA_CHn_INT_MASK_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_INT_MASK_REG_OFFSET)
`define DMA_CHn_INT_STATUS_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_INT_STATUS_REG_OFFSET)
`define DMA_CHn_INT_CLEAR_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_INT_CLEAR_REG_OFFSET)
`define DMA_CHn_SOFT_REQ_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_SOFT_REQ_REG_OFFSET)
`define DMA_CHn_EN_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHn_EN_REG_OFFSET)
`define DMA_CHSR_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_CHSR_REG_OFFSET)
`define DMA_DMACCFG_REG_ADDR					(`DMA_REG_BASE_ADDR + `DMA_DMACCFG_REG_OFFSET)


#endif //__DMA_REG_DEF_SVH__
