#ifndef __GPIO_REG_DEF_H__
#define __GPIO_REG_DEF_H__

/*
 * ============================================================================
 * GPIO Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x60018000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* GPIOOUTPUTDATA (0x00000000) - gpio_output_data */
typedef union
{
	struct
	{
		unsigned int gpio_data_register /* gpio_data_register, R/W, 写入此寄存器的值将在 I/O 信号上输出（仅在对应 GPIO 方向设为 Output 且控制位设为 Software 模 */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOOUTPUTDATA;

/* GPIODIRECTION (0x00000004) - gpio_direction */
typedef union
{
	struct
	{
		unsigned int gpio_data_direction_register /* gpio_data_direction_register, R/W, 每 bit 独立控制对应 GPIO 方向：`0` = Input；`1` = Output。Reset: `32'b0` */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIODIRECTION;

/* GPIOCTL (0x00000008) - gpio_ctl */
typedef union
{
	struct
	{
		unsigned int gpio_data_source_register /* gpio_data_source_register, R/W, 每 bit 选择数据源：`0` = Software mode（由 `gpio_output_data` 驱动）；`1` */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOCTL;

/* GPIOINTEN (0x00000030) - gpio_inten */
typedef union
{
	struct
	{
		unsigned int interrupt_enable /* interrupt_enable, R/W, 每 bit 独立配置 GPIO 中断：`0` = 普通信号；`1` = 中断源。**约束**：仅当 (Data dire */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINTEN;

/* GPIOINTMASK (0x00000034) - gpio_intmask */
typedef union
{
	struct
	{
		unsigned int interrupt_mask /* interrupt_mask, R/W, 每 bit 独立控制是否 mask 对应 GPIO 中断：`0` = unmasked（default）；`1` = m */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINTMASK;

/* GPIOINTTYPELEVEL (0x00000038) - gpio_inttype_level */
typedef union
{
	struct
	{
		unsigned int interrupt_level /* interrupt_level, R/W, 每 bit 选择中断触发类型：`0` = level-sensitive（default）；`1` = edge-sen */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINTTYPELEVEL;

/* GPIOINTPOLARITY (0x0000003c) - gpio_int_polarity */
typedef union
{
	struct
	{
		unsigned int interrupt_polarity /* interrupt_polarity, R/W, 每 bit 选择中断极性：`0` = active-low / falling-edge（default）；`1` =  */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINTPOLARITY;

/* GPIOINTSTATUS (0x00000040) - gpio_intstatus */
typedef union
{
	struct
	{
		unsigned int interrupt_status /* interrupt_status, R, 屏蔽后的中断状态。Reset: `32'b0` */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINTSTATUS;

/* GPIORAWINTSTATUS (0x00000044) - gpio_rawintstatus */
typedef union
{
	struct
	{
		unsigned int raw_interrupt_status /* raw_interrupt_status, R, 屏蔽前的原始中断状态。Reset: `32'b0` */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIORAWINTSTATUS;

/* GPIOPORTAINTCLR (0x0000004c) - gpio_porta_int_clr */
typedef union
{
	struct
	{
		unsigned int clear_interrupt /* clear_interrupt, W, 写 1 到对应 bit 清除 edge 类型中断。GPIO 未配置为中断时所有中断自动清除：`0` = 不清（defau */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOPORTAINTCLR;

/* GPIOINPUTDATA (0x00000050) - gpio_input_data */
typedef union
{
	struct
	{
		unsigned int external_gpio /* external_gpio, R, 当 GPIO 配为 Input：读此位置返回 PAD 输入值。当 GPIO 配为 Output：读此位置返回 `gpio */ : 32;
	}bits;
	unsigned int u32;
} U_GPIO_GPIOINPUTDATA;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define GPIO_REG_BASE_ADDR						0x60018000

#define GPIO_GPIOOUTPUTDATA_REG_OFFSET					0x00000000
#define GPIO_GPIODIRECTION_REG_OFFSET					0x00000004
#define GPIO_GPIOCTL_REG_OFFSET					0x00000008
#define GPIO_GPIOINTEN_REG_OFFSET					0x00000030
#define GPIO_GPIOINTMASK_REG_OFFSET					0x00000034
#define GPIO_GPIOINTTYPELEVEL_REG_OFFSET					0x00000038
#define GPIO_GPIOINTPOLARITY_REG_OFFSET					0x0000003c
#define GPIO_GPIOINTSTATUS_REG_OFFSET					0x00000040
#define GPIO_GPIORAWINTSTATUS_REG_OFFSET					0x00000044
#define GPIO_GPIOPORTAINTCLR_REG_OFFSET					0x0000004c
#define GPIO_GPIOINPUTDATA_REG_OFFSET					0x00000050

#define GPIO_GPIOOUTPUTDATA_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOOUTPUTDATA_REG_OFFSET)
#define GPIO_GPIODIRECTION_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIODIRECTION_REG_OFFSET)
#define GPIO_GPIOCTL_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOCTL_REG_OFFSET)
#define GPIO_GPIOINTEN_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINTEN_REG_OFFSET)
#define GPIO_GPIOINTMASK_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINTMASK_REG_OFFSET)
#define GPIO_GPIOINTTYPELEVEL_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINTTYPELEVEL_REG_OFFSET)
#define GPIO_GPIOINTPOLARITY_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINTPOLARITY_REG_OFFSET)
#define GPIO_GPIOINTSTATUS_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINTSTATUS_REG_OFFSET)
#define GPIO_GPIORAWINTSTATUS_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIORAWINTSTATUS_REG_OFFSET)
#define GPIO_GPIOPORTAINTCLR_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOPORTAINTCLR_REG_OFFSET)
#define GPIO_GPIOINPUTDATA_REG_ADDR						(GPIO_REG_BASE_ADDR + GPIO_GPIOINPUTDATA_REG_OFFSET)

#endif //__GPIO_REG_DEF_H__
