/* GPIO Register Definition (SystemVerilog Header) */
#ifndef __GPIO_REG_DEF_SVH__
#define __GPIO_REG_DEF_SVH__

/*
 * ============================================================================
 * GPIO Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x60018000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* GPIOOUTPUTDATA (0x00000000) - gpio_output_data */
typedef union {
    struct packed {
        bit[31:0]        gpio_data_register /* gpio_data_register, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOOUTPUTDATA;

/* GPIODIRECTION (0x00000004) - gpio_direction */
typedef union {
    struct packed {
        bit[31:0]        gpio_data_direction_register /* gpio_data_direction_register, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIODIRECTION;

/* GPIOCTL (0x00000008) - gpio_ctl */
typedef union {
    struct packed {
        bit[31:0]        gpio_data_source_register /* gpio_data_source_register, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOCTL;

/* GPIOINTEN (0x00000030) - gpio_inten */
typedef union {
    struct packed {
        bit[31:0]        interrupt_enable /* interrupt_enable, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINTEN;

/* GPIOINTMASK (0x00000034) - gpio_intmask */
typedef union {
    struct packed {
        bit[31:0]        interrupt_mask /* interrupt_mask, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINTMASK;

/* GPIOINTTYPELEVEL (0x00000038) - gpio_inttype_level */
typedef union {
    struct packed {
        bit[31:0]        interrupt_level /* interrupt_level, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINTTYPELEVEL;

/* GPIOINTPOLARITY (0x0000003c) - gpio_int_polarity */
typedef union {
    struct packed {
        bit[31:0]        interrupt_polarity /* interrupt_polarity, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINTPOLARITY;

/* GPIOINTSTATUS (0x00000040) - gpio_intstatus */
typedef union {
    struct packed {
        bit[31:0]        interrupt_status /* interrupt_status, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINTSTATUS;

/* GPIORAWINTSTATUS (0x00000044) - gpio_rawintstatus */
typedef union {
    struct packed {
        bit[31:0]        raw_interrupt_status /* raw_interrupt_status, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIORAWINTSTATUS;

/* GPIOPORTAINTCLR (0x0000004c) - gpio_porta_int_clr */
typedef union {
    struct packed {
        bit[31:0]        clear_interrupt /* clear_interrupt, W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOPORTAINTCLR;

/* GPIOINPUTDATA (0x00000050) - gpio_input_data */
typedef union {
    struct packed {
        bit[31:0]        external_gpio /* external_gpio, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_GPIO_GPIOINPUTDATA;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define GPIO_REG_BASE_ADDR						'h60018000

`define GPIO_GPIOOUTPUTDATA_REG_OFFSET					0x00000000
`define GPIO_GPIODIRECTION_REG_OFFSET					0x00000004
`define GPIO_GPIOCTL_REG_OFFSET					0x00000008
`define GPIO_GPIOINTEN_REG_OFFSET					0x00000030
`define GPIO_GPIOINTMASK_REG_OFFSET					0x00000034
`define GPIO_GPIOINTTYPELEVEL_REG_OFFSET					0x00000038
`define GPIO_GPIOINTPOLARITY_REG_OFFSET					0x0000003c
`define GPIO_GPIOINTSTATUS_REG_OFFSET					0x00000040
`define GPIO_GPIORAWINTSTATUS_REG_OFFSET					0x00000044
`define GPIO_GPIOPORTAINTCLR_REG_OFFSET					0x0000004c
`define GPIO_GPIOINPUTDATA_REG_OFFSET					0x00000050

`define GPIO_GPIOOUTPUTDATA_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOOUTPUTDATA_REG_OFFSET)
`define GPIO_GPIODIRECTION_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIODIRECTION_REG_OFFSET)
`define GPIO_GPIOCTL_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOCTL_REG_OFFSET)
`define GPIO_GPIOINTEN_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINTEN_REG_OFFSET)
`define GPIO_GPIOINTMASK_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINTMASK_REG_OFFSET)
`define GPIO_GPIOINTTYPELEVEL_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINTTYPELEVEL_REG_OFFSET)
`define GPIO_GPIOINTPOLARITY_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINTPOLARITY_REG_OFFSET)
`define GPIO_GPIOINTSTATUS_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINTSTATUS_REG_OFFSET)
`define GPIO_GPIORAWINTSTATUS_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIORAWINTSTATUS_REG_OFFSET)
`define GPIO_GPIOPORTAINTCLR_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOPORTAINTCLR_REG_OFFSET)
`define GPIO_GPIOINPUTDATA_REG_ADDR					(`GPIO_REG_BASE_ADDR + `GPIO_GPIOINPUTDATA_REG_OFFSET)


#endif //__GPIO_REG_DEF_SVH__
