#ifndef __PWM_REG_DEF_H__
#define __PWM_REG_DEF_H__

/*
 * ============================================================================
 * PWM Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x5001C000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* PWMCFG (0x00000000) - PWMCFG */
typedef union
{
	struct
	{
		unsigned int pwm0en /* pwm0en, R/W, Channel 0 PWM 输出使能 */ : 1;
		unsigned int pwm1en /* pwm1en, R/W, Channel 1 PWM 输出使能 */ : 1;
		unsigned int pwm2en /* pwm2en, R/W, Channel 2 PWM 输出使能 */ : 1;
		unsigned int pwm3en /* pwm3en, R/W, Channel 3 PWM 输出使能 */ : 1;
		unsigned int pwm4en /* pwm4en, R/W, Channel 4 PWM 输出使能 */ : 1;
		unsigned int pwm5en /* pwm5en, R/W, Channel 5 PWM 输出使能 */ : 1;
		unsigned int pwm6en /* pwm6en, R/W, Channel 6 PWM 输出使能 */ : 1;
		unsigned int pwm7en /* pwm7en, R/W, Channel 7 PWM 输出使能 */ : 1;
		unsigned int pwm8en /* pwm8en, R/W, Channel 8 PWM 输出使能 */ : 1;
		unsigned int pwm9en /* pwm9en, R/W, Channel 9 PWM 输出使能 */ : 1;
		unsigned int pwm10en /* pwm10en, R/W, Channel 10 PWM 输出使能 */ : 1;
		unsigned int pwm11en /* pwm11en, R/W, Channel 11 PWM 输出使能：`1` = PWM output enable; `0` = PWM outpu */ : 1;
		unsigned int cap0en /* cap0en, R/W, Group 0-channel 0 输入捕获使能 */ : 1;
		unsigned int cap1en /* cap1en, R/W, Group 1-channel 2 输入捕获使能 */ : 1;
		unsigned int cap2en /* cap2en, R/W, Group 2-channel 4 输入捕获使能 */ : 1;
		unsigned int cap3en /* cap3en, R/W, Group 3-channel 6 输入捕获使能 */ : 1;
		unsigned int cap4en /* cap4en, R/W, Group 4-channel 8 输入捕获使能 */ : 1;
		unsigned int cap5en /* cap5en, R/W, Group 5-channel 10 输入捕获使能：`1` = enable; `0` = disable */ : 1;
		unsigned int tim0en /* tim0en, R/W, Group 0 输出比较使能 */ : 1;
		unsigned int tim1en /* tim1en, R/W, Group 1 输出比较使能 */ : 1;
		unsigned int tim2en /* tim2en, R/W, Group 2 输出比较使能 */ : 1;
		unsigned int tim3en /* tim3en, R/W, Group 3 输出比较使能 */ : 1;
		unsigned int tim4en /* tim4en, R/W, Group 4 输出比较使能 */ : 1;
		unsigned int tim5en /* tim5en, R/W, Group 5 输出比较使能：`1` = enable; `0` = disable */ : 1;
		unsigned int cntdiv /* cntdiv, R/W, 计数器分频选择：`111`/`110` = /128; `101` = /64; `100` = /32; `011`  */ : 3;
		unsigned int cntdiven /* cntdiven, R/W, 计数器分频使能：`1` = frequency division enable；`0` = frequency divi */ : 1;
		unsigned int /* rsvd_31_28 */ /* —, Reserved, read as zero */ : 4;
	}bits;
	unsigned int u32;
} U_PWM_PWMCFG;

/* PWMINVERTTRIG (0x00000004) - PWMINVERTTRIG */
typedef union
{
	struct
	{
		unsigned int pwm0inv /* pwm0inv, R/W, Invert PWM0 */ : 1;
		unsigned int pwm1inv /* pwm1inv, R/W, Invert PWM1 */ : 1;
		unsigned int pwm2inv /* pwm2inv, R/W, Invert PWM2 */ : 1;
		unsigned int pwm3inv /* pwm3inv, R/W, Invert PWM3 */ : 1;
		unsigned int pwm4inv /* pwm4inv, R/W, Invert PWM4 */ : 1;
		unsigned int pwm5inv /* pwm5inv, R/W, Invert PWM5 */ : 1;
		unsigned int pwm6inv /* pwm6inv, R/W, Invert PWM6 */ : 1;
		unsigned int pwm7inv /* pwm7inv, R/W, Invert PWM7 */ : 1;
		unsigned int pwm8inv /* pwm8inv, R/W, Invert PWM8 */ : 1;
		unsigned int pwm9inv /* pwm9inv, R/W, Invert PWM9 */ : 1;
		unsigned int pwm10inv /* pwm10inv, R/W, Invert PWM10 */ : 1;
		unsigned int pwm11inv /* pwm11inv, R/W, Invert PWM11 信号：`1` = PWM11 signal is inverted; `0` = not in */ : 1;
		unsigned int /* rsvd_31_12 */ /* —, Reserved, read as zero */ : 20;
	}bits;
	unsigned int u32;
} U_PWM_PWMINVERTTRIG;

/* PWM01TRIG (0x00000008) - PWM01TRIG */
typedef union
{
	struct
	{
		unsigned int pwm0trig /* pwm0trig, R/W, The value generating group 0 trigger signal */ : 16;
		unsigned int pwm1trig /* pwm1trig, R/W, The value generating group 1 trigger signal */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM01TRIG;

/* PWM23TRIG (0x0000000c) - PWM23TRIG */
typedef union
{
	struct
	{
		unsigned int pwm2trig /* pwm2trig, R/W, The value generating group 2 trigger signal */ : 16;
		unsigned int pwm3trig /* pwm3trig, R/W, The value generating group 3 trigger signal */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM23TRIG;

/* PWM45TRIG (0x00000010) - PWM45TRIG */
typedef union
{
	struct
	{
		unsigned int pwm4trig /* pwm4trig, R/W, The value generating group 4 trigger signal */ : 16;
		unsigned int pwm5trig /* pwm5trig, R/W, The value generating group 5 trigger signal */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM45TRIG;

/* PWMINTEN1 (0x00000014) - PWMINTEN1 */
typedef union
{
	struct
	{
		unsigned int /* rsvd_7_0 */ /* —, Reserved, read as zero */ : 8;
		unsigned int int0encntzero /* int0encntzero, R/W, Interrupt for counter = 0 (channel1/0) */ : 1;
		unsigned int int0encntload /* int0encntload, R/W, Interrupt for counter = Load (channel1/0) */ : 1;
		unsigned int int0encmpau /* int0encmpau, R/W, Interrupt for counter = comparator A Up (channel0) */ : 1;
		unsigned int int0encmpbu /* int0encmpbu, R/W, Interrupt for counter = comparator B Up (channel1) */ : 1;
		unsigned int int0encmpad /* int0encmpad, R/W, Interrupt for counter = comparator A Down (channel0) */ : 1;
		unsigned int int0encmpbd /* int0encmpbd, R/W, Interrupt for counter = comparator B Down (channel1) */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int int1encntzero /* int1encntzero, R/W, Interrupt for counter = 0 (channel3/2) */ : 1;
		unsigned int int1encntload /* int1encntload, R/W, Interrupt for counter = Load (channel3/2) */ : 1;
		unsigned int int1encmpau /* int1encmpau, R/W, Interrupt for counter = comparator A Up (channel2) */ : 1;
		unsigned int int1encmpbu /* int1encmpbu, R/W, Interrupt for counter = comparator B Up (channel3) */ : 1;
		unsigned int int1encmpad /* int1encmpad, R/W, Interrupt for counter = comparator A Down (channel2) */ : 1;
		unsigned int int1encmpbd /* int1encmpbd, R/W, Interrupt for counter = comparator B Down (channel3) */ : 1;
		unsigned int /* rsvd_23_22 */ /* —, Reserved, read as zero */ : 2;
		unsigned int int2encntzero /* int2encntzero, R/W, Interrupt for counter = 0 (channel5/4) */ : 1;
		unsigned int int2encntload /* int2encntload, R/W, Interrupt for counter = Load (channel5/4) */ : 1;
		unsigned int int2encmpau /* int2encmpau, R/W, Interrupt for counter = comparator A Up (channel4) */ : 1;
		unsigned int int2encmpbu /* int2encmpbu, R/W, Interrupt for counter = comparator B Up (channel5) */ : 1;
		unsigned int int2encmpad /* int2encmpad, R/W, Interrupt for counter = comparator A Down (channel4) */ : 1;
		unsigned int int2encmpbd /* int2encmpbd, R/W, Interrupt for counter = comparator B Down (channel5). `1` =  */ : 1;
		unsigned int /* rsvd_31_30 */ /* —, Reserved, read as zero */ : 2;
	}bits;
	unsigned int u32;
} U_PWM_PWMINTEN1;

/* PWMINTEN2 (0x00000018) - PWMINTEN2 */
typedef union
{
	struct
	{
		unsigned int int3encntzero /* int3encntzero, R/W, Interrupt for counter = 0 (group3-channel7/6) */ : 1;
		unsigned int int3encntload /* int3encntload, R/W, Interrupt for counter = Load (group3-channel7/6) */ : 1;
		unsigned int int3encmpau /* int3encmpau, R/W, Interrupt for counter = comparator A Up (group3-channel6) */ : 1;
		unsigned int int3encmpbu /* int3encmpbu, R/W, Interrupt for counter = comparator B Up (group3-channel7) */ : 1;
		unsigned int int3encmpad /* int3encmpad, R/W, Interrupt for counter = comparator A Down (group3-channel6) */ : 1;
		unsigned int int3encmpbd /* int3encmpbd, R/W, Interrupt for counter = comparator B Down (group3-channel7) */ : 1;
		unsigned int /* rsvd_7_6 */ /* —, Reserved, read as zero */ : 2;
		unsigned int int4encntzero /* int4encntzero, R/W, Interrupt for counter = 0 (group4-channel9/8) */ : 1;
		unsigned int int4encntload /* int4encntload, R/W, Interrupt for counter = Load (group4-channel9/8) */ : 1;
		unsigned int int4encmpau /* int4encmpau, R/W, Interrupt for counter = comparator A Up (group4-channel8) */ : 1;
		unsigned int int4encmpbu /* int4encmpbu, R/W, Interrupt for counter = comparator B Up (group4-channel9) */ : 1;
		unsigned int int4encmpad /* int4encmpad, R/W, Interrupt for counter = comparator A Down (group4-channel8) */ : 1;
		unsigned int int4encmpbd /* int4encmpbd, R/W, Interrupt for counter = comparator B Down (group4-channel9) */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int int5encntzero /* int5encntzero, R/W, Interrupt for counter = 0 (group5-channel11/10) */ : 1;
		unsigned int int5encntload /* int5encntload, R/W, Interrupt for counter = Load (group5-channel11/10) */ : 1;
		unsigned int int5encmpau /* int5encmpau, R/W, Interrupt for counter = comparator A Up (group5-channel10) */ : 1;
		unsigned int int5encmpbu /* int5encmpbu, R/W, Interrupt for counter = comparator B Up (group5-channel11) */ : 1;
		unsigned int int5encmpad /* int5encmpad, R/W, Interrupt for counter = comparator A Down (group5-channel10) */ : 1;
		unsigned int int5encmpbd /* int5encmpbd, R/W, Interrupt for counter = comparator B Down (group5-channel11) */ : 1;
		unsigned int /* rsvd_31_22 */ /* —, Reserved, read as zero */ : 10;
	}bits;
	unsigned int u32;
} U_PWM_PWMINTEN2;

/* PWMRIS1 (0x0000001c) - PWMRIS1 */
typedef union
{
	struct
	{
		unsigned int /* rsvd_7_0 */ /* —, Reserved, read as zero */ : 8;
		unsigned int intris0cntzero /* intris0cntzero, R, Raw Interrupt for counter = 0 (group0-channel1/0) */ : 1;
		unsigned int intris0cntload /* intris0cntload, R, Raw Interrupt for counter = Load (group0-channel1/0) */ : 1;
		unsigned int intris0cmpau /* intris0cmpau, R, Raw Interrupt for counter = comparator A Up (group0-channel0 */ : 1;
		unsigned int intris0cmpbu /* intris0cmpbu, R, Raw Interrupt for counter = comparator B Up (group0-channel1 */ : 1;
		unsigned int intris0cmpad /* intris0cmpad, R, Raw Interrupt for counter = comparator A Down (group0-channe */ : 1;
		unsigned int intris0cmpbd /* intris0cmpbd, R, Raw Interrupt for counter = comparator B Down (group0-channe */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intris1cntzero /* intris1cntzero, R, Raw Interrupt for counter = 0 (group1-channel3/2) */ : 1;
		unsigned int intris1cntload /* intris1cntload, R, Raw Interrupt for counter = Load (group1-channel3/2) */ : 1;
		unsigned int intris1cmpau /* intris1cmpau, R, Raw Interrupt for counter = comparator A Up (group1-channel2 */ : 1;
		unsigned int intris1cmpbu /* intris1cmpbu, R, Raw Interrupt for counter = comparator B Up (group1-channel3 */ : 1;
		unsigned int intris1cmpad /* intris1cmpad, R, Raw Interrupt for counter = comparator A Down (group1-channe */ : 1;
		unsigned int intris1cmpbd /* intris1cmpbd, R, Raw Interrupt for counter = comparator B Down (group1-channe */ : 1;
		unsigned int /* rsvd_23_22 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intris2cntzero /* intris2cntzero, R, Raw Interrupt for counter = 0 (group2-channel5/4) */ : 1;
		unsigned int intris2cntload /* intris2cntload, R, Raw Interrupt for counter = Load (group2-channel5/4) */ : 1;
		unsigned int intris2cmpau /* intris2cmpau, R, Raw Interrupt for counter = comparator A Up (group2-channel4 */ : 1;
		unsigned int intris2cmpbu /* intris2cmpbu, R, Raw Interrupt for counter = comparator B Up (group2-channel5 */ : 1;
		unsigned int intris2cmpad /* intris2cmpad, R, Raw Interrupt for counter = comparator A Down (group2-channe */ : 1;
		unsigned int intris2cmpbd /* intris2cmpbd, R, Raw Interrupt for counter = comparator B Down (group2-channe */ : 1;
		unsigned int /* rsvd_31_30 */ /* —, Reserved, read as zero */ : 2;
	}bits;
	unsigned int u32;
} U_PWM_PWMRIS1;

/* PWMRIS2 (0x00000020) - PWMRIS2 */
typedef union
{
	struct
	{
		unsigned int intris3cntzero /* intris3cntzero, R, Raw Interrupt for counter = 0 (group3-channel7/6) */ : 1;
		unsigned int intris3cntload /* intris3cntload, R, Raw Interrupt for counter = Load (group3-channel7/6) */ : 1;
		unsigned int intris3cmpau /* intris3cmpau, R, Raw Interrupt for counter = comparator A Up (group3-channel6 */ : 1;
		unsigned int intris3cmpbu /* intris3cmpbu, R, Raw Interrupt for counter = comparator B Up (group3-channel7 */ : 1;
		unsigned int intris3cmpad /* intris3cmpad, R, Raw Interrupt for counter = comparator A Down (group3-channe */ : 1;
		unsigned int intris3cmpbd /* intris3cmpbd, R, Raw Interrupt for counter = comparator B Down (group3-channe */ : 1;
		unsigned int /* rsvd_7_6 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intris4cntzero /* intris4cntzero, R, Raw Interrupt for counter = 0 (group4-channel9/8) */ : 1;
		unsigned int intris4cntload /* intris4cntload, R, Raw Interrupt for counter = Load (group4-channel9/8) */ : 1;
		unsigned int intris4cmpau /* intris4cmpau, R, Raw Interrupt for counter = comparator A Up (group4-channel8 */ : 1;
		unsigned int intris4cmpbu /* intris4cmpbu, R, Raw Interrupt for counter = comparator B Up (group4-channel9 */ : 1;
		unsigned int intris4cmpad /* intris4cmpad, R, Raw Interrupt for counter = comparator A Down (group4-channe */ : 1;
		unsigned int intris4cmpbd /* intris4cmpbd, R, Raw Interrupt for counter = comparator B Down (group4-channe */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intris5cntzero /* intris5cntzero, R, Raw Interrupt for counter = 0 (group5-channel11/10) */ : 1;
		unsigned int intris5cntload /* intris5cntload, R, Raw Interrupt for counter = Load (group5-channel11/10) */ : 1;
		unsigned int intris5cmpau /* intris5cmpau, R, Raw Interrupt for counter = comparator A Up (group5-channel1 */ : 1;
		unsigned int intris5cmpbu /* intris5cmpbu, R, Raw Interrupt for counter = comparator B Up (group5-channel1 */ : 1;
		unsigned int intris5cmpad /* intris5cmpad, R, Raw Interrupt for counter = comparator A Down (group5-channe */ : 1;
		unsigned int intris5cmpbd /* intris5cmpbd, R, Raw Interrupt for counter = comparator B Down (group5-channe */ : 1;
		unsigned int /* rsvd_31_22 */ /* —, Reserved, read as zero */ : 10;
	}bits;
	unsigned int u32;
} U_PWM_PWMRIS2;

/* PWMIC1 (0x00000024) - PWMIC1 */
typedef union
{
	struct
	{
		unsigned int /* rsvd_7_0 */ /* —, Reserved, read as zero */ : 8;
		unsigned int intic0cntzero /* intic0cntzero, R/W, Clear Interrupt for counter = 0 (group0-channel1/0) */ : 1;
		unsigned int intic0cntload /* intic0cntload, R/W, Clear Interrupt for counter = Load (group0-channel1/0) */ : 1;
		unsigned int intic0cmpau /* intic0cmpau, R/W, Clear Interrupt for counter = comparator A Up (group0-channe */ : 1;
		unsigned int intic0cmpbu /* intic0cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group0-channe */ : 1;
		unsigned int intic0cmpad /* intic0cmpad, R/W, Clear Interrupt for counter = comparator A Down (group0-chan */ : 1;
		unsigned int intic0cmpbd /* intic0cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group0-chan */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intic1cntzero /* intic1cntzero, R/W, Clear Interrupt for counter = 0 (group1-channel3/2) */ : 1;
		unsigned int intic1cntload /* intic1cntload, R/W, Clear Interrupt for counter = Load (group1-channel3/2) */ : 1;
		unsigned int intic1cmpau /* intic1cmpau, R/W, Clear Interrupt for counter = comparator A Up (group1-channe */ : 1;
		unsigned int intic1cmpbu /* intic1cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group1-channe */ : 1;
		unsigned int intic1cmpad /* intic1cmpad, R/W, Clear Interrupt for counter = comparator A Down (group1-chan */ : 1;
		unsigned int intic1cmpbd /* intic1cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group1-chan */ : 1;
		unsigned int /* rsvd_23_22 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intic2cntzero /* intic2cntzero, R/W, Clear Interrupt for counter = 0 (group2-channel5/4) */ : 1;
		unsigned int intic2cntload /* intic2cntload, R/W, Clear Interrupt for counter = Load (group2-channel5/4) */ : 1;
		unsigned int intic2cmpau /* intic2cmpau, R/W, Clear Interrupt for counter = comparator A Up (group2-channe */ : 1;
		unsigned int intic2cmpbu /* intic2cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group2-channe */ : 1;
		unsigned int intic2cmpad /* intic2cmpad, R/W, Clear Interrupt for counter = comparator A Down (group2-chan */ : 1;
		unsigned int intic2cmpbd /* intic2cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group2-chan */ : 1;
		unsigned int /* rsvd_31_30 */ /* —, Reserved, read as zero */ : 2;
	}bits;
	unsigned int u32;
} U_PWM_PWMIC1;

/* PWMIC2 (0x00000028) - PWMIC2 */
typedef union
{
	struct
	{
		unsigned int intic3cntzero /* intic3cntzero, R/W, Clear Interrupt for counter = 0 (group3-channel7/6) */ : 1;
		unsigned int intic3cntload /* intic3cntload, R/W, Clear Interrupt for counter = Load (group3-channel7/6) */ : 1;
		unsigned int intic3cmpau /* intic3cmpau, R/W, Clear Interrupt for counter = comparator A Up (group3-channe */ : 1;
		unsigned int intic3cmpbu /* intic3cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group3-channe */ : 1;
		unsigned int intic3cmpad /* intic3cmpad, R/W, Clear Interrupt for counter = comparator A Down (group3-chan */ : 1;
		unsigned int intic3cmpbd /* intic3cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group3-chan */ : 1;
		unsigned int /* rsvd_7_6 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intic4cntzero /* intic4cntzero, R/W, Clear Interrupt for counter = 0 (group4-channel9/8) */ : 1;
		unsigned int intic4cntload /* intic4cntload, R/W, Clear Interrupt for counter = Load (group4-channel9/8) */ : 1;
		unsigned int intic4cmpau /* intic4cmpau, R/W, Clear Interrupt for counter = comparator A Up (group4-channe */ : 1;
		unsigned int intic4cmpbu /* intic4cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group4-channe */ : 1;
		unsigned int intic4cmpad /* intic4cmpad, R/W, Clear Interrupt for counter = comparator A Down (group4-chan */ : 1;
		unsigned int intic4cmpbd /* intic4cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group4-chan */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intic5cntzero /* intic5cntzero, R/W, Clear Interrupt for counter = 0 (group5-channel11/10) */ : 1;
		unsigned int intic5cntload /* intic5cntload, R/W, Clear Interrupt for counter = Load (group5-channel11/10) */ : 1;
		unsigned int intic5cmpau /* intic5cmpau, R/W, Clear Interrupt for counter = comparator A Up (group5-channe */ : 1;
		unsigned int intic5cmpbu /* intic5cmpbu, R/W, Clear Interrupt for counter = comparator B Up (group5-channe */ : 1;
		unsigned int intic5cmpad /* intic5cmpad, R/W, Clear Interrupt for counter = comparator A Down (group5-chan */ : 1;
		unsigned int intic5cmpbd /* intic5cmpbd, R/W, Clear Interrupt for counter = comparator B Down (group5-chan */ : 1;
		unsigned int /* rsvd_31_22 */ /* —, Reserved, read as zero */ : 10;
	}bits;
	unsigned int u32;
} U_PWM_PWMIC2;

/* PWMIS1 (0x0000002c) - PWMIS1 */
typedef union
{
	struct
	{
		unsigned int /* rsvd_7_0 */ /* —, Reserved, read as zero */ : 8;
		unsigned int intis0cntzero /* intis0cntzero, R, Interrupt for counter = 0 (group0-channel1/0) */ : 1;
		unsigned int intis0cntload /* intis0cntload, R, Interrupt for counter = Load (group0-channel1/0) */ : 1;
		unsigned int intis0cmpau /* intis0cmpau, R, Interrupt for counter = comparator A Up (group0-channel0) */ : 1;
		unsigned int intis0cmpbu /* intis0cmpbu, R, Interrupt for counter = comparator B Up (group0-channel1) */ : 1;
		unsigned int intis0cmpad /* intis0cmpad, R, Interrupt for counter = comparator A Down (group0-channel0) */ : 1;
		unsigned int intis0cmpbd /* intis0cmpbd, R, Interrupt for counter = comparator B Down (group0-channel1) */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intis1cntzero /* intis1cntzero, R, Interrupt for counter = 0 (group1-channel3/2) */ : 1;
		unsigned int intis1cntload /* intis1cntload, R, Interrupt for counter = Load (group1-channel3/2) */ : 1;
		unsigned int intis1cmpau /* intis1cmpau, R, Interrupt for counter = comparator A Up (group1-channel2) */ : 1;
		unsigned int intis1cmpbu /* intis1cmpbu, R, Interrupt for counter = comparator B Up (group1-channel3) */ : 1;
		unsigned int intis1cmpad /* intis1cmpad, R, Interrupt for counter = comparator A Down (group1-channel2) */ : 1;
		unsigned int intis1cmpbd /* intis1cmpbd, R, Interrupt for counter = comparator B Down (group1-channel3) */ : 1;
		unsigned int /* rsvd_23_22 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intis2cntzero /* intis2cntzero, R, Interrupt for counter = 0 (group2-channel5/4) */ : 1;
		unsigned int intis2cntload /* intis2cntload, R, Interrupt for counter = Load (group2-channel5/4) */ : 1;
		unsigned int intis2cmpau /* intis2cmpau, R, Interrupt for counter = comparator A Up (group2-channel4) */ : 1;
		unsigned int intis2cmpbu /* intis2cmpbu, R, Interrupt for counter = comparator B Up (group2-channel5) */ : 1;
		unsigned int intis2cmpad /* intis2cmpad, R, Interrupt for counter = comparator A Down (group2-channel4) */ : 1;
		unsigned int intis2cmpbd /* intis2cmpbd, R, Interrupt for counter = comparator B Down (group2-channel5) */ : 1;
		unsigned int /* rsvd_31_30 */ /* —, Reserved, read as zero */ : 2;
	}bits;
	unsigned int u32;
} U_PWM_PWMIS1;

/* PWMIS2 (0x00000030) - PWMIS2 */
typedef union
{
	struct
	{
		unsigned int intis3cntzero /* intis3cntzero, R, Interrupt for counter = 0 (group3-channel7/6) */ : 1;
		unsigned int intis3cntload /* intis3cntload, R, Interrupt for counter = Load (group3-channel7/6) */ : 1;
		unsigned int intis3cmpau /* intis3cmpau, R, Interrupt for counter = comparator A Up (group3-channel6) */ : 1;
		unsigned int intis3cmpbu /* intis3cmpbu, R, Interrupt for counter = comparator B Up (group3-channel7) */ : 1;
		unsigned int intis3cmpad /* intis3cmpad, R, Interrupt for counter = comparator A Down (group3-channel6) */ : 1;
		unsigned int intis3cmpbd /* intis3cmpbd, R, Interrupt for counter = comparator B Down (group3-channel7) */ : 1;
		unsigned int /* rsvd_7_6 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intis4cntzero /* intis4cntzero, R, Interrupt for counter = 0 (group4-channel9/8) */ : 1;
		unsigned int intis4cntload /* intis4cntload, R, Interrupt for counter = Load (group4-channel9/8) */ : 1;
		unsigned int intis4cmpau /* intis4cmpau, R, Interrupt for counter = comparator A Up (group4-channel8) */ : 1;
		unsigned int intis4cmpbu /* intis4cmpbu, R, Interrupt for counter = comparator B Up (group4-channel9) */ : 1;
		unsigned int intis4cmpad /* intis4cmpad, R, Interrupt for counter = comparator A Down (group4-channel8) */ : 1;
		unsigned int intis4cmpbd /* intis4cmpbd, R, Interrupt for counter = comparator B Down (group4-channel9) */ : 1;
		unsigned int /* rsvd_15_14 */ /* —, Reserved, read as zero */ : 2;
		unsigned int intis5cntzero /* intis5cntzero, R, Interrupt for counter = 0 (group5-channel11/10) */ : 1;
		unsigned int intis5cntload /* intis5cntload, R, Interrupt for counter = Load (group5-channel11/10) */ : 1;
		unsigned int intis5cmpau /* intis5cmpau, R, Interrupt for counter = comparator A Up (group5-channel10) */ : 1;
		unsigned int intis5cmpbu /* intis5cmpbu, R, Interrupt for counter = comparator B Up (group5-channel11) */ : 1;
		unsigned int intis5cmpad /* intis5cmpad, R, Interrupt for counter = comparator A Down (group5-channel10) */ : 1;
		unsigned int intis5cmpbd /* intis5cmpbd, R, Interrupt for counter = comparator B Down (group5-channel11) */ : 1;
		unsigned int /* rsvd_31_22 */ /* —, Reserved, read as zero */ : 10;
	}bits;
	unsigned int u32;
} U_PWM_PWMIS2;

/* PWMCTL (0x00000034) - PWMCTL */
typedef union
{
	struct
	{
		unsigned int pwm0mode /* pwm0mode, R/W, Counter mode (group0-channel1/0) — 编码同上 */ : 1;
		unsigned int pwm1mode /* pwm1mode, R/W, Counter mode (group1-channel3/2) — 编码同上 */ : 1;
		unsigned int pwm2mode /* pwm2mode, R/W, Counter mode (group2-channel5/4) — 编码同上 */ : 1;
		unsigned int pwm3mode /* pwm3mode, R/W, Counter mode (group3-channel7/6) — 编码同上 */ : 1;
		unsigned int pwm4mode /* pwm4mode, R/W, Counter mode (group4-channel9/8) — 编码同上 */ : 1;
		unsigned int pwm5mode /* pwm5mode, R/W, Counter mode (group5-channel11/10): `1` = count-up/down mode */ : 1;
		unsigned int sync0mode /* sync0mode, R/W, Synchronize mode (group0-channel1/0) — 编码同上 */ : 2;
		unsigned int sync1mode /* sync1mode, R/W, Synchronize mode (group1-channel3/2) — 编码同上 */ : 2;
		unsigned int sync2mode /* sync2mode, R/W, Synchronize mode (group2-channel5/4) — 编码同上 */ : 2;
		unsigned int sync3mode /* sync3mode, R/W, Synchronize mode (group3-channel7/6) — 编码同上 */ : 2;
		unsigned int sync4mode /* sync4mode, R/W, Synchronize mode (group4-channel9/8) — 编码同上 */ : 2;
		unsigned int sync5mode /* sync5mode, R/W, Synchronize mode (group5-channel11/10): `00` = update regist */ : 2;
		unsigned int /* rsvd_31_18 */ /* —, Reserved, read as zero */ : 14;
	}bits;
	unsigned int u32;
} U_PWM_PWMCTL;

/* PWM01LOAD (0x00000038) - 每 register 内含 2 个 16-bit load value（对应同一对 group 的两个计数器），字段名 `loadm` / `loadn`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM45LOAD` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int loadn /* loadn, R/W, Counter load n value（n=4：group4-channel9/8） */ : 16;
		unsigned int loadm /* loadm, R/W, Counter load m value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM01LOAD;

/* PWM23LOAD (0x0000003c) -  */
typedef union
{
	struct
	{
		unsigned int loadn /* loadn, R/W, Counter load n value（n=4：group4-channel9/8） */ : 16;
		unsigned int loadm /* loadm, R/W, Counter load m value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM23LOAD;

/* PWM45LOAD (0x00000040) - PWM45LOAD */
typedef union
{
	struct
	{
		unsigned int loadn /* loadn, R/W, Counter load n value（n=4：group4-channel9/8） */ : 16;
		unsigned int loadm /* loadm, R/W, Counter load m value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM45LOAD;

/* PWM01COUNT (0x00000044) - 只读当前计数器值，字段名 `countm` / `countn`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM45COUNT` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int countn /* countn, R, Counter n current value（n=4：group4-channel9/8） */ : 16;
		unsigned int countm /* countm, R, Counter m current value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM01COUNT;

/* PWM23COUNT (0x00000048) -  */
typedef union
{
	struct
	{
		unsigned int countn /* countn, R, Counter n current value（n=4：group4-channel9/8） */ : 16;
		unsigned int countm /* countm, R, Counter m current value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM23COUNT;

/* PWM45COUNT (0x0000004c) - PWM45COUNT */
typedef union
{
	struct
	{
		unsigned int countn /* countn, R, Counter n current value（n=4：group4-channel9/8） */ : 16;
		unsigned int countm /* countm, R, Counter m current value（m=5：group5-channel11/10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM45COUNT;

/* PWM0CMP (0x00000050) - 每寄存器 32-bit 内含 2 个 16-bit compare value（高 16-bit = 该 group 第 2 通道 CMP_B，低 16-bit = 第 1 通道 CMP_A），字段名 `compnb` / `compna`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM5CMP` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM0CMP;

/* PWM1CMP (0x00000054) -  */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM1CMP;

/* PWM2CMP (0x00000058) -  */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM2CMP;

/* PWM3CMP (0x0000005c) -  */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM3CMP;

/* PWM4CMP (0x00000060) -  */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM4CMP;

/* PWM5CMP (0x00000064) - PWM5CMP */
typedef union
{
	struct
	{
		unsigned int compna /* compna, R/W, Comparator A value（n=5：group5-channel10） */ : 16;
		unsigned int compnb /* compnb, R/W, Comparator B value（n=5：group5-channel11） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_PWM5CMP;

/* PWM01DB (0x00000068) - 死区（dead-band）延迟计数值，用于互补 PWM 输出延迟插入；位域结构见下方 `PWM45DB` 独立子节。整体 reset = `0x0000_0000`。 */
typedef union
{
	struct
	{
		unsigned int delayn /* delayn, R/W, Dead-band delay（n=4：group4-channel9/8）：clock tick 数 */ : 12;
		unsigned int delaym /* delaym, R/W, Dead-band delay（m=5：group5-channel11/10）：clock tick 数 */ : 12;
		unsigned int dbnen /* dbnen, R/W, Dead-band n generator enable（n=4：group4-channel9/8）：`1` = in */ : 1;
		unsigned int dbmen /* dbmen, R/W, Dead-band m generator enable（m=5：group5-channel11/10）：`1` =  */ : 1;
		unsigned int /* rsvd_31_26 */ /* —, Reserved, read as zero */ : 6;
	}bits;
	unsigned int u32;
} U_PWM_PWM01DB;

/* PWM23DB (0x0000006c) -  */
typedef union
{
	struct
	{
		unsigned int delayn /* delayn, R/W, Dead-band delay（n=4：group4-channel9/8）：clock tick 数 */ : 12;
		unsigned int delaym /* delaym, R/W, Dead-band delay（m=5：group5-channel11/10）：clock tick 数 */ : 12;
		unsigned int dbnen /* dbnen, R/W, Dead-band n generator enable（n=4：group4-channel9/8）：`1` = in */ : 1;
		unsigned int dbmen /* dbmen, R/W, Dead-band m generator enable（m=5：group5-channel11/10）：`1` =  */ : 1;
		unsigned int /* rsvd_31_26 */ /* —, Reserved, read as zero */ : 6;
	}bits;
	unsigned int u32;
} U_PWM_PWM23DB;

/* PWM45DB (0x00000070) - PWM45DB */
typedef union
{
	struct
	{
		unsigned int delayn /* delayn, R/W, Dead-band delay（n=4：group4-channel9/8）：clock tick 数 */ : 12;
		unsigned int delaym /* delaym, R/W, Dead-band delay（m=5：group5-channel11/10）：clock tick 数 */ : 12;
		unsigned int dbnen /* dbnen, R/W, Dead-band n generator enable（n=4：group4-channel9/8）：`1` = in */ : 1;
		unsigned int dbmen /* dbmen, R/W, Dead-band m generator enable（m=5：group5-channel11/10）：`1` =  */ : 1;
		unsigned int /* rsvd_31_26 */ /* —, Reserved, read as zero */ : 6;
	}bits;
	unsigned int u32;
} U_PWM_PWM45DB;

/* CAPCTL (0x00000074) - 字段命名与功能（user guide Table 6-19）： */
typedef union
{
	struct
	{
		unsigned int cap0mode /* cap0mode, R/W, Capture0 模式（group0-channel0）— 编码同上 */ : 1;
		unsigned int cap1mode /* cap1mode, R/W, Capture1 模式（group1-channel2）— 编码同上 */ : 1;
		unsigned int cap2mode /* cap2mode, R/W, Capture2 模式（group2-channel4）— 编码同上 */ : 1;
		unsigned int cap3mode /* cap3mode, R/W, Capture3 模式（group3-channel6）— 编码同上 */ : 1;
		unsigned int cap4mode /* cap4mode, R/W, Capture4 模式（group4-channel8）— 编码同上 */ : 1;
		unsigned int cap5mode /* cap5mode, R/W, Capture5 模式（group5-channel10）：`1` = edge count mode；`0` = ed */ : 1;
		unsigned int cap0event /* cap0event, R/W, Capture0 边沿事件模式（group0-channel0）— 编码同上 */ : 2;
		unsigned int cap1event /* cap1event, R/W, Capture1 边沿事件模式（group1-channel2）— 编码同上 */ : 2;
		unsigned int cap2event /* cap2event, R/W, Capture2 边沿事件模式（group2-channel4）— 编码同上 */ : 2;
		unsigned int cap3event /* cap3event, R/W, Capture3 边沿事件模式（group3-channel6）— 编码同上 */ : 2;
		unsigned int cap4event /* cap4event, R/W, Capture4 边沿事件模式（group4-channel8）— 编码同上 */ : 2;
		unsigned int cap5event /* cap5event, R/W, Capture5 边沿事件模式（group5-channel10）：`00` = posedge；`01` = nege */ : 2;
		unsigned int /* rsvd_31_18 */ /* —, Reserved, read as zero */ : 14;
	}bits;
	unsigned int u32;
} U_PWM_CAPCTL;

/* CAPINTEN (0x00000078) - CAPINTEN */
typedef union
{
	struct
	{
		unsigned int cap0cntie /* cap0cntie, R/W, Capture0 edge count interrupt enable（group0-channel0） */ : 1;
		unsigned int cap1cntie /* cap1cntie, R/W, Capture1 edge count interrupt enable（group1-channel2） */ : 1;
		unsigned int cap2cntie /* cap2cntie, R/W, Capture2 edge count interrupt enable（group2-channel4） */ : 1;
		unsigned int cap3cntie /* cap3cntie, R/W, Capture3 edge count interrupt enable（group3-channel6） */ : 1;
		unsigned int cap4cntie /* cap4cntie, R/W, Capture4 edge count interrupt enable（group4-channel8） */ : 1;
		unsigned int cap5cntie /* cap5cntie, R/W, Capture5 edge count interrupt enable（group5-channel10） */ : 1;
		unsigned int cap0timie /* cap0timie, R/W, Capture0 edge time interrupt enable（group0-channel0） */ : 1;
		unsigned int cap1timie /* cap1timie, R/W, Capture1 edge time interrupt enable（group1-channel2） */ : 1;
		unsigned int cap2timie /* cap2timie, R/W, Capture2 edge time interrupt enable（group2-channel4） */ : 1;
		unsigned int cap3timie /* cap3timie, R/W, Capture3 edge time interrupt enable（group3-channel6） */ : 1;
		unsigned int cap4timie /* cap4timie, R/W, Capture4 edge time interrupt enable（group4-channel8） */ : 1;
		unsigned int cap5timie /* cap5timie, R/W, Capture5 edge time interrupt enable（group5-channel10） */ : 1;
		unsigned int /* rsvd_31_12 */ /* —, Reserved, read as zero */ : 20;
	}bits;
	unsigned int u32;
} U_PWM_CAPINTEN;

/* CAPRIS (0x0000007c) - CAPRIS */
typedef union
{
	struct
	{
		unsigned int cap0cntris /* cap0cntris, R, Capture0 edge count raw interrupt occurs（group0-channel0） */ : 1;
		unsigned int cap1cntris /* cap1cntris, R, Capture1 edge count raw interrupt occurs（group1-channel2） */ : 1;
		unsigned int cap2cntris /* cap2cntris, R, Capture2 edge count raw interrupt occurs（group2-channel4） */ : 1;
		unsigned int cap3cntris /* cap3cntris, R, Capture3 edge count raw interrupt occurs（group3-channel6） */ : 1;
		unsigned int cap4cntris /* cap4cntris, R, Capture4 edge count raw interrupt occurs（group4-channel8） */ : 1;
		unsigned int cap5cntris /* cap5cntris, R, Capture5 edge count raw interrupt occurs（group5-channel10） */ : 1;
		unsigned int cap0timris /* cap0timris, R, Capture0 edge time raw interrupt occurs（group0-channel0） */ : 1;
		unsigned int cap1timris /* cap1timris, R, Capture1 edge time raw interrupt occurs（group1-channel2） */ : 1;
		unsigned int cap2timris /* cap2timris, R, Capture2 edge time raw interrupt occurs（group2-channel4） */ : 1;
		unsigned int cap3timris /* cap3timris, R, Capture3 edge time raw interrupt occurs（group3-channel6） */ : 1;
		unsigned int cap4timris /* cap4timris, R, Capture4 edge time raw interrupt occurs（group4-channel8） */ : 1;
		unsigned int cap5timris /* cap5timris, R, Capture5 edge time raw interrupt occurs（group5-channel10） */ : 1;
		unsigned int /* rsvd_31_12 */ /* —, Reserved, read as zero */ : 20;
	}bits;
	unsigned int u32;
} U_PWM_CAPRIS;

/* CAPIC (0x00000080) - CAPIC */
typedef union
{
	struct
	{
		unsigned int cap0cntic /* cap0cntic, R/W, Clear Capture0 edge count interrupt（group0-channel0） */ : 1;
		unsigned int cap1cntic /* cap1cntic, R/W, Clear Capture1 edge count interrupt（group1-channel2） */ : 1;
		unsigned int cap2cntic /* cap2cntic, R/W, Clear Capture2 edge count interrupt（group2-channel4） */ : 1;
		unsigned int cap3cntic /* cap3cntic, R/W, Clear Capture3 edge count interrupt（group3-channel6） */ : 1;
		unsigned int cap4cntic /* cap4cntic, R/W, Clear Capture4 edge count interrupt（group4-channel8） */ : 1;
		unsigned int cap5cntic /* cap5cntic, R/W, Clear Capture5 edge count interrupt（group5-channel10） */ : 1;
		unsigned int cap0timic /* cap0timic, R/W, Clear Capture0 edge time interrupt（group0-channel0） */ : 1;
		unsigned int cap1timic /* cap1timic, R/W, Clear Capture1 edge time interrupt（group1-channel2） */ : 1;
		unsigned int cap2timic /* cap2timic, R/W, Clear Capture2 edge time interrupt（group2-channel4） */ : 1;
		unsigned int cap3timic /* cap3timic, R/W, Clear Capture3 edge time interrupt（group3-channel6） */ : 1;
		unsigned int cap4timic /* cap4timic, R/W, Clear Capture4 edge time interrupt（group4-channel8） */ : 1;
		unsigned int cap5timic /* cap5timic, R/W, Clear Capture5 edge time interrupt（group5-channel10） */ : 1;
		unsigned int /* rsvd_31_12 */ /* —, Reserved, read as zero */ : 20;
	}bits;
	unsigned int u32;
} U_PWM_CAPIC;

/* CAPIS (0x00000084) - CAPIS */
typedef union
{
	struct
	{
		unsigned int cap0cntis /* cap0cntis, R, Capture0 edge count interrupt occurs（group0-channel0） */ : 1;
		unsigned int cap1cntis /* cap1cntis, R, Capture1 edge count interrupt occurs（group1-channel2） */ : 1;
		unsigned int cap2cntis /* cap2cntis, R, Capture2 edge count interrupt occurs（group2-channel4） */ : 1;
		unsigned int cap3cntis /* cap3cntis, R, Capture3 edge count interrupt occurs（group3-channel6） */ : 1;
		unsigned int cap4cntis /* cap4cntis, R, Capture4 edge count interrupt occurs（group4-channel8） */ : 1;
		unsigned int cap5cntis /* cap5cntis, R, Capture5 edge count interrupt occurs（group5-channel10） */ : 1;
		unsigned int cap0timis /* cap0timis, R, Capture0 edge time interrupt occurs（group0-channel0） */ : 1;
		unsigned int cap1timis /* cap1timis, R, Capture1 edge time interrupt occurs（group1-channel2） */ : 1;
		unsigned int cap2timis /* cap2timis, R, Capture2 edge time interrupt occurs（group2-channel4） */ : 1;
		unsigned int cap3timis /* cap3timis, R, Capture3 edge time interrupt occurs（group3-channel6） */ : 1;
		unsigned int cap4timis /* cap4timis, R, Capture4 edge time interrupt occurs（group4-channel8） */ : 1;
		unsigned int cap5timis /* cap5timis, R, Capture5 edge time interrupt occurs（group5-channel10） */ : 1;
		unsigned int /* rsvd_31_12 */ /* —, Reserved, read as zero */ : 20;
	}bits;
	unsigned int u32;
} U_PWM_CAPIS;

/* CAP01T (0x00000088) - 捕获事件时的 counter 值，字段名 `CAPnmTm` / `CAPnmTn`。整体 reset = `0x0000_0000`。本寄存器组的 `CAP45T` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int capnmtn /* capnmtn, R, Input capture n counter value（n=4：group5-channel8） */ : 16;
		unsigned int capnmtm /* capnmtm, R, Input capture m counter value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP01T;

/* CAP23T (0x0000008c) -  */
typedef union
{
	struct
	{
		unsigned int capnmtn /* capnmtn, R, Input capture n counter value（n=4：group5-channel8） */ : 16;
		unsigned int capnmtm /* capnmtm, R, Input capture m counter value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP23T;

/* CAP45T (0x00000090) - CAP45T */
typedef union
{
	struct
	{
		unsigned int capnmtn /* capnmtn, R, Input capture n counter value（n=4：group5-channel8） */ : 16;
		unsigned int capnmtm /* capnmtm, R, Input capture m counter value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP45T;

/* CAP01MATCH (0x00000094) - 捕获 match 值，字段名 `CAPnmMATCHm` / `CAPnmMATCHn`。整体 reset = `0x0000_0000`。本寄存器组的 `CAP45MATCH` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int capnmmatchn /* capnmmatchn, R/W, Input capture n match value（n=4：group5-channel8） */ : 16;
		unsigned int capnmmatchm /* capnmmatchm, R/W, Input capture m match value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP01MATCH;

/* CAP23MATCH (0x00000098) -  */
typedef union
{
	struct
	{
		unsigned int capnmmatchn /* capnmmatchn, R/W, Input capture n match value（n=4：group5-channel8） */ : 16;
		unsigned int capnmmatchm /* capnmmatchm, R/W, Input capture m match value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP23MATCH;

/* CAP45MATCH (0x0000009c) - CAP45MATCH */
typedef union
{
	struct
	{
		unsigned int capnmmatchn /* capnmmatchn, R/W, Input capture n match value（n=4：group5-channel8） */ : 16;
		unsigned int capnmmatchm /* capnmmatchm, R/W, Input capture m match value（m=5：group5-channel10） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CAP45MATCH;

/* TIMINTEN (0x000000a0) - TIM_INT_EN */
typedef union
{
	struct
	{
		unsigned int tim0ie /* tim0ie, R/W */ : 1;
		unsigned int tim1ie /* tim1ie, R/W */ : 1;
		unsigned int tim2ie /* tim2ie, R/W */ : 1;
		unsigned int tim3ie /* tim3ie, R/W */ : 1;
		unsigned int tim4ie /* tim4ie, R/W, Timer4 中断使能 */ : 1;
		unsigned int tim5ie /* tim5ie, R/W, Timer5 中断使能（counter = CMP match） */ : 1;
		unsigned int /* rsvd_31_6 */ /* —, Reserved */ : 26;
	}bits;
	unsigned int u32;
} U_PWM_TIMINTEN;

/* TIMRIS (0x000000a4) - TIMRIS */
typedef union
{
	struct
	{
		unsigned int tim0ris /* tim0ris, R, Timer0 raw interrupt occurs（group0） */ : 1;
		unsigned int tim1ris /* tim1ris, R, Timer1 raw interrupt occurs（group1） */ : 1;
		unsigned int tim2ris /* tim2ris, R, Timer2 raw interrupt occurs（group2） */ : 1;
		unsigned int tim3ris /* tim3ris, R, Timer3 raw interrupt occurs（group3） */ : 1;
		unsigned int tim4ris /* tim4ris, R, Timer4 raw interrupt occurs（group4） */ : 1;
		unsigned int tim5ris /* tim5ris, R, Timer5 raw interrupt occurs（group5） */ : 1;
		unsigned int /* rsvd_31_6 */ /* —, Reserved, read as zero */ : 26;
	}bits;
	unsigned int u32;
} U_PWM_TIMRIS;

/* TIMINTCLR (0x000000a8) - TIM_INT_CLR */
typedef union
{
	struct
	{
		unsigned int tim0ic /* tim0ic, R/W, Timer0 interrupt clear（group0） */ : 1;
		unsigned int tim1ic /* tim1ic, R/W, Timer1 interrupt clear（group1） */ : 1;
		unsigned int tim2ic /* tim2ic, R/W, Timer2 interrupt clear（group2） */ : 1;
		unsigned int tim3ic /* tim3ic, R/W, Timer3 interrupt clear（group3） */ : 1;
		unsigned int tim4ic /* tim4ic, R/W, Timer4 interrupt clear（group4） */ : 1;
		unsigned int tim5ic /* tim5ic, R/W, Timer5 interrupt clear（group5） */ : 1;
		unsigned int /* rsvd_31_6 */ /* —, Reserved, read as zero */ : 26;
	}bits;
	unsigned int u32;
} U_PWM_TIMINTCLR;

/* TIMIS (0x000000ac) - TIMIS */
typedef union
{
	struct
	{
		unsigned int tim0is /* tim0is, R, Timer0 interrupt occurs（group0） */ : 1;
		unsigned int tim1is /* tim1is, R, Timer1 interrupt occurs（group1） */ : 1;
		unsigned int tim2is /* tim2is, R, Timer2 interrupt occurs（group2） */ : 1;
		unsigned int tim3is /* tim3is, R, Timer3 interrupt occurs（group3） */ : 1;
		unsigned int tim4is /* tim4is, R, Timer4 interrupt occurs（group4） */ : 1;
		unsigned int tim5is /* tim5is, R, Timer5 interrupt occurs（group5） */ : 1;
		unsigned int /* rsvd_31_6 */ /* —, Reserved, read as zero */ : 26;
	}bits;
	unsigned int u32;
} U_PWM_TIMIS;

/* TIM01LOAD (0x000000b0) - 每寄存器含 2 个 16-bit timer load 值，字段名 `timloadm` / `timloadn`。整体 reset = `0x0000_0000`。本寄存器组的 `TIM45LOAD` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int timloadn /* timloadn, R/W, Timer n load value（n=4：group5） */ : 16;
		unsigned int timloadm /* timloadm, R/W, Timer m load value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM01LOAD;

/* TIM23LOAD (0x000000b4) -  */
typedef union
{
	struct
	{
		unsigned int timloadn /* timloadn, R/W, Timer n load value（n=4：group5） */ : 16;
		unsigned int timloadm /* timloadm, R/W, Timer m load value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM23LOAD;

/* TIM45LOAD (0x000000b8) - TIM45LOAD */
typedef union
{
	struct
	{
		unsigned int timloadn /* timloadn, R/W, Timer n load value（n=4：group5） */ : 16;
		unsigned int timloadm /* timloadm, R/W, Timer m load value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM45LOAD;

/* TIM01COUNT (0x000000bc) - 每寄存器含 2 个 16-bit timer 当前值，字段名 `timcntm` / `timcntn`。整体 reset = `0x0000_0000`。本寄存器组的 `TIM45COUNT` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int timcntn /* timcntn, R, Timer n current count value（n=4：group5） */ : 16;
		unsigned int timcntm /* timcntm, R, Timer m current count value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM01COUNT;

/* TIM23COUNT (0x000000c0) -  */
typedef union
{
	struct
	{
		unsigned int timcntn /* timcntn, R, Timer n current count value（n=4：group5） */ : 16;
		unsigned int timcntm /* timcntm, R, Timer m current count value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM23COUNT;

/* TIM45COUNT (0x000000c4) - TIM45COUNT */
typedef union
{
	struct
	{
		unsigned int timcntn /* timcntn, R, Timer n current count value（n=4：group5） */ : 16;
		unsigned int timcntm /* timcntm, R, Timer m current count value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_TIM45COUNT;

/* CNT01VAL (0x000000c8) - 每寄存器含 2 个 16-bit 输入脉冲计数值（edge count mode 输出），字段名 `Cntmval` / `Cntnval`。整体 reset = `0x0000_0000`。本寄存器组的 `CNT45VAL` 见下方独立子节。 */
typedef union
{
	struct
	{
		unsigned int cntnval /* cntnval, R, Counter n captured input pulse number value（n=4：group5） */ : 16;
		unsigned int cntmval /* cntmval, R, Counter m captured input pulse number value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CNT01VAL;

/* CNT23VAL (0x000000cc) -  */
typedef union
{
	struct
	{
		unsigned int cntnval /* cntnval, R, Counter n captured input pulse number value（n=4：group5） */ : 16;
		unsigned int cntmval /* cntmval, R, Counter m captured input pulse number value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CNT23VAL;

/* CNT45VAL (0x000000d0) - CNT45VAL */
typedef union
{
	struct
	{
		unsigned int cntnval /* cntnval, R, Counter n captured input pulse number value（n=4：group5） */ : 16;
		unsigned int cntmval /* cntmval, R, Counter m captured input pulse number value（m=5：group5） */ : 16;
	}bits;
	unsigned int u32;
} U_PWM_CNT45VAL;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define PWM_REG_BASE_ADDR						0x5001C000

#define PWM_PWMCFG_REG_OFFSET					0x00000000
#define PWM_PWMINVERTTRIG_REG_OFFSET					0x00000004
#define PWM_PWM01TRIG_REG_OFFSET					0x00000008
#define PWM_PWM23TRIG_REG_OFFSET					0x0000000c
#define PWM_PWM45TRIG_REG_OFFSET					0x00000010
#define PWM_PWMINTEN1_REG_OFFSET					0x00000014
#define PWM_PWMINTEN2_REG_OFFSET					0x00000018
#define PWM_PWMRIS1_REG_OFFSET					0x0000001c
#define PWM_PWMRIS2_REG_OFFSET					0x00000020
#define PWM_PWMIC1_REG_OFFSET					0x00000024
#define PWM_PWMIC2_REG_OFFSET					0x00000028
#define PWM_PWMIS1_REG_OFFSET					0x0000002c
#define PWM_PWMIS2_REG_OFFSET					0x00000030
#define PWM_PWMCTL_REG_OFFSET					0x00000034
#define PWM_PWM01LOAD_REG_OFFSET					0x00000038
#define PWM_PWM23LOAD_REG_OFFSET					0x0000003c
#define PWM_PWM45LOAD_REG_OFFSET					0x00000040
#define PWM_PWM01COUNT_REG_OFFSET					0x00000044
#define PWM_PWM23COUNT_REG_OFFSET					0x00000048
#define PWM_PWM45COUNT_REG_OFFSET					0x0000004c
#define PWM_PWM0CMP_REG_OFFSET					0x00000050
#define PWM_PWM1CMP_REG_OFFSET					0x00000054
#define PWM_PWM2CMP_REG_OFFSET					0x00000058
#define PWM_PWM3CMP_REG_OFFSET					0x0000005c
#define PWM_PWM4CMP_REG_OFFSET					0x00000060
#define PWM_PWM5CMP_REG_OFFSET					0x00000064
#define PWM_PWM01DB_REG_OFFSET					0x00000068
#define PWM_PWM23DB_REG_OFFSET					0x0000006c
#define PWM_PWM45DB_REG_OFFSET					0x00000070
#define PWM_CAPCTL_REG_OFFSET					0x00000074
#define PWM_CAPINTEN_REG_OFFSET					0x00000078
#define PWM_CAPRIS_REG_OFFSET					0x0000007c
#define PWM_CAPIC_REG_OFFSET					0x00000080
#define PWM_CAPIS_REG_OFFSET					0x00000084
#define PWM_CAP01T_REG_OFFSET					0x00000088
#define PWM_CAP23T_REG_OFFSET					0x0000008c
#define PWM_CAP45T_REG_OFFSET					0x00000090
#define PWM_CAP01MATCH_REG_OFFSET					0x00000094
#define PWM_CAP23MATCH_REG_OFFSET					0x00000098
#define PWM_CAP45MATCH_REG_OFFSET					0x0000009c
#define PWM_TIMINTEN_REG_OFFSET					0x000000a0
#define PWM_TIMRIS_REG_OFFSET					0x000000a4
#define PWM_TIMINTCLR_REG_OFFSET					0x000000a8
#define PWM_TIMIS_REG_OFFSET					0x000000ac
#define PWM_TIM01LOAD_REG_OFFSET					0x000000b0
#define PWM_TIM23LOAD_REG_OFFSET					0x000000b4
#define PWM_TIM45LOAD_REG_OFFSET					0x000000b8
#define PWM_TIM01COUNT_REG_OFFSET					0x000000bc
#define PWM_TIM23COUNT_REG_OFFSET					0x000000c0
#define PWM_TIM45COUNT_REG_OFFSET					0x000000c4
#define PWM_CNT01VAL_REG_OFFSET					0x000000c8
#define PWM_CNT23VAL_REG_OFFSET					0x000000cc
#define PWM_CNT45VAL_REG_OFFSET					0x000000d0

#define PWM_PWMCFG_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMCFG_REG_OFFSET)
#define PWM_PWMINVERTTRIG_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMINVERTTRIG_REG_OFFSET)
#define PWM_PWM01TRIG_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM01TRIG_REG_OFFSET)
#define PWM_PWM23TRIG_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM23TRIG_REG_OFFSET)
#define PWM_PWM45TRIG_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM45TRIG_REG_OFFSET)
#define PWM_PWMINTEN1_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMINTEN1_REG_OFFSET)
#define PWM_PWMINTEN2_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMINTEN2_REG_OFFSET)
#define PWM_PWMRIS1_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMRIS1_REG_OFFSET)
#define PWM_PWMRIS2_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMRIS2_REG_OFFSET)
#define PWM_PWMIC1_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMIC1_REG_OFFSET)
#define PWM_PWMIC2_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMIC2_REG_OFFSET)
#define PWM_PWMIS1_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMIS1_REG_OFFSET)
#define PWM_PWMIS2_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMIS2_REG_OFFSET)
#define PWM_PWMCTL_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWMCTL_REG_OFFSET)
#define PWM_PWM01LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM01LOAD_REG_OFFSET)
#define PWM_PWM23LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM23LOAD_REG_OFFSET)
#define PWM_PWM45LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM45LOAD_REG_OFFSET)
#define PWM_PWM01COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM01COUNT_REG_OFFSET)
#define PWM_PWM23COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM23COUNT_REG_OFFSET)
#define PWM_PWM45COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM45COUNT_REG_OFFSET)
#define PWM_PWM0CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM0CMP_REG_OFFSET)
#define PWM_PWM1CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM1CMP_REG_OFFSET)
#define PWM_PWM2CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM2CMP_REG_OFFSET)
#define PWM_PWM3CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM3CMP_REG_OFFSET)
#define PWM_PWM4CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM4CMP_REG_OFFSET)
#define PWM_PWM5CMP_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM5CMP_REG_OFFSET)
#define PWM_PWM01DB_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM01DB_REG_OFFSET)
#define PWM_PWM23DB_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM23DB_REG_OFFSET)
#define PWM_PWM45DB_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_PWM45DB_REG_OFFSET)
#define PWM_CAPCTL_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAPCTL_REG_OFFSET)
#define PWM_CAPINTEN_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAPINTEN_REG_OFFSET)
#define PWM_CAPRIS_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAPRIS_REG_OFFSET)
#define PWM_CAPIC_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAPIC_REG_OFFSET)
#define PWM_CAPIS_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAPIS_REG_OFFSET)
#define PWM_CAP01T_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP01T_REG_OFFSET)
#define PWM_CAP23T_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP23T_REG_OFFSET)
#define PWM_CAP45T_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP45T_REG_OFFSET)
#define PWM_CAP01MATCH_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP01MATCH_REG_OFFSET)
#define PWM_CAP23MATCH_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP23MATCH_REG_OFFSET)
#define PWM_CAP45MATCH_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CAP45MATCH_REG_OFFSET)
#define PWM_TIMINTEN_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIMINTEN_REG_OFFSET)
#define PWM_TIMRIS_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIMRIS_REG_OFFSET)
#define PWM_TIMINTCLR_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIMINTCLR_REG_OFFSET)
#define PWM_TIMIS_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIMIS_REG_OFFSET)
#define PWM_TIM01LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM01LOAD_REG_OFFSET)
#define PWM_TIM23LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM23LOAD_REG_OFFSET)
#define PWM_TIM45LOAD_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM45LOAD_REG_OFFSET)
#define PWM_TIM01COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM01COUNT_REG_OFFSET)
#define PWM_TIM23COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM23COUNT_REG_OFFSET)
#define PWM_TIM45COUNT_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_TIM45COUNT_REG_OFFSET)
#define PWM_CNT01VAL_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CNT01VAL_REG_OFFSET)
#define PWM_CNT23VAL_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CNT23VAL_REG_OFFSET)
#define PWM_CNT45VAL_REG_ADDR						(PWM_REG_BASE_ADDR + PWM_CNT45VAL_REG_OFFSET)

#endif //__PWM_REG_DEF_H__
