/* PWM Register Definition (SystemVerilog Header) */
#ifndef __PWM_REG_DEF_SVH__
#define __PWM_REG_DEF_SVH__

/*
 * ============================================================================
 * PWM Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x5001C000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* PWMCFG (0x00000000) - PWMCFG */
typedef union {
    struct packed {
        const bit[3:0]   /* rsvd_31_28 */ /* — */;
        bit                 cntdiven /* cntdiven, R/W */;
        bit[2:0]        cntdiv /* cntdiv, R/W */;
        bit                 tim5en /* tim5en, R/W */;
        bit                 tim4en /* tim4en, R/W */;
        bit                 tim3en /* tim3en, R/W */;
        bit                 tim2en /* tim2en, R/W */;
        bit                 tim1en /* tim1en, R/W */;
        bit                 tim0en /* tim0en, R/W */;
        bit                 cap5en /* cap5en, R/W */;
        bit                 cap4en /* cap4en, R/W */;
        bit                 cap3en /* cap3en, R/W */;
        bit                 cap2en /* cap2en, R/W */;
        bit                 cap1en /* cap1en, R/W */;
        bit                 cap0en /* cap0en, R/W */;
        bit                 pwm11en /* pwm11en, R/W */;
        bit                 pwm10en /* pwm10en, R/W */;
        bit                 pwm9en /* pwm9en, R/W */;
        bit                 pwm8en /* pwm8en, R/W */;
        bit                 pwm7en /* pwm7en, R/W */;
        bit                 pwm6en /* pwm6en, R/W */;
        bit                 pwm5en /* pwm5en, R/W */;
        bit                 pwm4en /* pwm4en, R/W */;
        bit                 pwm3en /* pwm3en, R/W */;
        bit                 pwm2en /* pwm2en, R/W */;
        bit                 pwm1en /* pwm1en, R/W */;
        bit                 pwm0en /* pwm0en, R/W */;
    }bits;
    int unsigned u32 = {4'h0, 1'h0, 3'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMCFG;

/* PWMINVERTTRIG (0x00000004) - PWMINVERTTRIG */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* — */;
        bit                 pwm11inv /* pwm11inv, R/W */;
        bit                 pwm10inv /* pwm10inv, R/W */;
        bit                 pwm9inv /* pwm9inv, R/W */;
        bit                 pwm8inv /* pwm8inv, R/W */;
        bit                 pwm7inv /* pwm7inv, R/W */;
        bit                 pwm6inv /* pwm6inv, R/W */;
        bit                 pwm5inv /* pwm5inv, R/W */;
        bit                 pwm4inv /* pwm4inv, R/W */;
        bit                 pwm3inv /* pwm3inv, R/W */;
        bit                 pwm2inv /* pwm2inv, R/W */;
        bit                 pwm1inv /* pwm1inv, R/W */;
        bit                 pwm0inv /* pwm0inv, R/W */;
    }bits;
    int unsigned u32 = {20'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMINVERTTRIG;

/* PWM01TRIG (0x00000008) - PWM01TRIG */
typedef union {
    struct packed {
        bit[15:0]        pwm1trig /* pwm1trig, R/W */;
        bit[15:0]        pwm0trig /* pwm0trig, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM01TRIG;

/* PWM23TRIG (0x0000000c) - PWM23TRIG */
typedef union {
    struct packed {
        bit[15:0]        pwm3trig /* pwm3trig, R/W */;
        bit[15:0]        pwm2trig /* pwm2trig, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM23TRIG;

/* PWM45TRIG (0x00000010) - PWM45TRIG */
typedef union {
    struct packed {
        bit[15:0]        pwm5trig /* pwm5trig, R/W */;
        bit[15:0]        pwm4trig /* pwm4trig, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM45TRIG;

/* PWMINTEN1 (0x00000014) - PWMINTEN1 */
typedef union {
    struct packed {
        const bit[1:0]   /* rsvd_31_30 */ /* — */;
        bit                 int2encmpbd /* int2encmpbd, R/W */;
        bit                 int2encmpad /* int2encmpad, R/W */;
        bit                 int2encmpbu /* int2encmpbu, R/W */;
        bit                 int2encmpau /* int2encmpau, R/W */;
        bit                 int2encntload /* int2encntload, R/W */;
        bit                 int2encntzero /* int2encntzero, R/W */;
        const bit[1:0]   /* rsvd_23_22 */ /* — */;
        bit                 int1encmpbd /* int1encmpbd, R/W */;
        bit                 int1encmpad /* int1encmpad, R/W */;
        bit                 int1encmpbu /* int1encmpbu, R/W */;
        bit                 int1encmpau /* int1encmpau, R/W */;
        bit                 int1encntload /* int1encntload, R/W */;
        bit                 int1encntzero /* int1encntzero, R/W */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 int0encmpbd /* int0encmpbd, R/W */;
        bit                 int0encmpad /* int0encmpad, R/W */;
        bit                 int0encmpbu /* int0encmpbu, R/W */;
        bit                 int0encmpau /* int0encmpau, R/W */;
        bit                 int0encntload /* int0encntload, R/W */;
        bit                 int0encntzero /* int0encntzero, R/W */;
        const bit[7:0]   /* rsvd_7_0 */ /* — */;
    }bits;
    int unsigned u32 = {2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 8'h0};
} U_PWM_PWMINTEN1;

/* PWMINTEN2 (0x00000018) - PWMINTEN2 */
typedef union {
    struct packed {
        const bit[9:0]   /* rsvd_31_22 */ /* — */;
        bit                 int5encmpbd /* int5encmpbd, R/W */;
        bit                 int5encmpad /* int5encmpad, R/W */;
        bit                 int5encmpbu /* int5encmpbu, R/W */;
        bit                 int5encmpau /* int5encmpau, R/W */;
        bit                 int5encntload /* int5encntload, R/W */;
        bit                 int5encntzero /* int5encntzero, R/W */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 int4encmpbd /* int4encmpbd, R/W */;
        bit                 int4encmpad /* int4encmpad, R/W */;
        bit                 int4encmpbu /* int4encmpbu, R/W */;
        bit                 int4encmpau /* int4encmpau, R/W */;
        bit                 int4encntload /* int4encntload, R/W */;
        bit                 int4encntzero /* int4encntzero, R/W */;
        const bit[1:0]   /* rsvd_7_6 */ /* — */;
        bit                 int3encmpbd /* int3encmpbd, R/W */;
        bit                 int3encmpad /* int3encmpad, R/W */;
        bit                 int3encmpbu /* int3encmpbu, R/W */;
        bit                 int3encmpau /* int3encmpau, R/W */;
        bit                 int3encntload /* int3encntload, R/W */;
        bit                 int3encntzero /* int3encntzero, R/W */;
    }bits;
    int unsigned u32 = {10'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMINTEN2;

/* PWMRIS1 (0x0000001c) - PWMRIS1 */
typedef union {
    struct packed {
        const bit[1:0]   /* rsvd_31_30 */ /* — */;
        bit                 intris2cmpbd /* intris2cmpbd, R */;
        bit                 intris2cmpad /* intris2cmpad, R */;
        bit                 intris2cmpbu /* intris2cmpbu, R */;
        bit                 intris2cmpau /* intris2cmpau, R */;
        bit                 intris2cntload /* intris2cntload, R */;
        bit                 intris2cntzero /* intris2cntzero, R */;
        const bit[1:0]   /* rsvd_23_22 */ /* — */;
        bit                 intris1cmpbd /* intris1cmpbd, R */;
        bit                 intris1cmpad /* intris1cmpad, R */;
        bit                 intris1cmpbu /* intris1cmpbu, R */;
        bit                 intris1cmpau /* intris1cmpau, R */;
        bit                 intris1cntload /* intris1cntload, R */;
        bit                 intris1cntzero /* intris1cntzero, R */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intris0cmpbd /* intris0cmpbd, R */;
        bit                 intris0cmpad /* intris0cmpad, R */;
        bit                 intris0cmpbu /* intris0cmpbu, R */;
        bit                 intris0cmpau /* intris0cmpau, R */;
        bit                 intris0cntload /* intris0cntload, R */;
        bit                 intris0cntzero /* intris0cntzero, R */;
        const bit[7:0]   /* rsvd_7_0 */ /* — */;
    }bits;
    int unsigned u32 = {2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 8'h0};
} U_PWM_PWMRIS1;

/* PWMRIS2 (0x00000020) - PWMRIS2 */
typedef union {
    struct packed {
        const bit[9:0]   /* rsvd_31_22 */ /* — */;
        bit                 intris5cmpbd /* intris5cmpbd, R */;
        bit                 intris5cmpad /* intris5cmpad, R */;
        bit                 intris5cmpbu /* intris5cmpbu, R */;
        bit                 intris5cmpau /* intris5cmpau, R */;
        bit                 intris5cntload /* intris5cntload, R */;
        bit                 intris5cntzero /* intris5cntzero, R */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intris4cmpbd /* intris4cmpbd, R */;
        bit                 intris4cmpad /* intris4cmpad, R */;
        bit                 intris4cmpbu /* intris4cmpbu, R */;
        bit                 intris4cmpau /* intris4cmpau, R */;
        bit                 intris4cntload /* intris4cntload, R */;
        bit                 intris4cntzero /* intris4cntzero, R */;
        const bit[1:0]   /* rsvd_7_6 */ /* — */;
        bit                 intris3cmpbd /* intris3cmpbd, R */;
        bit                 intris3cmpad /* intris3cmpad, R */;
        bit                 intris3cmpbu /* intris3cmpbu, R */;
        bit                 intris3cmpau /* intris3cmpau, R */;
        bit                 intris3cntload /* intris3cntload, R */;
        bit                 intris3cntzero /* intris3cntzero, R */;
    }bits;
    int unsigned u32 = {10'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMRIS2;

/* PWMIC1 (0x00000024) - PWMIC1 */
typedef union {
    struct packed {
        const bit[1:0]   /* rsvd_31_30 */ /* — */;
        bit                 intic2cmpbd /* intic2cmpbd, R/W */;
        bit                 intic2cmpad /* intic2cmpad, R/W */;
        bit                 intic2cmpbu /* intic2cmpbu, R/W */;
        bit                 intic2cmpau /* intic2cmpau, R/W */;
        bit                 intic2cntload /* intic2cntload, R/W */;
        bit                 intic2cntzero /* intic2cntzero, R/W */;
        const bit[1:0]   /* rsvd_23_22 */ /* — */;
        bit                 intic1cmpbd /* intic1cmpbd, R/W */;
        bit                 intic1cmpad /* intic1cmpad, R/W */;
        bit                 intic1cmpbu /* intic1cmpbu, R/W */;
        bit                 intic1cmpau /* intic1cmpau, R/W */;
        bit                 intic1cntload /* intic1cntload, R/W */;
        bit                 intic1cntzero /* intic1cntzero, R/W */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intic0cmpbd /* intic0cmpbd, R/W */;
        bit                 intic0cmpad /* intic0cmpad, R/W */;
        bit                 intic0cmpbu /* intic0cmpbu, R/W */;
        bit                 intic0cmpau /* intic0cmpau, R/W */;
        bit                 intic0cntload /* intic0cntload, R/W */;
        bit                 intic0cntzero /* intic0cntzero, R/W */;
        const bit[7:0]   /* rsvd_7_0 */ /* — */;
    }bits;
    int unsigned u32 = {2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 8'h0};
} U_PWM_PWMIC1;

/* PWMIC2 (0x00000028) - PWMIC2 */
typedef union {
    struct packed {
        const bit[9:0]   /* rsvd_31_22 */ /* — */;
        bit                 intic5cmpbd /* intic5cmpbd, R/W */;
        bit                 intic5cmpad /* intic5cmpad, R/W */;
        bit                 intic5cmpbu /* intic5cmpbu, R/W */;
        bit                 intic5cmpau /* intic5cmpau, R/W */;
        bit                 intic5cntload /* intic5cntload, R/W */;
        bit                 intic5cntzero /* intic5cntzero, R/W */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intic4cmpbd /* intic4cmpbd, R/W */;
        bit                 intic4cmpad /* intic4cmpad, R/W */;
        bit                 intic4cmpbu /* intic4cmpbu, R/W */;
        bit                 intic4cmpau /* intic4cmpau, R/W */;
        bit                 intic4cntload /* intic4cntload, R/W */;
        bit                 intic4cntzero /* intic4cntzero, R/W */;
        const bit[1:0]   /* rsvd_7_6 */ /* — */;
        bit                 intic3cmpbd /* intic3cmpbd, R/W */;
        bit                 intic3cmpad /* intic3cmpad, R/W */;
        bit                 intic3cmpbu /* intic3cmpbu, R/W */;
        bit                 intic3cmpau /* intic3cmpau, R/W */;
        bit                 intic3cntload /* intic3cntload, R/W */;
        bit                 intic3cntzero /* intic3cntzero, R/W */;
    }bits;
    int unsigned u32 = {10'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMIC2;

/* PWMIS1 (0x0000002c) - PWMIS1 */
typedef union {
    struct packed {
        const bit[1:0]   /* rsvd_31_30 */ /* — */;
        bit                 intis2cmpbd /* intis2cmpbd, R */;
        bit                 intis2cmpad /* intis2cmpad, R */;
        bit                 intis2cmpbu /* intis2cmpbu, R */;
        bit                 intis2cmpau /* intis2cmpau, R */;
        bit                 intis2cntload /* intis2cntload, R */;
        bit                 intis2cntzero /* intis2cntzero, R */;
        const bit[1:0]   /* rsvd_23_22 */ /* — */;
        bit                 intis1cmpbd /* intis1cmpbd, R */;
        bit                 intis1cmpad /* intis1cmpad, R */;
        bit                 intis1cmpbu /* intis1cmpbu, R */;
        bit                 intis1cmpau /* intis1cmpau, R */;
        bit                 intis1cntload /* intis1cntload, R */;
        bit                 intis1cntzero /* intis1cntzero, R */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intis0cmpbd /* intis0cmpbd, R */;
        bit                 intis0cmpad /* intis0cmpad, R */;
        bit                 intis0cmpbu /* intis0cmpbu, R */;
        bit                 intis0cmpau /* intis0cmpau, R */;
        bit                 intis0cntload /* intis0cntload, R */;
        bit                 intis0cntzero /* intis0cntzero, R */;
        const bit[7:0]   /* rsvd_7_0 */ /* — */;
    }bits;
    int unsigned u32 = {2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 8'h0};
} U_PWM_PWMIS1;

/* PWMIS2 (0x00000030) - PWMIS2 */
typedef union {
    struct packed {
        const bit[9:0]   /* rsvd_31_22 */ /* — */;
        bit                 intis5cmpbd /* intis5cmpbd, R */;
        bit                 intis5cmpad /* intis5cmpad, R */;
        bit                 intis5cmpbu /* intis5cmpbu, R */;
        bit                 intis5cmpau /* intis5cmpau, R */;
        bit                 intis5cntload /* intis5cntload, R */;
        bit                 intis5cntzero /* intis5cntzero, R */;
        const bit[1:0]   /* rsvd_15_14 */ /* — */;
        bit                 intis4cmpbd /* intis4cmpbd, R */;
        bit                 intis4cmpad /* intis4cmpad, R */;
        bit                 intis4cmpbu /* intis4cmpbu, R */;
        bit                 intis4cmpau /* intis4cmpau, R */;
        bit                 intis4cntload /* intis4cntload, R */;
        bit                 intis4cntzero /* intis4cntzero, R */;
        const bit[1:0]   /* rsvd_7_6 */ /* — */;
        bit                 intis3cmpbd /* intis3cmpbd, R */;
        bit                 intis3cmpad /* intis3cmpad, R */;
        bit                 intis3cmpbu /* intis3cmpbu, R */;
        bit                 intis3cmpau /* intis3cmpau, R */;
        bit                 intis3cntload /* intis3cntload, R */;
        bit                 intis3cntzero /* intis3cntzero, R */;
    }bits;
    int unsigned u32 = {10'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMIS2;

/* PWMCTL (0x00000034) - PWMCTL */
typedef union {
    struct packed {
        const bit[13:0]   /* rsvd_31_18 */ /* — */;
        bit[1:0]        sync5mode /* sync5mode, R/W */;
        bit[1:0]        sync4mode /* sync4mode, R/W */;
        bit[1:0]        sync3mode /* sync3mode, R/W */;
        bit[1:0]        sync2mode /* sync2mode, R/W */;
        bit[1:0]        sync1mode /* sync1mode, R/W */;
        bit[1:0]        sync0mode /* sync0mode, R/W */;
        bit                 pwm5mode /* pwm5mode, R/W */;
        bit                 pwm4mode /* pwm4mode, R/W */;
        bit                 pwm3mode /* pwm3mode, R/W */;
        bit                 pwm2mode /* pwm2mode, R/W */;
        bit                 pwm1mode /* pwm1mode, R/W */;
        bit                 pwm0mode /* pwm0mode, R/W */;
    }bits;
    int unsigned u32 = {14'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_PWMCTL;

/* PWM01LOAD (0x00000038) - 每 register 内含 2 个 16-bit load value（对应同一对 group 的两个计数器），字段名 `loadm` / `loadn`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM45LOAD` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        loadm /* loadm, R/W */;
        bit[15:0]        loadn /* loadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM01LOAD;

/* PWM23LOAD (0x0000003c) -  */
typedef union {
    struct packed {
        bit[15:0]        loadm /* loadm, R/W */;
        bit[15:0]        loadn /* loadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM23LOAD;

/* PWM45LOAD (0x00000040) - PWM45LOAD */
typedef union {
    struct packed {
        bit[15:0]        loadm /* loadm, R/W */;
        bit[15:0]        loadn /* loadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM45LOAD;

/* PWM01COUNT (0x00000044) - 只读当前计数器值，字段名 `countm` / `countn`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM45COUNT` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        countm /* countm, R */;
        bit[15:0]        countn /* countn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM01COUNT;

/* PWM23COUNT (0x00000048) -  */
typedef union {
    struct packed {
        bit[15:0]        countm /* countm, R */;
        bit[15:0]        countn /* countn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM23COUNT;

/* PWM45COUNT (0x0000004c) - PWM45COUNT */
typedef union {
    struct packed {
        bit[15:0]        countm /* countm, R */;
        bit[15:0]        countn /* countn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM45COUNT;

/* PWM0CMP (0x00000050) - 每寄存器 32-bit 内含 2 个 16-bit compare value（高 16-bit = 该 group 第 2 通道 CMP_B，低 16-bit = 第 1 通道 CMP_A），字段名 `compnb` / `compna`。整体 reset = `0x0000_0000`。本寄存器组的 `PWM5CMP` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM0CMP;

/* PWM1CMP (0x00000054) -  */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM1CMP;

/* PWM2CMP (0x00000058) -  */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM2CMP;

/* PWM3CMP (0x0000005c) -  */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM3CMP;

/* PWM4CMP (0x00000060) -  */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM4CMP;

/* PWM5CMP (0x00000064) - PWM5CMP */
typedef union {
    struct packed {
        bit[15:0]        compnb /* compnb, R/W */;
        bit[15:0]        compna /* compna, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_PWM5CMP;

/* PWM01DB (0x00000068) - 死区（dead-band）延迟计数值，用于互补 PWM 输出延迟插入；位域结构见下方 `PWM45DB` 独立子节。整体 reset = `0x0000_0000`。 */
typedef union {
    struct packed {
        const bit[5:0]   /* rsvd_31_26 */ /* — */;
        bit                 dbmen /* dbmen, R/W */;
        bit                 dbnen /* dbnen, R/W */;
        bit[11:0]        delaym /* delaym, R/W */;
        bit[11:0]        delayn /* delayn, R/W */;
    }bits;
    int unsigned u32 = {6'h0, 1'h0, 1'h0, 12'h0, 12'h0};
} U_PWM_PWM01DB;

/* PWM23DB (0x0000006c) -  */
typedef union {
    struct packed {
        const bit[5:0]   /* rsvd_31_26 */ /* — */;
        bit                 dbmen /* dbmen, R/W */;
        bit                 dbnen /* dbnen, R/W */;
        bit[11:0]        delaym /* delaym, R/W */;
        bit[11:0]        delayn /* delayn, R/W */;
    }bits;
    int unsigned u32 = {6'h0, 1'h0, 1'h0, 12'h0, 12'h0};
} U_PWM_PWM23DB;

/* PWM45DB (0x00000070) - PWM45DB */
typedef union {
    struct packed {
        const bit[5:0]   /* rsvd_31_26 */ /* — */;
        bit                 dbmen /* dbmen, R/W */;
        bit                 dbnen /* dbnen, R/W */;
        bit[11:0]        delaym /* delaym, R/W */;
        bit[11:0]        delayn /* delayn, R/W */;
    }bits;
    int unsigned u32 = {6'h0, 1'h0, 1'h0, 12'h0, 12'h0};
} U_PWM_PWM45DB;

/* CAPCTL (0x00000074) - 字段命名与功能（user guide Table 6-19）： */
typedef union {
    struct packed {
        const bit[13:0]   /* rsvd_31_18 */ /* — */;
        bit[1:0]        cap5event /* cap5event, R/W */;
        bit[1:0]        cap4event /* cap4event, R/W */;
        bit[1:0]        cap3event /* cap3event, R/W */;
        bit[1:0]        cap2event /* cap2event, R/W */;
        bit[1:0]        cap1event /* cap1event, R/W */;
        bit[1:0]        cap0event /* cap0event, R/W */;
        bit                 cap5mode /* cap5mode, R/W */;
        bit                 cap4mode /* cap4mode, R/W */;
        bit                 cap3mode /* cap3mode, R/W */;
        bit                 cap2mode /* cap2mode, R/W */;
        bit                 cap1mode /* cap1mode, R/W */;
        bit                 cap0mode /* cap0mode, R/W */;
    }bits;
    int unsigned u32 = {14'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 2'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_CAPCTL;

/* CAPINTEN (0x00000078) - CAPINTEN */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* — */;
        bit                 cap5timie /* cap5timie, R/W */;
        bit                 cap4timie /* cap4timie, R/W */;
        bit                 cap3timie /* cap3timie, R/W */;
        bit                 cap2timie /* cap2timie, R/W */;
        bit                 cap1timie /* cap1timie, R/W */;
        bit                 cap0timie /* cap0timie, R/W */;
        bit                 cap5cntie /* cap5cntie, R/W */;
        bit                 cap4cntie /* cap4cntie, R/W */;
        bit                 cap3cntie /* cap3cntie, R/W */;
        bit                 cap2cntie /* cap2cntie, R/W */;
        bit                 cap1cntie /* cap1cntie, R/W */;
        bit                 cap0cntie /* cap0cntie, R/W */;
    }bits;
    int unsigned u32 = {20'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_CAPINTEN;

/* CAPRIS (0x0000007c) - CAPRIS */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* — */;
        bit                 cap5timris /* cap5timris, R */;
        bit                 cap4timris /* cap4timris, R */;
        bit                 cap3timris /* cap3timris, R */;
        bit                 cap2timris /* cap2timris, R */;
        bit                 cap1timris /* cap1timris, R */;
        bit                 cap0timris /* cap0timris, R */;
        bit                 cap5cntris /* cap5cntris, R */;
        bit                 cap4cntris /* cap4cntris, R */;
        bit                 cap3cntris /* cap3cntris, R */;
        bit                 cap2cntris /* cap2cntris, R */;
        bit                 cap1cntris /* cap1cntris, R */;
        bit                 cap0cntris /* cap0cntris, R */;
    }bits;
    int unsigned u32 = {20'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_CAPRIS;

/* CAPIC (0x00000080) - CAPIC */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* — */;
        bit                 cap5timic /* cap5timic, R/W */;
        bit                 cap4timic /* cap4timic, R/W */;
        bit                 cap3timic /* cap3timic, R/W */;
        bit                 cap2timic /* cap2timic, R/W */;
        bit                 cap1timic /* cap1timic, R/W */;
        bit                 cap0timic /* cap0timic, R/W */;
        bit                 cap5cntic /* cap5cntic, R/W */;
        bit                 cap4cntic /* cap4cntic, R/W */;
        bit                 cap3cntic /* cap3cntic, R/W */;
        bit                 cap2cntic /* cap2cntic, R/W */;
        bit                 cap1cntic /* cap1cntic, R/W */;
        bit                 cap0cntic /* cap0cntic, R/W */;
    }bits;
    int unsigned u32 = {20'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_CAPIC;

/* CAPIS (0x00000084) - CAPIS */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* — */;
        bit                 cap5timis /* cap5timis, R */;
        bit                 cap4timis /* cap4timis, R */;
        bit                 cap3timis /* cap3timis, R */;
        bit                 cap2timis /* cap2timis, R */;
        bit                 cap1timis /* cap1timis, R */;
        bit                 cap0timis /* cap0timis, R */;
        bit                 cap5cntis /* cap5cntis, R */;
        bit                 cap4cntis /* cap4cntis, R */;
        bit                 cap3cntis /* cap3cntis, R */;
        bit                 cap2cntis /* cap2cntis, R */;
        bit                 cap1cntis /* cap1cntis, R */;
        bit                 cap0cntis /* cap0cntis, R */;
    }bits;
    int unsigned u32 = {20'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_CAPIS;

/* CAP01T (0x00000088) - 捕获事件时的 counter 值，字段名 `CAPnmTm` / `CAPnmTn`。整体 reset = `0x0000_0000`。本寄存器组的 `CAP45T` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        capnmtm /* capnmtm, R */;
        bit[15:0]        capnmtn /* capnmtn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP01T;

/* CAP23T (0x0000008c) -  */
typedef union {
    struct packed {
        bit[15:0]        capnmtm /* capnmtm, R */;
        bit[15:0]        capnmtn /* capnmtn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP23T;

/* CAP45T (0x00000090) - CAP45T */
typedef union {
    struct packed {
        bit[15:0]        capnmtm /* capnmtm, R */;
        bit[15:0]        capnmtn /* capnmtn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP45T;

/* CAP01MATCH (0x00000094) - 捕获 match 值，字段名 `CAPnmMATCHm` / `CAPnmMATCHn`。整体 reset = `0x0000_0000`。本寄存器组的 `CAP45MATCH` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        capnmmatchm /* capnmmatchm, R/W */;
        bit[15:0]        capnmmatchn /* capnmmatchn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP01MATCH;

/* CAP23MATCH (0x00000098) -  */
typedef union {
    struct packed {
        bit[15:0]        capnmmatchm /* capnmmatchm, R/W */;
        bit[15:0]        capnmmatchn /* capnmmatchn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP23MATCH;

/* CAP45MATCH (0x0000009c) - CAP45MATCH */
typedef union {
    struct packed {
        bit[15:0]        capnmmatchm /* capnmmatchm, R/W */;
        bit[15:0]        capnmmatchn /* capnmmatchn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CAP45MATCH;

/* TIMINTEN (0x000000a0) - TIM_INT_EN */
typedef union {
    struct packed {
        const bit[25:0]   /* rsvd_31_6 */ /* — */;
        bit                 tim5ie /* tim5ie, R/W */;
        bit                 tim4ie /* tim4ie, R/W */;
        bit                 tim3ie /* tim3ie, R/W */;
        bit                 tim2ie /* tim2ie, R/W */;
        bit                 tim1ie /* tim1ie, R/W */;
        bit                 tim0ie /* tim0ie, R/W */;
    }bits;
    int unsigned u32 = {26'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_TIMINTEN;

/* TIMRIS (0x000000a4) - TIMRIS */
typedef union {
    struct packed {
        const bit[25:0]   /* rsvd_31_6 */ /* — */;
        bit                 tim5ris /* tim5ris, R */;
        bit                 tim4ris /* tim4ris, R */;
        bit                 tim3ris /* tim3ris, R */;
        bit                 tim2ris /* tim2ris, R */;
        bit                 tim1ris /* tim1ris, R */;
        bit                 tim0ris /* tim0ris, R */;
    }bits;
    int unsigned u32 = {26'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_TIMRIS;

/* TIMINTCLR (0x000000a8) - TIM_INT_CLR */
typedef union {
    struct packed {
        const bit[25:0]   /* rsvd_31_6 */ /* — */;
        bit                 tim5ic /* tim5ic, R/W */;
        bit                 tim4ic /* tim4ic, R/W */;
        bit                 tim3ic /* tim3ic, R/W */;
        bit                 tim2ic /* tim2ic, R/W */;
        bit                 tim1ic /* tim1ic, R/W */;
        bit                 tim0ic /* tim0ic, R/W */;
    }bits;
    int unsigned u32 = {26'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_TIMINTCLR;

/* TIMIS (0x000000ac) - TIMIS */
typedef union {
    struct packed {
        const bit[25:0]   /* rsvd_31_6 */ /* — */;
        bit                 tim5is /* tim5is, R */;
        bit                 tim4is /* tim4is, R */;
        bit                 tim3is /* tim3is, R */;
        bit                 tim2is /* tim2is, R */;
        bit                 tim1is /* tim1is, R */;
        bit                 tim0is /* tim0is, R */;
    }bits;
    int unsigned u32 = {26'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_PWM_TIMIS;

/* TIM01LOAD (0x000000b0) - 每寄存器含 2 个 16-bit timer load 值，字段名 `timloadm` / `timloadn`。整体 reset = `0x0000_0000`。本寄存器组的 `TIM45LOAD` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        timloadm /* timloadm, R/W */;
        bit[15:0]        timloadn /* timloadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM01LOAD;

/* TIM23LOAD (0x000000b4) -  */
typedef union {
    struct packed {
        bit[15:0]        timloadm /* timloadm, R/W */;
        bit[15:0]        timloadn /* timloadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM23LOAD;

/* TIM45LOAD (0x000000b8) - TIM45LOAD */
typedef union {
    struct packed {
        bit[15:0]        timloadm /* timloadm, R/W */;
        bit[15:0]        timloadn /* timloadn, R/W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM45LOAD;

/* TIM01COUNT (0x000000bc) - 每寄存器含 2 个 16-bit timer 当前值，字段名 `timcntm` / `timcntn`。整体 reset = `0x0000_0000`。本寄存器组的 `TIM45COUNT` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        timcntm /* timcntm, R */;
        bit[15:0]        timcntn /* timcntn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM01COUNT;

/* TIM23COUNT (0x000000c0) -  */
typedef union {
    struct packed {
        bit[15:0]        timcntm /* timcntm, R */;
        bit[15:0]        timcntn /* timcntn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM23COUNT;

/* TIM45COUNT (0x000000c4) - TIM45COUNT */
typedef union {
    struct packed {
        bit[15:0]        timcntm /* timcntm, R */;
        bit[15:0]        timcntn /* timcntn, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_TIM45COUNT;

/* CNT01VAL (0x000000c8) - 每寄存器含 2 个 16-bit 输入脉冲计数值（edge count mode 输出），字段名 `Cntmval` / `Cntnval`。整体 reset = `0x0000_0000`。本寄存器组的 `CNT45VAL` 见下方独立子节。 */
typedef union {
    struct packed {
        bit[15:0]        cntmval /* cntmval, R */;
        bit[15:0]        cntnval /* cntnval, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CNT01VAL;

/* CNT23VAL (0x000000cc) -  */
typedef union {
    struct packed {
        bit[15:0]        cntmval /* cntmval, R */;
        bit[15:0]        cntnval /* cntnval, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CNT23VAL;

/* CNT45VAL (0x000000d0) - CNT45VAL */
typedef union {
    struct packed {
        bit[15:0]        cntmval /* cntmval, R */;
        bit[15:0]        cntnval /* cntnval, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_PWM_CNT45VAL;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define PWM_REG_BASE_ADDR						'h5001C000

`define PWM_PWMCFG_REG_OFFSET					0x00000000
`define PWM_PWMINVERTTRIG_REG_OFFSET					0x00000004
`define PWM_PWM01TRIG_REG_OFFSET					0x00000008
`define PWM_PWM23TRIG_REG_OFFSET					0x0000000c
`define PWM_PWM45TRIG_REG_OFFSET					0x00000010
`define PWM_PWMINTEN1_REG_OFFSET					0x00000014
`define PWM_PWMINTEN2_REG_OFFSET					0x00000018
`define PWM_PWMRIS1_REG_OFFSET					0x0000001c
`define PWM_PWMRIS2_REG_OFFSET					0x00000020
`define PWM_PWMIC1_REG_OFFSET					0x00000024
`define PWM_PWMIC2_REG_OFFSET					0x00000028
`define PWM_PWMIS1_REG_OFFSET					0x0000002c
`define PWM_PWMIS2_REG_OFFSET					0x00000030
`define PWM_PWMCTL_REG_OFFSET					0x00000034
`define PWM_PWM01LOAD_REG_OFFSET					0x00000038
`define PWM_PWM23LOAD_REG_OFFSET					0x0000003c
`define PWM_PWM45LOAD_REG_OFFSET					0x00000040
`define PWM_PWM01COUNT_REG_OFFSET					0x00000044
`define PWM_PWM23COUNT_REG_OFFSET					0x00000048
`define PWM_PWM45COUNT_REG_OFFSET					0x0000004c
`define PWM_PWM0CMP_REG_OFFSET					0x00000050
`define PWM_PWM1CMP_REG_OFFSET					0x00000054
`define PWM_PWM2CMP_REG_OFFSET					0x00000058
`define PWM_PWM3CMP_REG_OFFSET					0x0000005c
`define PWM_PWM4CMP_REG_OFFSET					0x00000060
`define PWM_PWM5CMP_REG_OFFSET					0x00000064
`define PWM_PWM01DB_REG_OFFSET					0x00000068
`define PWM_PWM23DB_REG_OFFSET					0x0000006c
`define PWM_PWM45DB_REG_OFFSET					0x00000070
`define PWM_CAPCTL_REG_OFFSET					0x00000074
`define PWM_CAPINTEN_REG_OFFSET					0x00000078
`define PWM_CAPRIS_REG_OFFSET					0x0000007c
`define PWM_CAPIC_REG_OFFSET					0x00000080
`define PWM_CAPIS_REG_OFFSET					0x00000084
`define PWM_CAP01T_REG_OFFSET					0x00000088
`define PWM_CAP23T_REG_OFFSET					0x0000008c
`define PWM_CAP45T_REG_OFFSET					0x00000090
`define PWM_CAP01MATCH_REG_OFFSET					0x00000094
`define PWM_CAP23MATCH_REG_OFFSET					0x00000098
`define PWM_CAP45MATCH_REG_OFFSET					0x0000009c
`define PWM_TIMINTEN_REG_OFFSET					0x000000a0
`define PWM_TIMRIS_REG_OFFSET					0x000000a4
`define PWM_TIMINTCLR_REG_OFFSET					0x000000a8
`define PWM_TIMIS_REG_OFFSET					0x000000ac
`define PWM_TIM01LOAD_REG_OFFSET					0x000000b0
`define PWM_TIM23LOAD_REG_OFFSET					0x000000b4
`define PWM_TIM45LOAD_REG_OFFSET					0x000000b8
`define PWM_TIM01COUNT_REG_OFFSET					0x000000bc
`define PWM_TIM23COUNT_REG_OFFSET					0x000000c0
`define PWM_TIM45COUNT_REG_OFFSET					0x000000c4
`define PWM_CNT01VAL_REG_OFFSET					0x000000c8
`define PWM_CNT23VAL_REG_OFFSET					0x000000cc
`define PWM_CNT45VAL_REG_OFFSET					0x000000d0

`define PWM_PWMCFG_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMCFG_REG_OFFSET)
`define PWM_PWMINVERTTRIG_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMINVERTTRIG_REG_OFFSET)
`define PWM_PWM01TRIG_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM01TRIG_REG_OFFSET)
`define PWM_PWM23TRIG_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM23TRIG_REG_OFFSET)
`define PWM_PWM45TRIG_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM45TRIG_REG_OFFSET)
`define PWM_PWMINTEN1_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMINTEN1_REG_OFFSET)
`define PWM_PWMINTEN2_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMINTEN2_REG_OFFSET)
`define PWM_PWMRIS1_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMRIS1_REG_OFFSET)
`define PWM_PWMRIS2_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMRIS2_REG_OFFSET)
`define PWM_PWMIC1_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMIC1_REG_OFFSET)
`define PWM_PWMIC2_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMIC2_REG_OFFSET)
`define PWM_PWMIS1_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMIS1_REG_OFFSET)
`define PWM_PWMIS2_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMIS2_REG_OFFSET)
`define PWM_PWMCTL_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWMCTL_REG_OFFSET)
`define PWM_PWM01LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM01LOAD_REG_OFFSET)
`define PWM_PWM23LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM23LOAD_REG_OFFSET)
`define PWM_PWM45LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM45LOAD_REG_OFFSET)
`define PWM_PWM01COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM01COUNT_REG_OFFSET)
`define PWM_PWM23COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM23COUNT_REG_OFFSET)
`define PWM_PWM45COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM45COUNT_REG_OFFSET)
`define PWM_PWM0CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM0CMP_REG_OFFSET)
`define PWM_PWM1CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM1CMP_REG_OFFSET)
`define PWM_PWM2CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM2CMP_REG_OFFSET)
`define PWM_PWM3CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM3CMP_REG_OFFSET)
`define PWM_PWM4CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM4CMP_REG_OFFSET)
`define PWM_PWM5CMP_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM5CMP_REG_OFFSET)
`define PWM_PWM01DB_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM01DB_REG_OFFSET)
`define PWM_PWM23DB_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM23DB_REG_OFFSET)
`define PWM_PWM45DB_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_PWM45DB_REG_OFFSET)
`define PWM_CAPCTL_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAPCTL_REG_OFFSET)
`define PWM_CAPINTEN_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAPINTEN_REG_OFFSET)
`define PWM_CAPRIS_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAPRIS_REG_OFFSET)
`define PWM_CAPIC_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAPIC_REG_OFFSET)
`define PWM_CAPIS_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAPIS_REG_OFFSET)
`define PWM_CAP01T_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP01T_REG_OFFSET)
`define PWM_CAP23T_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP23T_REG_OFFSET)
`define PWM_CAP45T_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP45T_REG_OFFSET)
`define PWM_CAP01MATCH_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP01MATCH_REG_OFFSET)
`define PWM_CAP23MATCH_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP23MATCH_REG_OFFSET)
`define PWM_CAP45MATCH_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CAP45MATCH_REG_OFFSET)
`define PWM_TIMINTEN_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIMINTEN_REG_OFFSET)
`define PWM_TIMRIS_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIMRIS_REG_OFFSET)
`define PWM_TIMINTCLR_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIMINTCLR_REG_OFFSET)
`define PWM_TIMIS_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIMIS_REG_OFFSET)
`define PWM_TIM01LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM01LOAD_REG_OFFSET)
`define PWM_TIM23LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM23LOAD_REG_OFFSET)
`define PWM_TIM45LOAD_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM45LOAD_REG_OFFSET)
`define PWM_TIM01COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM01COUNT_REG_OFFSET)
`define PWM_TIM23COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM23COUNT_REG_OFFSET)
`define PWM_TIM45COUNT_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_TIM45COUNT_REG_OFFSET)
`define PWM_CNT01VAL_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CNT01VAL_REG_OFFSET)
`define PWM_CNT23VAL_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CNT23VAL_REG_OFFSET)
`define PWM_CNT45VAL_REG_ADDR					(`PWM_REG_BASE_ADDR + `PWM_CNT45VAL_REG_OFFSET)


#endif //__PWM_REG_DEF_SVH__
