#ifndef __RTC_REG_DEF_H__
#define __RTC_REG_DEF_H__

/*
 * ============================================================================
 * RTC Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x60004000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* RTCCURRENTVALUE (0x00000000) - RTC_current_value */
typedef union
{
	struct
	{
		unsigned int current_counter_value /* current_counter_value, R, 32-bit 内部 counter 当前值，读取保持一致。Reset: `0x0` */ : 32;
	}bits;
	unsigned int u32;
} U_RTC_RTCCURRENTVALUE;

/* RTCMATCHVALUE (0x00000004) - RTC_match_value */
typedef union
{
	struct
	{
		unsigned int counter_match /* counter_match, R/W, 匹配值寄存器；当 counter 与之匹配时产生中断（需 `rtc_ien=1` 且 `rtc_mask=0`）。仅当  */ : 32;
	}bits;
	unsigned int u32;
} U_RTC_RTCMATCHVALUE;

/* RTCLOADVALUE (0x00000008) - RTC_load_value */
typedef union
{
	struct
	{
		unsigned int counter_load /* counter_load, R/W, 加载到 counter 的初值（coherently written）。Reset: `0x0` */ : 32;
	}bits;
	unsigned int u32;
} U_RTC_RTCLOADVALUE;

/* RTCCCR (0x0000000c) - RTC_CCR */
typedef union
{
	struct
	{
		unsigned int rtc_ien /* rtc_ien, R/W, interrupt enable：`0` = disabled; `1` = enabled. Reset: `0x0` */ : 1;
		unsigned int rtc_mask /* rtc_mask, R/W, interrupt mask：`0` = unmasked; `1` = masked. Reset: `0x0` */ : 1;
		unsigned int rtc_en /* rtc_en, R/W, counter 使能：`0` = disabled; `1` = enabled. Reset: `0x0` */ : 1;
		unsigned int rtc_wen /* rtc_wen, R/W, Wrap 控制：`0` = 匹配时不立即 wrap（继续到 max）；`1` = 匹配时立即 wrap 回 `RTC_l */ : 1;
		unsigned int /* rsvd_31_4 */ /* —, Reserved, read as 0 */ : 28;
	}bits;
	unsigned int u32;
} U_RTC_RTCCCR;

/* RTCINTSTATUS (0x00000010) - RTC_int_status */
typedef union
{
	struct
	{
		unsigned int rtc_stat /* rtc_stat, R, Masked 后中断状态：`0` = inactive; `1` = active. Reset: `0x0` */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as 0 */ : 31;
	}bits;
	unsigned int u32;
} U_RTC_RTCINTSTATUS;

/* RTCRAWINTSTATUS (0x00000014) - RTC_raw_int_status */
typedef union
{
	struct
	{
		unsigned int rtc_rstat /* rtc_rstat, R, 原始中断状态（未 mask）：`0` = inactive; `1` = active. Reset: `0x0` */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as 0 */ : 31;
	}bits;
	unsigned int u32;
} U_RTC_RTCRAWINTSTATUS;

/* RTCINTCLR (0x00000018) - RTC_int_clr */
typedef union
{
	struct
	{
		unsigned int rtc_int_clr /* rtc_int_clr, R, 读此寄存器清除匹配中断；读完成时（end of read）清除中断。Reset: `0x0` */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as 0 */ : 31;
	}bits;
	unsigned int u32;
} U_RTC_RTCINTCLR;

/* RTCCOMPVERSION (0x0000001c) - RTC_COMP_VERSION */
typedef union
{
	struct
	{
		unsigned int component_version /* component_version, R, 组件版本号（只读）。Reset: `0x0` */ : 32;
	}bits;
	unsigned int u32;
} U_RTC_RTCCOMPVERSION;

/* RTCDIV (0x00000020) - RTC_DIV */
typedef union
{
	struct
	{
		unsigned int rtc_div /* rtc_div, R/W, RTC 时钟分频值（基于此寄存器的分频）。Reset: `0x4000` (=16384) */ : 20;
		unsigned int /* rsvd_31_20 */ /* —, Reserved, read as 0 */ : 12;
	}bits;
	unsigned int u32;
} U_RTC_RTCDIV;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define RTC_REG_BASE_ADDR						0x60004000

#define RTC_RTCCURRENTVALUE_REG_OFFSET					0x00000000
#define RTC_RTCMATCHVALUE_REG_OFFSET					0x00000004
#define RTC_RTCLOADVALUE_REG_OFFSET					0x00000008
#define RTC_RTCCCR_REG_OFFSET					0x0000000c
#define RTC_RTCINTSTATUS_REG_OFFSET					0x00000010
#define RTC_RTCRAWINTSTATUS_REG_OFFSET					0x00000014
#define RTC_RTCINTCLR_REG_OFFSET					0x00000018
#define RTC_RTCCOMPVERSION_REG_OFFSET					0x0000001c
#define RTC_RTCDIV_REG_OFFSET					0x00000020

#define RTC_RTCCURRENTVALUE_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCCURRENTVALUE_REG_OFFSET)
#define RTC_RTCMATCHVALUE_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCMATCHVALUE_REG_OFFSET)
#define RTC_RTCLOADVALUE_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCLOADVALUE_REG_OFFSET)
#define RTC_RTCCCR_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCCCR_REG_OFFSET)
#define RTC_RTCINTSTATUS_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCINTSTATUS_REG_OFFSET)
#define RTC_RTCRAWINTSTATUS_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCRAWINTSTATUS_REG_OFFSET)
#define RTC_RTCINTCLR_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCINTCLR_REG_OFFSET)
#define RTC_RTCCOMPVERSION_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCCOMPVERSION_REG_OFFSET)
#define RTC_RTCDIV_REG_ADDR						(RTC_REG_BASE_ADDR + RTC_RTCDIV_REG_OFFSET)

#endif //__RTC_REG_DEF_H__
