/* RTC Register Definition (SystemVerilog Header) */
#ifndef __RTC_REG_DEF_SVH__
#define __RTC_REG_DEF_SVH__

/*
 * ============================================================================
 * RTC Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x60004000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* RTCCURRENTVALUE (0x00000000) - RTC_current_value */
typedef union {
    struct packed {
        bit[31:0]        current_counter_value /* current_counter_value, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_RTC_RTCCURRENTVALUE;

/* RTCMATCHVALUE (0x00000004) - RTC_match_value */
typedef union {
    struct packed {
        bit[31:0]        counter_match /* counter_match, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_RTC_RTCMATCHVALUE;

/* RTCLOADVALUE (0x00000008) - RTC_load_value */
typedef union {
    struct packed {
        bit[31:0]        counter_load /* counter_load, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_RTC_RTCLOADVALUE;

/* RTCCCR (0x0000000c) - RTC_CCR */
typedef union {
    struct packed {
        const bit[27:0]   /* rsvd_31_4 */ /* — */;
        bit                 rtc_wen /* rtc_wen, R/W */;
        bit                 rtc_en /* rtc_en, R/W */;
        bit                 rtc_mask /* rtc_mask, R/W */;
        bit                 rtc_ien /* rtc_ien, R/W */;
    }bits;
    int unsigned u32 = {28'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_RTC_RTCCCR;

/* RTCINTSTATUS (0x00000010) - RTC_int_status */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 rtc_stat /* rtc_stat, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_RTC_RTCINTSTATUS;

/* RTCRAWINTSTATUS (0x00000014) - RTC_raw_int_status */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 rtc_rstat /* rtc_rstat, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_RTC_RTCRAWINTSTATUS;

/* RTCINTCLR (0x00000018) - RTC_int_clr */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 rtc_int_clr /* rtc_int_clr, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_RTC_RTCINTCLR;

/* RTCCOMPVERSION (0x0000001c) - RTC_COMP_VERSION */
typedef union {
    struct packed {
        bit[31:0]        component_version /* component_version, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_RTC_RTCCOMPVERSION;

/* RTCDIV (0x00000020) - RTC_DIV */
typedef union {
    struct packed {
        const bit[11:0]   /* rsvd_31_20 */ /* — */;
        bit[19:0]        rtc_div /* rtc_div, R/W */;
    }bits;
    int unsigned u32 = {12'h0, 20'h0};
} U_RTC_RTCDIV;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define RTC_REG_BASE_ADDR						'h60004000

`define RTC_RTCCURRENTVALUE_REG_OFFSET					0x00000000
`define RTC_RTCMATCHVALUE_REG_OFFSET					0x00000004
`define RTC_RTCLOADVALUE_REG_OFFSET					0x00000008
`define RTC_RTCCCR_REG_OFFSET					0x0000000c
`define RTC_RTCINTSTATUS_REG_OFFSET					0x00000010
`define RTC_RTCRAWINTSTATUS_REG_OFFSET					0x00000014
`define RTC_RTCINTCLR_REG_OFFSET					0x00000018
`define RTC_RTCCOMPVERSION_REG_OFFSET					0x0000001c
`define RTC_RTCDIV_REG_OFFSET					0x00000020

`define RTC_RTCCURRENTVALUE_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCCURRENTVALUE_REG_OFFSET)
`define RTC_RTCMATCHVALUE_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCMATCHVALUE_REG_OFFSET)
`define RTC_RTCLOADVALUE_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCLOADVALUE_REG_OFFSET)
`define RTC_RTCCCR_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCCCR_REG_OFFSET)
`define RTC_RTCINTSTATUS_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCINTSTATUS_REG_OFFSET)
`define RTC_RTCRAWINTSTATUS_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCRAWINTSTATUS_REG_OFFSET)
`define RTC_RTCINTCLR_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCINTCLR_REG_OFFSET)
`define RTC_RTCCOMPVERSION_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCCOMPVERSION_REG_OFFSET)
`define RTC_RTCDIV_REG_ADDR					(`RTC_REG_BASE_ADDR + `RTC_RTCDIV_REG_OFFSET)


#endif //__RTC_REG_DEF_SVH__
