/* TIM Register Definition (SystemVerilog Header) */
#ifndef __TIM_REG_DEF_SVH__
#define __TIM_REG_DEF_SVH__

/*
 * ============================================================================
 * TIM Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x50000000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* TIMER1LOADCOUNT (0x00000000) - Timer1 Load Count */
typedef union {
    struct packed {
        bit[31:0]        timer1_load_count_register /* timer1_load_count_register, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_TIM_TIMER1LOADCOUNT;

/* TIMER1CURRENTVALUE (0x00000004) - Timer1 Current Value */
typedef union {
    struct packed {
        bit[31:0]        timer1_current_value_register /* timer1_current_value_register, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_TIM_TIMER1CURRENTVALUE;

/* TIMER1CONTROLREG (0x00000008) - Timer1 Control Reg */
typedef union {
    struct packed {
        const bit[26:0]   /* rsvd_31_5 */ /* — */;
        bit                 timer_hardware_trigger_enable /* timer_hardware_trigger_enable, R/W */;
        const bit            /* rsvd_3_3 */ /* — */;
        bit                 timer_interrupt_mask /* timer_interrupt_mask, R/W */;
        bit                 timer_mode_select /* timer_mode_select, R/W */;
        bit                 timer_enable_select /* timer_enable_select, R/W */;
    }bits;
    int unsigned u32 = {27'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_TIM_TIMER1CONTROLREG;

/* TIMER1_INT_CLR (0x0000000c) - Timer1_int_clr */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 timer1_int_clr_register /* timer1_int_clr_register, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_TIM_TIMER1_INT_CLR;

/* TIMER1INTSTATUS (0x00000010) - Timer1Int Status */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 timer1int_status_register /* timer1int_status_register, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_TIM_TIMER1INTSTATUS;

/* TIMER2LOADCOUNT (0x00000014) -  */
typedef union {
    struct packed {
        bit[31:0]        timer2_load_count_register /* timer2_load_count_register, R/W */;
    }bits;
    int unsigned u32 = {32'h0};
} U_TIM_TIMER2LOADCOUNT;

/* TIMER2CURRENTVALUE (0x00000018) -  */
typedef union {
    struct packed {
        bit[31:0]        timer2_current_value_register /* timer2_current_value_register, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_TIM_TIMER2CURRENTVALUE;

/* TIMER2CONTROLREG (0x0000001c) -  */
typedef union {
    struct packed {
        const bit[26:0]   /* rsvd_31_5 */ /* — */;
        bit                 timer_hardware_trigger_enable /* timer_hardware_trigger_enable, R/W */;
        const bit            /* rsvd_3_3 */ /* — */;
        bit                 timer_interrupt_mask /* timer_interrupt_mask, R/W */;
        bit                 timer_mode_select /* timer_mode_select, R/W */;
        bit                 timer_enable_select /* timer_enable_select, R/W */;
    }bits;
    int unsigned u32 = {27'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_TIM_TIMER2CONTROLREG;

/* TIMER2_INT_CLR (0x00000020) -  */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 timer2_int_clr_register /* timer2_int_clr_register, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_TIM_TIMER2_INT_CLR;

/* TIMER2INTSTATUS (0x00000024) -  */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 timer2int_status_register /* timer2int_status_register, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_TIM_TIMER2INTSTATUS;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define TIM_REG_BASE_ADDR						'h50000000

`define TIM_TIMER1LOADCOUNT_REG_OFFSET					0x00000000
`define TIM_TIMER1CURRENTVALUE_REG_OFFSET					0x00000004
`define TIM_TIMER1CONTROLREG_REG_OFFSET					0x00000008
`define TIM_TIMER1_INT_CLR_REG_OFFSET					0x0000000c
`define TIM_TIMER1INTSTATUS_REG_OFFSET					0x00000010
`define TIM_TIMER2LOADCOUNT_REG_OFFSET					0x00000014
`define TIM_TIMER2CURRENTVALUE_REG_OFFSET					0x00000018
`define TIM_TIMER2CONTROLREG_REG_OFFSET					0x0000001c
`define TIM_TIMER2_INT_CLR_REG_OFFSET					0x00000020
`define TIM_TIMER2INTSTATUS_REG_OFFSET					0x00000024

`define TIM_TIMER1LOADCOUNT_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER1LOADCOUNT_REG_OFFSET)
`define TIM_TIMER1CURRENTVALUE_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER1CURRENTVALUE_REG_OFFSET)
`define TIM_TIMER1CONTROLREG_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER1CONTROLREG_REG_OFFSET)
`define TIM_TIMER1_INT_CLR_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER1_INT_CLR_REG_OFFSET)
`define TIM_TIMER1INTSTATUS_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER1INTSTATUS_REG_OFFSET)
`define TIM_TIMER2LOADCOUNT_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER2LOADCOUNT_REG_OFFSET)
`define TIM_TIMER2CURRENTVALUE_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER2CURRENTVALUE_REG_OFFSET)
`define TIM_TIMER2CONTROLREG_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER2CONTROLREG_REG_OFFSET)
`define TIM_TIMER2_INT_CLR_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER2_INT_CLR_REG_OFFSET)
`define TIM_TIMER2INTSTATUS_REG_ADDR					(`TIM_REG_BASE_ADDR + `TIM_TIMER2INTSTATUS_REG_OFFSET)


#endif //__TIM_REG_DEF_SVH__
