#ifndef __TIM_REG_DEF_H__
#define __TIM_REG_DEF_H__

/*
 * ============================================================================
 * TIM Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x50000000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* TIMER1LOADCOUNT (0x00000000) - Timer1 Load Count */
typedef union
{
	struct
	{
		unsigned int timer1_load_count_register /* timer1_load_count_register, R/W, Value to be loaded into Timer1. This is the value from which */ : 32;
	}bits;
	unsigned int u32;
} U_TIM_TIMER1LOADCOUNT;

/* TIMER1CURRENTVALUE (0x00000004) - Timer1 Current Value */
typedef union
{
	struct
	{
		unsigned int timer1_current_value_register /* timer1_current_value_register, R, Current Value of Timer1. Reset Value: `32'b0` */ : 32;
	}bits;
	unsigned int u32;
} U_TIM_TIMER1CURRENTVALUE;

/* TIMER1CONTROLREG (0x00000008) - Timer1 Control Reg */
typedef union
{
	struct
	{
		unsigned int timer_enable_select /* timer_enable_select, R/W, `0` = disabled; `1` = enabled. Reset Value: `1'b0` */ : 1;
		unsigned int timer_mode_select /* timer_mode_select, R/W, `0` = free-running; `1` = user-defined running. Reset Value: */ : 1;
		unsigned int timer_interrupt_mask /* timer_interrupt_mask, R/W, `0` = timer interrupt not masked; `1` = timer interrupt mask */ : 1;
		unsigned int /* rsvd_3_3 */ /* —, Reserved, read as zero */ : 1;
		unsigned int timer_hardware_trigger_enable /* timer_hardware_trigger_enable, R/W, `0` = timer hardware trigger disable; `1` = timer hardware t */ : 1;
		unsigned int /* rsvd_31_5 */ /* —, Reserved, read as zero */ : 27;
	}bits;
	unsigned int u32;
} U_TIM_TIMER1CONTROLREG;

/* TIMER1_INT_CLR (0x0000000c) - Timer1_int_clr */
typedef union
{
	struct
	{
		unsigned int timer1_int_clr_register /* timer1_int_clr_register, R, Reading from this register returns all zeros (`0`) and clear */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_TIM_TIMER1_INT_CLR;

/* TIMER1INTSTATUS (0x00000010) - Timer1Int Status */
typedef union
{
	struct
	{
		unsigned int timer1int_status_register /* timer1int_status_register, R, Contains the interrupt status for Timer1 */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_TIM_TIMER1INTSTATUS;

/* TIMER2LOADCOUNT (0x00000014) -  */
typedef union
{
	struct
	{
		unsigned int timer2_load_count_register /* timer2_load_count_register, R/W, Value to be loaded into Timer2. This is the value from which */ : 32;
	}bits;
	unsigned int u32;
} U_TIM_TIMER2LOADCOUNT;

/* TIMER2CURRENTVALUE (0x00000018) -  */
typedef union
{
	struct
	{
		unsigned int timer2_current_value_register /* timer2_current_value_register, R, Current Value of Timer2. Reset Value: `32'b0` */ : 32;
	}bits;
	unsigned int u32;
} U_TIM_TIMER2CURRENTVALUE;

/* TIMER2CONTROLREG (0x0000001c) -  */
typedef union
{
	struct
	{
		unsigned int timer_enable_select /* timer_enable_select, R/W, `0` = disabled; `1` = enabled. Reset Value: `1'b0` */ : 1;
		unsigned int timer_mode_select /* timer_mode_select, R/W, `0` = free-running; `1` = user-defined running. Reset Value: */ : 1;
		unsigned int timer_interrupt_mask /* timer_interrupt_mask, R/W, `0` = timer interrupt not masked; `1` = timer interrupt mask */ : 1;
		unsigned int /* rsvd_3_3 */ /* —, Reserved, read as zero */ : 1;
		unsigned int timer_hardware_trigger_enable /* timer_hardware_trigger_enable, R/W, `0` = timer hardware trigger disable; `1` = timer hardware t */ : 1;
		unsigned int /* rsvd_31_5 */ /* —, Reserved, read as zero */ : 27;
	}bits;
	unsigned int u32;
} U_TIM_TIMER2CONTROLREG;

/* TIMER2_INT_CLR (0x00000020) -  */
typedef union
{
	struct
	{
		unsigned int timer2_int_clr_register /* timer2_int_clr_register, R, Reading from this register returns all zeros (`0`) and clear */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_TIM_TIMER2_INT_CLR;

/* TIMER2INTSTATUS (0x00000024) -  */
typedef union
{
	struct
	{
		unsigned int timer2int_status_register /* timer2int_status_register, R, Contains the interrupt status for Timer2 */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_TIM_TIMER2INTSTATUS;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define TIM_REG_BASE_ADDR						0x50000000

#define TIM_TIMER1LOADCOUNT_REG_OFFSET					0x00000000
#define TIM_TIMER1CURRENTVALUE_REG_OFFSET					0x00000004
#define TIM_TIMER1CONTROLREG_REG_OFFSET					0x00000008
#define TIM_TIMER1_INT_CLR_REG_OFFSET					0x0000000c
#define TIM_TIMER1INTSTATUS_REG_OFFSET					0x00000010
#define TIM_TIMER2LOADCOUNT_REG_OFFSET					0x00000014
#define TIM_TIMER2CURRENTVALUE_REG_OFFSET					0x00000018
#define TIM_TIMER2CONTROLREG_REG_OFFSET					0x0000001c
#define TIM_TIMER2_INT_CLR_REG_OFFSET					0x00000020
#define TIM_TIMER2INTSTATUS_REG_OFFSET					0x00000024

#define TIM_TIMER1LOADCOUNT_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER1LOADCOUNT_REG_OFFSET)
#define TIM_TIMER1CURRENTVALUE_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER1CURRENTVALUE_REG_OFFSET)
#define TIM_TIMER1CONTROLREG_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER1CONTROLREG_REG_OFFSET)
#define TIM_TIMER1_INT_CLR_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER1_INT_CLR_REG_OFFSET)
#define TIM_TIMER1INTSTATUS_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER1INTSTATUS_REG_OFFSET)
#define TIM_TIMER2LOADCOUNT_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER2LOADCOUNT_REG_OFFSET)
#define TIM_TIMER2CURRENTVALUE_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER2CURRENTVALUE_REG_OFFSET)
#define TIM_TIMER2CONTROLREG_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER2CONTROLREG_REG_OFFSET)
#define TIM_TIMER2_INT_CLR_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER2_INT_CLR_REG_OFFSET)
#define TIM_TIMER2INTSTATUS_REG_ADDR						(TIM_REG_BASE_ADDR + TIM_TIMER2INTSTATUS_REG_OFFSET)

#endif //__TIM_REG_DEF_H__
