#ifndef __USI_REG_DEF_H__
#define __USI_REG_DEF_H__

/*
 * ============================================================================
 * USI Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x50028000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* USICTRL (0x00000000) - USI_CTRL */
typedef union
{
	struct
	{
		unsigned int usi_en /* usi_en, R/W, All modules in USI enable */ : 1;
		unsigned int fm_en /* fm_en, R/W, Function modules (UART/I2C/SPI) enable */ : 1;
		unsigned int tx_fifo_en /* tx_fifo_en, R/W, TX FIFO enable */ : 1;
		unsigned int rx_fifo_en /* rx_fifo_en, R/W, RX FIFO enable (`0` = disable; `1` = enable) */ : 1;
		unsigned int /* rsvd_31_4 */ /* R, — */ : 28;
	}bits;
	unsigned int u32;
} U_USI_USICTRL;

/* MODESEL (0x00000004) - MODE_SEL */
typedef union
{
	struct
	{
		unsigned int mode_sel /* mode_sel, R/W, `00` = UART; `01` = I2C; `10` = SPI; `11` = mode keep the la */ : 2;
		unsigned int /* rsvd_31_2 */ /* R, — */ : 30;
	}bits;
	unsigned int u32;
} U_USI_MODESEL;

/* RXFIFO (0x00000008) - TX_FIFO */
typedef union
{
	struct
	{
		unsigned int rx_data /* rx_data, R, Received data */ : 16;
		unsigned int /* rsvd_31_16 */ /* R, — */ : 16;
	}bits;
	unsigned int u32;
} U_USI_RXFIFO;

/* TXFIFO (0x00000008) - TX_FIFO */
typedef union
{
	struct
	{
		unsigned int tx_data /* tx_data, W, Transmitting data */ : 16;
		unsigned int /* rsvd_31_16 */ /* R, — */ : 16;
	}bits;
	unsigned int u32;
} U_USI_TXFIFO;

/* FIFOSTA (0x0000000c) - FIFO_STA */
typedef union
{
	struct
	{
		unsigned int tx_empty /* tx_empty, R, TX FIFO 空 */ : 1;
		unsigned int tx_full /* tx_full, R, TX FIFO 满 */ : 1;
		unsigned int rx_empty /* rx_empty, R, RX FIFO 空 */ : 1;
		unsigned int rx_full /* rx_full, R, RX FIFO 满 */ : 1;
		unsigned int /* rsvd_7_4 */ /* R, — */ : 4;
		unsigned int tx_num /* tx_num, R, 数据字计数（TX FIFO 当前存储数量） */ : 4;
		unsigned int /* rsvd_15_12 */ /* R, — */ : 4;
		unsigned int rx_num /* rx_num, R, 数据字计数（RX FIFO 当前存储数量） */ : 4;
		unsigned int /* rsvd_31_20 */ /* R, — */ : 12;
	}bits;
	unsigned int u32;
} U_USI_FIFOSTA;

/* CLKDIV0 (0x00000010) - CLK_DIV0 */
typedef union
{
	struct
	{
		unsigned int clk_div0 /* clk_div0, R/W, 分频寄存器。<br>UART 模式：Baud rate = `Fpclk / (16 × (CLK_DIV0 + 1)) */ : 24;
		unsigned int /* rsvd_31_24 */ /* R, — */ : 8;
	}bits;
	unsigned int u32;
} U_USI_CLKDIV0;

/* CLKDIV1 (0x00000014) - CLK_DIV1 */
typedef union
{
	struct
	{
		unsigned int clk_div1 /* clk_div1, R/W, I2C SCL 低电平计数值；UART/SPI 不使用 */ : 24;
		unsigned int /* rsvd_31_24 */ /* R, — */ : 8;
	}bits;
	unsigned int u32;
} U_USI_CLKDIV1;

/* UARTCTRL (0x00000018) - UART_CTRL */
typedef union
{
	struct
	{
		unsigned int dbit /* dbit, R/W, 数据位：`00` = 5; `01` = 6; `10` = 7; `11` = 8 */ : 2;
		unsigned int pbit /* pbit, R/W, 停止位数：`00` = 1 stop; `01` = 1.5 stop; `10` = 2 stop; `11` = k */ : 2;
		unsigned int pen /* pen, R/W, Parity enable */ : 1;
		unsigned int eps /* eps, R/W, Even parity select（`0` = odd；`1` = even）；`PEN=1` 时有效 */ : 1;
		unsigned int /* rsvd_31_6 */ /* R, — */ : 26;
	}bits;
	unsigned int u32;
} U_USI_UARTCTRL;

/* UARTSTA (0x0000001c) - UART_STA */
typedef union
{
	struct
	{
		unsigned int txd_work /* txd_work, R, UART TXD 正在发送 */ : 1;
		unsigned int rxd_work /* rxd_work, R, UART RXD 正在接收 */ : 1;
		unsigned int /* rsvd_31_2 */ /* R, — */ : 30;
	}bits;
	unsigned int u32;
} U_USI_UARTSTA;

/* I2CMODE (0x00000020) - I2C_MODE */
typedef union
{
	struct
	{
		unsigned int ms_mode /* ms_mode, R/W, `0` = I2CS 模式；`1` = I2CM 模式 */ : 1;
		unsigned int /* rsvd_31_1 */ /* R, — */ : 31;
	}bits;
	unsigned int u32;
} U_USI_I2CMODE;

/* I2CADDR (0x00000024) - I2C_ADDR */
typedef union
{
	struct
	{
		unsigned int i2c_addr /* i2c_addr, R/W, 10-bit I2C slave 地址 */ : 10;
		unsigned int /* rsvd_31_10 */ /* R, — */ : 22;
	}bits;
	unsigned int u32;
} U_USI_I2CADDR;

/* I2CMCTRL (0x00000028) - I2CM_CTRL */
typedef union
{
	struct
	{
		unsigned int addr_mode /* addr_mode, R/W, `0` = 7-bit 地址；`1` = 10-bit 地址 */ : 1;
		unsigned int stop /* stop, R/W, TX FIFO 空时：`0` = I2CM 保持 SCL 低；`1` = I2CM 产生 STOP */ : 1;
		unsigned int hs_mode /* hs_mode, R/W, 高速模式 */ : 1;
		unsigned int sbyte /* sbyte, R/W, `1` = generate START byte */ : 1;
		unsigned int gcall /* gcall, R/W, 首字节是否为 general call 地址；用 general call 须先清 `ADDR_MODE` */ : 1;
		unsigned int /* rsvd_31_5 */ /* R, — */ : 27;
	}bits;
	unsigned int u32;
} U_USI_I2CMCTRL;

/* I2CMCODE (0x0000002c) - I2CM_CODE */
typedef union
{
	struct
	{
		unsigned int mcode /* mcode, R/W, I2CM 高速模式 master code */ : 3;
		unsigned int /* rsvd_31_3 */ /* R, — */ : 29;
	}bits;
	unsigned int u32;
} U_USI_I2CMCODE;

/* I2CSCTRL (0x00000030) - I2CS_CTRL */
typedef union
{
	struct
	{
		unsigned int gcall_mode /* gcall_mode, R/W, `0` = 接收 general call 数据；`1` = 不接收 general call 数据 */ : 1;
		unsigned int /* rsvd_31_1 */ /* R, — */ : 31;
	}bits;
	unsigned int u32;
} U_USI_I2CSCTRL;

/* I2CFMDIV (0x00000034) - I2C_FM_DIV */
typedef union
{
	struct
	{
		unsigned int i2c_fm_div /* i2c_fm_div, R/W, I2C fast mode 分频（用于 master code + START byte 传输） */ : 8;
		unsigned int /* rsvd_31_8 */ /* R, — */ : 24;
	}bits;
	unsigned int u32;
} U_USI_I2CFMDIV;

/* I2CHOLD (0x00000038) - I2C_HOLD */
typedef union
{
	struct
	{
		unsigned int i2c_hold /* i2c_hold, R/W, SDA hold time（master/slave 通用）：`T_I2C_HOLD = (I2C_HOLD + 1)  */ : 8;
		unsigned int /* rsvd_31_8 */ /* R, — */ : 24;
	}bits;
	unsigned int u32;
} U_USI_I2CHOLD;

/* I2CSTA (0x0000003c) - I2C_STA */
typedef union
{
	struct
	{
		unsigned int i2cm_work /* i2cm_work, R, I2CM 忙 */ : 1;
		unsigned int i2cm_data /* i2cm_data, R, I2CM 正在传输数据 */ : 1;
		unsigned int /* rsvd_7_2 */ /* R, — */ : 6;
		unsigned int i2cs_work /* i2cs_work, R, I2C slave 忙 */ : 1;
		unsigned int /* rsvd_31_9 */ /* R, — */ : 23;
	}bits;
	unsigned int u32;
} U_USI_I2CSTA;

/* SPIMODE (0x00000040) - SPI_MODE */
typedef union
{
	struct
	{
		unsigned int ms_mode /* ms_mode, R/W, `0` = SPI slave；`1` = SPI master */ : 1;
		unsigned int /* rsvd_31_1 */ /* R, — */ : 31;
	}bits;
	unsigned int u32;
} U_USI_SPIMODE;

/* SPICTRL (0x00000044) - SPI_CTRL */
typedef union
{
	struct
	{
		unsigned int data_size /* data_size, R/W, 数据帧大小（见下表） */ : 4;
		unsigned int tmod /* tmod, R/W, Transfer mode：`00` = TR & RX；`01` = TX only；`10` = RX only；` */ : 2;
		unsigned int cpha /* cpha, R/W, Clock phase：`0` = 第一 bit 中部 toggle；`1` = 第一 bit 起始 toggle */ : 1;
		unsigned int cpol /* cpol, R/W, Clock polarity：`0` = 空闲 SCK 低；`1` = 空闲 SCK 高 */ : 1;
		unsigned int nss_toggle /* nss_toggle, R/W, `0` = 每个数据帧末尾 toggle；`1` = NSS 一直保持直至 SPI master 停止 */ : 1;
		unsigned int nss_ctrl /* nss_ctrl, R/W, NSS 输出控制选择：`0` = NSS_TOGGLE 控制；`1` = NSS_DATA 控制 */ : 1;
		unsigned int /* rsvd_31_10 */ /* R, — */ : 22;
	}bits;
	unsigned int u32;
} U_USI_SPICTRL;

/* SPISTA (0x00000048) - SPI_STA */
typedef union
{
	struct
	{
		unsigned int spi_working /* spi_working, R, SPI master/slave 工作状态 */ : 1;
		unsigned int /* rsvd_31_1 */ /* R, — */ : 31;
	}bits;
	unsigned int u32;
} U_USI_SPISTA;

/* INTRCTRL (0x0000004c) - INTR_CTRL */
typedef union
{
	struct
	{
		unsigned int tx_fifo_th /* tx_fifo_th, R/W, TX FIFO threshold：`0` = keep；`1` ~ `7` = 1 ~ 7 byte */ : 3;
		unsigned int /* rsvd_7_3 */ /* R, — */ : 5;
		unsigned int rx_fifo_th /* rx_fifo_th, R/W, RX FIFO threshold：`0` = keep；`1` ~ `7` = 1 ~ 7 byte */ : 3;
		unsigned int /* rsvd_15_11 */ /* R, — */ : 5;
		unsigned int th_mode /* th_mode, R/W, `1` = not less than threshold；`0` = not larger than threshol */ : 1;
		unsigned int /* rsvd_31_17 */ /* R, — */ : 15;
	}bits;
	unsigned int u32;
} U_USI_INTRCTRL;

/* INTREN (0x00000050) - INTR_EN */
typedef union
{
	struct
	{
		unsigned int tx_thold_en /* tx_thold_en, R/W */ : 1;
		unsigned int tx_empty_en /* tx_empty_en, R/W */ : 1;
		unsigned int tx_full_en /* tx_full_en, R/W */ : 1;
		unsigned int tx_rerr_en /* tx_rerr_en, R/W */ : 1;
		unsigned int tx_werr_en /* tx_werr_en, R/W */ : 1;
		unsigned int rx_thold_en /* rx_thold_en, R/W */ : 1;
		unsigned int rx_empty_en /* rx_empty_en, R/W */ : 1;
		unsigned int rx_full_en /* rx_full_en, R/W */ : 1;
		unsigned int rx_rerr_en /* rx_rerr_en, R/W */ : 1;
		unsigned int rx_werr_en /* rx_werr_en, R/W */ : 1;
		unsigned int uart_tx_stop_en /* uart_tx_stop_en, R/W */ : 1;
		unsigned int uart_rx_stop_en /* uart_rx_stop_en, R/W */ : 1;
		unsigned int uart_perr_en /* uart_perr_en, R/W */ : 1;
		unsigned int i2c_stop_en /* i2c_stop_en, R/W */ : 1;
		unsigned int i2c_nack_en /* i2c_nack_en, R/W */ : 1;
		unsigned int i2cm_lose_arbi_en /* i2cm_lose_arbi_en, R/W */ : 1;
		unsigned int i2cs_gcall_en /* i2cs_gcall_en, R/W */ : 1;
		unsigned int i2c_aerr_en /* i2c_aerr_en, R/W */ : 1;
		unsigned int spi_stop_en /* spi_stop_en, R/W, 各 bit = 1 时使能对应中断源（`0` = disable, `1` = enable） */ : 1;
		unsigned int /* rsvd_31_19 */ /* R, — */ : 13;
	}bits;
	unsigned int u32;
} U_USI_INTREN;

/* INTRSTA (0x00000054) - INTR_STA */
typedef union
{
	struct
	{
		unsigned int tx_thold /* tx_thold, R */ : 1;
		unsigned int tx_empty /* tx_empty, R */ : 1;
		unsigned int tx_full /* tx_full, R */ : 1;
		unsigned int tx_rerr /* tx_rerr, R */ : 1;
		unsigned int tx_werr /* tx_werr, R */ : 1;
		unsigned int rx_thold /* rx_thold, R */ : 1;
		unsigned int rx_empty /* rx_empty, R */ : 1;
		unsigned int rx_full /* rx_full, R */ : 1;
		unsigned int rx_rerr /* rx_rerr, R */ : 1;
		unsigned int rx_werr /* rx_werr, R */ : 1;
		unsigned int uart_tx_stop /* uart_tx_stop, R */ : 1;
		unsigned int uart_rx_stop /* uart_rx_stop, R */ : 1;
		unsigned int uart_perr /* uart_perr, R */ : 1;
		unsigned int i2c_stop /* i2c_stop, R */ : 1;
		unsigned int i2c_nack /* i2c_nack, R */ : 1;
		unsigned int i2cm_lose_arbi /* i2cm_lose_arbi, R */ : 1;
		unsigned int i2cs_gcall /* i2cs_gcall, R */ : 1;
		unsigned int i2c_aerr /* i2c_aerr, R */ : 1;
		unsigned int spi_stop /* spi_stop, R, 各 bit 含义与 `RAW_INTR_STA` 同位对应 */ : 1;
		unsigned int /* rsvd_31_19 */ /* R, — */ : 13;
	}bits;
	unsigned int u32;
} U_USI_INTRSTA;

/* RAWINTRSTA (0x00000058) - RAW_INTR_STA */
typedef union
{
	struct
	{
		unsigned int raw_tx_thold /* raw_tx_thold, R, TX FIFO 阈值触发（依 `TH_MODE`） */ : 1;
		unsigned int raw_tx_empty /* raw_tx_empty, R, TX FIFO 空 */ : 1;
		unsigned int raw_tx_full /* raw_tx_full, R, TX FIFO 满 */ : 1;
		unsigned int raw_tx_rerr /* raw_tx_rerr, R, TX FIFO 空后读 */ : 1;
		unsigned int raw_tx_werr /* raw_tx_werr, R, TX FIFO 满后写 */ : 1;
		unsigned int raw_rx_thold /* raw_rx_thold, R, RX FIFO 阈值触发（依 `TH_MODE`） */ : 1;
		unsigned int raw_rx_empty /* raw_rx_empty, R, RX FIFO 空 */ : 1;
		unsigned int raw_rx_full /* raw_rx_full, R, RX FIFO 满 */ : 1;
		unsigned int raw_rx_rerr /* raw_rx_rerr, R, RX FIFO 空后读 */ : 1;
		unsigned int raw_rx_werr /* raw_rx_werr, R, RX FIFO 满后写 */ : 1;
		unsigned int raw_uart_tx_stop /* raw_uart_tx_stop, R, UART TX STOP */ : 1;
		unsigned int raw_uart_rx_stop /* raw_uart_rx_stop, R, UART RX STOP */ : 1;
		unsigned int raw_uart_perr /* raw_uart_perr, R, UART 校验错 */ : 1;
		unsigned int raw_i2c_stop /* raw_i2c_stop, R, I2C STOP */ : 1;
		unsigned int raw_i2c_nack /* raw_i2c_nack, R, I2C NACK */ : 1;
		unsigned int raw_i2cm_lose_arbi /* raw_i2cm_lose_arbi, R, I2CM 仲裁失败 */ : 1;
		unsigned int raw_i2cs_gcall /* raw_i2cs_gcall, R, I2CS 收到 general call */ : 1;
		unsigned int raw_i2c_aerr /* raw_i2c_aerr, R, I2C 仲裁/总线错误 */ : 1;
		unsigned int raw_spi_stop /* raw_spi_stop, R, SPI 停止事件 */ : 1;
		unsigned int /* rsvd_31_19 */ /* R, — */ : 13;
	}bits;
	unsigned int u32;
} U_USI_RAWINTRSTA;

/* INTRUNMASK (0x0000005c) - INTR_UNMASK */
typedef union
{
	struct
	{
		unsigned int tx_thold_mask /* tx_thold_mask, R/W */ : 1;
		unsigned int tx_empty_mask /* tx_empty_mask, R/W */ : 1;
		unsigned int tx_full_mask /* tx_full_mask, R/W */ : 1;
		unsigned int tx_rerr_mask /* tx_rerr_mask, R/W */ : 1;
		unsigned int tx_werr_mask /* tx_werr_mask, R/W */ : 1;
		unsigned int rx_thold_mask /* rx_thold_mask, R/W */ : 1;
		unsigned int rx_empty_mask /* rx_empty_mask, R/W */ : 1;
		unsigned int rx_full_mask /* rx_full_mask, R/W */ : 1;
		unsigned int rx_rerr_mask /* rx_rerr_mask, R/W */ : 1;
		unsigned int rx_werr_mask /* rx_werr_mask, R/W */ : 1;
		unsigned int uart_tx_stop_mask /* uart_tx_stop_mask, R/W */ : 1;
		unsigned int uart_rx_stop_mask /* uart_rx_stop_mask, R/W */ : 1;
		unsigned int uart_perr_mask /* uart_perr_mask, R/W */ : 1;
		unsigned int i2c_stop_mask /* i2c_stop_mask, R/W */ : 1;
		unsigned int i2c_nack_mask /* i2c_nack_mask, R/W */ : 1;
		unsigned int i2cm_lose_arbi_mask /* i2cm_lose_arbi_mask, R/W */ : 1;
		unsigned int i2cs_gcall_mask /* i2cs_gcall_mask, R/W */ : 1;
		unsigned int i2c_aerr_mask /* i2c_aerr_mask, R/W */ : 1;
		unsigned int spi_stop_mask /* spi_stop_mask, R/W, `0` = masked；`1` = unmasked */ : 1;
		unsigned int /* rsvd_31_19 */ /* R, — */ : 13;
	}bits;
	unsigned int u32;
} U_USI_INTRUNMASK;

/* INTRCLR (0x00000060) - INTR_CLR */
typedef union
{
	struct
	{
		unsigned int tx_thold_clr /* tx_thold_clr, W */ : 1;
		unsigned int tx_empty_clr /* tx_empty_clr, W */ : 1;
		unsigned int tx_full_clr /* tx_full_clr, W */ : 1;
		unsigned int tx_rerr_clr /* tx_rerr_clr, W */ : 1;
		unsigned int tx_werr_clr /* tx_werr_clr, W */ : 1;
		unsigned int rx_thold_clr /* rx_thold_clr, W */ : 1;
		unsigned int rx_empty_clr /* rx_empty_clr, W */ : 1;
		unsigned int rx_full_clr /* rx_full_clr, W */ : 1;
		unsigned int rx_rerr_clr /* rx_rerr_clr, W */ : 1;
		unsigned int rx_werr_clr /* rx_werr_clr, W */ : 1;
		unsigned int uart_tx_stop_clr /* uart_tx_stop_clr, W */ : 1;
		unsigned int uart_rx_stop_clr /* uart_rx_stop_clr, W */ : 1;
		unsigned int uart_perr_clr /* uart_perr_clr, W */ : 1;
		unsigned int i2c_stop_clr /* i2c_stop_clr, W */ : 1;
		unsigned int i2c_nack_clr /* i2c_nack_clr, W */ : 1;
		unsigned int i2cm_lose_arbi_clr /* i2cm_lose_arbi_clr, W */ : 1;
		unsigned int i2cs_gcall_clr /* i2cs_gcall_clr, W */ : 1;
		unsigned int i2c_aerr_clr /* i2c_aerr_clr, W */ : 1;
		unsigned int spi_stop_clr /* spi_stop_clr, W, Write `1'b1` to clear the corresponding `RAW_*` interrupt */ : 1;
		unsigned int /* rsvd_31_19 */ /* R, — */ : 13;
	}bits;
	unsigned int u32;
} U_USI_INTRCLR;

/* DMACTRL (0x00000064) - DMA_CTRL */
typedef union
{
	struct
	{
		unsigned int tx_dma_en /* tx_dma_en, R/W, TX FIFO DMA 接口 enable */ : 1;
		unsigned int rx_dma_en /* rx_dma_en, R/W, RX FIFO DMA 接口 enable */ : 1;
		unsigned int /* rsvd_31_2 */ /* R, — */ : 30;
	}bits;
	unsigned int u32;
} U_USI_DMACTRL;

/* DMATHRESHOLD (0x00000068) - DMA_THRESHOLD */
typedef union
{
	struct
	{
		unsigned int tx_dma_th /* tx_dma_th, R/W, TX DMA trigger threshold（编码同 RX） */ : 4;
		unsigned int /* rsvd_7_4 */ /* R, — */ : 4;
		unsigned int rx_dma_th /* rx_dma_th, R/W, RX DMA trigger threshold（4-bit 字段，含 `0x0`=keep / `0x1`-`0x8` */ : 4;
		unsigned int /* rsvd_31_12 */ /* R, — */ : 20;
	}bits;
	unsigned int u32;
} U_USI_DMATHRESHOLD;

/* SPINSSDATA (0x0000006c) - SPI_NSS_DATA */
typedef union
{
	struct
	{
		unsigned int nss_data /* nss_data, R/W, 当 `NSS_CTRL=1` 时：`0` 透传到 NSS，`1` 透传到 NSS */ : 1;
		unsigned int /* rsvd_31_1 */ /* R, — */ : 31;
	}bits;
	unsigned int u32;
} U_USI_SPINSSDATA;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define USI_REG_BASE_ADDR						0x50028000

#define USI_USICTRL_REG_OFFSET					0x00000000
#define USI_MODESEL_REG_OFFSET					0x00000004
#define USI_RXFIFO_REG_OFFSET					0x00000008
#define USI_TXFIFO_REG_OFFSET					0x00000008
#define USI_FIFOSTA_REG_OFFSET					0x0000000c
#define USI_CLKDIV0_REG_OFFSET					0x00000010
#define USI_CLKDIV1_REG_OFFSET					0x00000014
#define USI_UARTCTRL_REG_OFFSET					0x00000018
#define USI_UARTSTA_REG_OFFSET					0x0000001c
#define USI_I2CMODE_REG_OFFSET					0x00000020
#define USI_I2CADDR_REG_OFFSET					0x00000024
#define USI_I2CMCTRL_REG_OFFSET					0x00000028
#define USI_I2CMCODE_REG_OFFSET					0x0000002c
#define USI_I2CSCTRL_REG_OFFSET					0x00000030
#define USI_I2CFMDIV_REG_OFFSET					0x00000034
#define USI_I2CHOLD_REG_OFFSET					0x00000038
#define USI_I2CSTA_REG_OFFSET					0x0000003c
#define USI_SPIMODE_REG_OFFSET					0x00000040
#define USI_SPICTRL_REG_OFFSET					0x00000044
#define USI_SPISTA_REG_OFFSET					0x00000048
#define USI_INTRCTRL_REG_OFFSET					0x0000004c
#define USI_INTREN_REG_OFFSET					0x00000050
#define USI_INTRSTA_REG_OFFSET					0x00000054
#define USI_RAWINTRSTA_REG_OFFSET					0x00000058
#define USI_INTRUNMASK_REG_OFFSET					0x0000005c
#define USI_INTRCLR_REG_OFFSET					0x00000060
#define USI_DMACTRL_REG_OFFSET					0x00000064
#define USI_DMATHRESHOLD_REG_OFFSET					0x00000068
#define USI_SPINSSDATA_REG_OFFSET					0x0000006c

#define USI_USICTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_USICTRL_REG_OFFSET)
#define USI_MODESEL_REG_ADDR						(USI_REG_BASE_ADDR + USI_MODESEL_REG_OFFSET)
#define USI_RXFIFO_REG_ADDR						(USI_REG_BASE_ADDR + USI_RXFIFO_REG_OFFSET)
#define USI_TXFIFO_REG_ADDR						(USI_REG_BASE_ADDR + USI_TXFIFO_REG_OFFSET)
#define USI_FIFOSTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_FIFOSTA_REG_OFFSET)
#define USI_CLKDIV0_REG_ADDR						(USI_REG_BASE_ADDR + USI_CLKDIV0_REG_OFFSET)
#define USI_CLKDIV1_REG_ADDR						(USI_REG_BASE_ADDR + USI_CLKDIV1_REG_OFFSET)
#define USI_UARTCTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_UARTCTRL_REG_OFFSET)
#define USI_UARTSTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_UARTSTA_REG_OFFSET)
#define USI_I2CMODE_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CMODE_REG_OFFSET)
#define USI_I2CADDR_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CADDR_REG_OFFSET)
#define USI_I2CMCTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CMCTRL_REG_OFFSET)
#define USI_I2CMCODE_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CMCODE_REG_OFFSET)
#define USI_I2CSCTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CSCTRL_REG_OFFSET)
#define USI_I2CFMDIV_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CFMDIV_REG_OFFSET)
#define USI_I2CHOLD_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CHOLD_REG_OFFSET)
#define USI_I2CSTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_I2CSTA_REG_OFFSET)
#define USI_SPIMODE_REG_ADDR						(USI_REG_BASE_ADDR + USI_SPIMODE_REG_OFFSET)
#define USI_SPICTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_SPICTRL_REG_OFFSET)
#define USI_SPISTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_SPISTA_REG_OFFSET)
#define USI_INTRCTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_INTRCTRL_REG_OFFSET)
#define USI_INTREN_REG_ADDR						(USI_REG_BASE_ADDR + USI_INTREN_REG_OFFSET)
#define USI_INTRSTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_INTRSTA_REG_OFFSET)
#define USI_RAWINTRSTA_REG_ADDR						(USI_REG_BASE_ADDR + USI_RAWINTRSTA_REG_OFFSET)
#define USI_INTRUNMASK_REG_ADDR						(USI_REG_BASE_ADDR + USI_INTRUNMASK_REG_OFFSET)
#define USI_INTRCLR_REG_ADDR						(USI_REG_BASE_ADDR + USI_INTRCLR_REG_OFFSET)
#define USI_DMACTRL_REG_ADDR						(USI_REG_BASE_ADDR + USI_DMACTRL_REG_OFFSET)
#define USI_DMATHRESHOLD_REG_ADDR						(USI_REG_BASE_ADDR + USI_DMATHRESHOLD_REG_OFFSET)
#define USI_SPINSSDATA_REG_ADDR						(USI_REG_BASE_ADDR + USI_SPINSSDATA_REG_OFFSET)

#endif //__USI_REG_DEF_H__
