/* USI Register Definition (SystemVerilog Header) */
#ifndef __USI_REG_DEF_SVH__
#define __USI_REG_DEF_SVH__

/*
 * ============================================================================
 * USI Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x50028000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* USICTRL (0x00000000) - USI_CTRL */
typedef union {
    struct packed {
        const bit[27:0]   /* rsvd_31_4 */ /* R */;
        bit                 rx_fifo_en /* rx_fifo_en, R/W */;
        bit                 tx_fifo_en /* tx_fifo_en, R/W */;
        bit                 fm_en /* fm_en, R/W */;
        bit                 usi_en /* usi_en, R/W */;
    }bits;
    int unsigned u32 = {28'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_USICTRL;

/* MODESEL (0x00000004) - MODE_SEL */
typedef union {
    struct packed {
        const bit[29:0]   /* rsvd_31_2 */ /* R */;
        bit[1:0]        mode_sel /* mode_sel, R/W */;
    }bits;
    int unsigned u32 = {30'h0, 2'h0};
} U_USI_MODESEL;

/* RXFIFO (0x00000008) - TX_FIFO */
typedef union {
    struct packed {
        const bit[15:0]   /* rsvd_31_16 */ /* R */;
        bit[15:0]        rx_data /* rx_data, R */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_USI_RXFIFO;

/* TXFIFO (0x00000008) - TX_FIFO */
typedef union {
    struct packed {
        const bit[15:0]   /* rsvd_31_16 */ /* R */;
        bit[15:0]        tx_data /* tx_data, W */;
    }bits;
    int unsigned u32 = {16'h0, 16'h0};
} U_USI_TXFIFO;

/* FIFOSTA (0x0000000c) - FIFO_STA */
typedef union {
    struct packed {
        const bit[11:0]   /* rsvd_31_20 */ /* R */;
        bit[3:0]        rx_num /* rx_num, R */;
        const bit[3:0]   /* rsvd_15_12 */ /* R */;
        bit[3:0]        tx_num /* tx_num, R */;
        const bit[3:0]   /* rsvd_7_4 */ /* R */;
        bit                 rx_full /* rx_full, R */;
        bit                 rx_empty /* rx_empty, R */;
        bit                 tx_full /* tx_full, R */;
        bit                 tx_empty /* tx_empty, R */;
    }bits;
    int unsigned u32 = {12'h0, 4'h0, 4'h0, 4'h0, 4'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_FIFOSTA;

/* CLKDIV0 (0x00000010) - CLK_DIV0 */
typedef union {
    struct packed {
        const bit[7:0]   /* rsvd_31_24 */ /* R */;
        bit[23:0]        clk_div0 /* clk_div0, R/W */;
    }bits;
    int unsigned u32 = {8'h0, 24'h0};
} U_USI_CLKDIV0;

/* CLKDIV1 (0x00000014) - CLK_DIV1 */
typedef union {
    struct packed {
        const bit[7:0]   /* rsvd_31_24 */ /* R */;
        bit[23:0]        clk_div1 /* clk_div1, R/W */;
    }bits;
    int unsigned u32 = {8'h0, 24'h0};
} U_USI_CLKDIV1;

/* UARTCTRL (0x00000018) - UART_CTRL */
typedef union {
    struct packed {
        const bit[25:0]   /* rsvd_31_6 */ /* R */;
        bit                 eps /* eps, R/W */;
        bit                 pen /* pen, R/W */;
        bit[1:0]        pbit /* pbit, R/W */;
        bit[1:0]        dbit /* dbit, R/W */;
    }bits;
    int unsigned u32 = {26'h0, 1'h0, 1'h0, 2'h0, 2'h0};
} U_USI_UARTCTRL;

/* UARTSTA (0x0000001c) - UART_STA */
typedef union {
    struct packed {
        const bit[29:0]   /* rsvd_31_2 */ /* R */;
        bit                 rxd_work /* rxd_work, R */;
        bit                 txd_work /* txd_work, R */;
    }bits;
    int unsigned u32 = {30'h0, 1'h0, 1'h0};
} U_USI_UARTSTA;

/* I2CMODE (0x00000020) - I2C_MODE */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* R */;
        bit                 ms_mode /* ms_mode, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_USI_I2CMODE;

/* I2CADDR (0x00000024) - I2C_ADDR */
typedef union {
    struct packed {
        const bit[21:0]   /* rsvd_31_10 */ /* R */;
        bit[9:0]        i2c_addr /* i2c_addr, R/W */;
    }bits;
    int unsigned u32 = {22'h0, 10'h0};
} U_USI_I2CADDR;

/* I2CMCTRL (0x00000028) - I2CM_CTRL */
typedef union {
    struct packed {
        const bit[26:0]   /* rsvd_31_5 */ /* R */;
        bit                 gcall /* gcall, R/W */;
        bit                 sbyte /* sbyte, R/W */;
        bit                 hs_mode /* hs_mode, R/W */;
        bit                 stop /* stop, R/W */;
        bit                 addr_mode /* addr_mode, R/W */;
    }bits;
    int unsigned u32 = {27'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_I2CMCTRL;

/* I2CMCODE (0x0000002c) - I2CM_CODE */
typedef union {
    struct packed {
        const bit[28:0]   /* rsvd_31_3 */ /* R */;
        bit[2:0]        mcode /* mcode, R/W */;
    }bits;
    int unsigned u32 = {29'h0, 3'h0};
} U_USI_I2CMCODE;

/* I2CSCTRL (0x00000030) - I2CS_CTRL */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* R */;
        bit                 gcall_mode /* gcall_mode, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_USI_I2CSCTRL;

/* I2CFMDIV (0x00000034) - I2C_FM_DIV */
typedef union {
    struct packed {
        const bit[23:0]   /* rsvd_31_8 */ /* R */;
        bit[7:0]        i2c_fm_div /* i2c_fm_div, R/W */;
    }bits;
    int unsigned u32 = {24'h0, 8'h0};
} U_USI_I2CFMDIV;

/* I2CHOLD (0x00000038) - I2C_HOLD */
typedef union {
    struct packed {
        const bit[23:0]   /* rsvd_31_8 */ /* R */;
        bit[7:0]        i2c_hold /* i2c_hold, R/W */;
    }bits;
    int unsigned u32 = {24'h0, 8'h0};
} U_USI_I2CHOLD;

/* I2CSTA (0x0000003c) - I2C_STA */
typedef union {
    struct packed {
        const bit[22:0]   /* rsvd_31_9 */ /* R */;
        bit                 i2cs_work /* i2cs_work, R */;
        const bit[5:0]   /* rsvd_7_2 */ /* R */;
        bit                 i2cm_data /* i2cm_data, R */;
        bit                 i2cm_work /* i2cm_work, R */;
    }bits;
    int unsigned u32 = {23'h0, 1'h0, 6'h0, 1'h0, 1'h0};
} U_USI_I2CSTA;

/* SPIMODE (0x00000040) - SPI_MODE */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* R */;
        bit                 ms_mode /* ms_mode, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_USI_SPIMODE;

/* SPICTRL (0x00000044) - SPI_CTRL */
typedef union {
    struct packed {
        const bit[21:0]   /* rsvd_31_10 */ /* R */;
        bit                 nss_ctrl /* nss_ctrl, R/W */;
        bit                 nss_toggle /* nss_toggle, R/W */;
        bit                 cpol /* cpol, R/W */;
        bit                 cpha /* cpha, R/W */;
        bit[1:0]        tmod /* tmod, R/W */;
        bit[3:0]        data_size /* data_size, R/W */;
    }bits;
    int unsigned u32 = {22'h0, 1'h0, 1'h0, 1'h0, 1'h0, 2'h0, 4'h0};
} U_USI_SPICTRL;

/* SPISTA (0x00000048) - SPI_STA */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* R */;
        bit                 spi_working /* spi_working, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_USI_SPISTA;

/* INTRCTRL (0x0000004c) - INTR_CTRL */
typedef union {
    struct packed {
        const bit[14:0]   /* rsvd_31_17 */ /* R */;
        bit                 th_mode /* th_mode, R/W */;
        const bit[4:0]   /* rsvd_15_11 */ /* R */;
        bit[2:0]        rx_fifo_th /* rx_fifo_th, R/W */;
        const bit[4:0]   /* rsvd_7_3 */ /* R */;
        bit[2:0]        tx_fifo_th /* tx_fifo_th, R/W */;
    }bits;
    int unsigned u32 = {15'h0, 1'h0, 5'h0, 3'h0, 5'h0, 3'h0};
} U_USI_INTRCTRL;

/* INTREN (0x00000050) - INTR_EN */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* R */;
        bit                 spi_stop_en /* spi_stop_en, R/W */;
        bit                 i2c_aerr_en /* i2c_aerr_en, R/W */;
        bit                 i2cs_gcall_en /* i2cs_gcall_en, R/W */;
        bit                 i2cm_lose_arbi_en /* i2cm_lose_arbi_en, R/W */;
        bit                 i2c_nack_en /* i2c_nack_en, R/W */;
        bit                 i2c_stop_en /* i2c_stop_en, R/W */;
        bit                 uart_perr_en /* uart_perr_en, R/W */;
        bit                 uart_rx_stop_en /* uart_rx_stop_en, R/W */;
        bit                 uart_tx_stop_en /* uart_tx_stop_en, R/W */;
        bit                 rx_werr_en /* rx_werr_en, R/W */;
        bit                 rx_rerr_en /* rx_rerr_en, R/W */;
        bit                 rx_full_en /* rx_full_en, R/W */;
        bit                 rx_empty_en /* rx_empty_en, R/W */;
        bit                 rx_thold_en /* rx_thold_en, R/W */;
        bit                 tx_werr_en /* tx_werr_en, R/W */;
        bit                 tx_rerr_en /* tx_rerr_en, R/W */;
        bit                 tx_full_en /* tx_full_en, R/W */;
        bit                 tx_empty_en /* tx_empty_en, R/W */;
        bit                 tx_thold_en /* tx_thold_en, R/W */;
    }bits;
    int unsigned u32 = {13'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_INTREN;

/* INTRSTA (0x00000054) - INTR_STA */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* R */;
        bit                 spi_stop /* spi_stop, R */;
        bit                 i2c_aerr /* i2c_aerr, R */;
        bit                 i2cs_gcall /* i2cs_gcall, R */;
        bit                 i2cm_lose_arbi /* i2cm_lose_arbi, R */;
        bit                 i2c_nack /* i2c_nack, R */;
        bit                 i2c_stop /* i2c_stop, R */;
        bit                 uart_perr /* uart_perr, R */;
        bit                 uart_rx_stop /* uart_rx_stop, R */;
        bit                 uart_tx_stop /* uart_tx_stop, R */;
        bit                 rx_werr /* rx_werr, R */;
        bit                 rx_rerr /* rx_rerr, R */;
        bit                 rx_full /* rx_full, R */;
        bit                 rx_empty /* rx_empty, R */;
        bit                 rx_thold /* rx_thold, R */;
        bit                 tx_werr /* tx_werr, R */;
        bit                 tx_rerr /* tx_rerr, R */;
        bit                 tx_full /* tx_full, R */;
        bit                 tx_empty /* tx_empty, R */;
        bit                 tx_thold /* tx_thold, R */;
    }bits;
    int unsigned u32 = {13'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_INTRSTA;

/* RAWINTRSTA (0x00000058) - RAW_INTR_STA */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* R */;
        bit                 raw_spi_stop /* raw_spi_stop, R */;
        bit                 raw_i2c_aerr /* raw_i2c_aerr, R */;
        bit                 raw_i2cs_gcall /* raw_i2cs_gcall, R */;
        bit                 raw_i2cm_lose_arbi /* raw_i2cm_lose_arbi, R */;
        bit                 raw_i2c_nack /* raw_i2c_nack, R */;
        bit                 raw_i2c_stop /* raw_i2c_stop, R */;
        bit                 raw_uart_perr /* raw_uart_perr, R */;
        bit                 raw_uart_rx_stop /* raw_uart_rx_stop, R */;
        bit                 raw_uart_tx_stop /* raw_uart_tx_stop, R */;
        bit                 raw_rx_werr /* raw_rx_werr, R */;
        bit                 raw_rx_rerr /* raw_rx_rerr, R */;
        bit                 raw_rx_full /* raw_rx_full, R */;
        bit                 raw_rx_empty /* raw_rx_empty, R */;
        bit                 raw_rx_thold /* raw_rx_thold, R */;
        bit                 raw_tx_werr /* raw_tx_werr, R */;
        bit                 raw_tx_rerr /* raw_tx_rerr, R */;
        bit                 raw_tx_full /* raw_tx_full, R */;
        bit                 raw_tx_empty /* raw_tx_empty, R */;
        bit                 raw_tx_thold /* raw_tx_thold, R */;
    }bits;
    int unsigned u32 = {13'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_RAWINTRSTA;

/* INTRUNMASK (0x0000005c) - INTR_UNMASK */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* R */;
        bit                 spi_stop_mask /* spi_stop_mask, R/W */;
        bit                 i2c_aerr_mask /* i2c_aerr_mask, R/W */;
        bit                 i2cs_gcall_mask /* i2cs_gcall_mask, R/W */;
        bit                 i2cm_lose_arbi_mask /* i2cm_lose_arbi_mask, R/W */;
        bit                 i2c_nack_mask /* i2c_nack_mask, R/W */;
        bit                 i2c_stop_mask /* i2c_stop_mask, R/W */;
        bit                 uart_perr_mask /* uart_perr_mask, R/W */;
        bit                 uart_rx_stop_mask /* uart_rx_stop_mask, R/W */;
        bit                 uart_tx_stop_mask /* uart_tx_stop_mask, R/W */;
        bit                 rx_werr_mask /* rx_werr_mask, R/W */;
        bit                 rx_rerr_mask /* rx_rerr_mask, R/W */;
        bit                 rx_full_mask /* rx_full_mask, R/W */;
        bit                 rx_empty_mask /* rx_empty_mask, R/W */;
        bit                 rx_thold_mask /* rx_thold_mask, R/W */;
        bit                 tx_werr_mask /* tx_werr_mask, R/W */;
        bit                 tx_rerr_mask /* tx_rerr_mask, R/W */;
        bit                 tx_full_mask /* tx_full_mask, R/W */;
        bit                 tx_empty_mask /* tx_empty_mask, R/W */;
        bit                 tx_thold_mask /* tx_thold_mask, R/W */;
    }bits;
    int unsigned u32 = {13'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_INTRUNMASK;

/* INTRCLR (0x00000060) - INTR_CLR */
typedef union {
    struct packed {
        const bit[12:0]   /* rsvd_31_19 */ /* R */;
        bit                 spi_stop_clr /* spi_stop_clr, W */;
        bit                 i2c_aerr_clr /* i2c_aerr_clr, W */;
        bit                 i2cs_gcall_clr /* i2cs_gcall_clr, W */;
        bit                 i2cm_lose_arbi_clr /* i2cm_lose_arbi_clr, W */;
        bit                 i2c_nack_clr /* i2c_nack_clr, W */;
        bit                 i2c_stop_clr /* i2c_stop_clr, W */;
        bit                 uart_perr_clr /* uart_perr_clr, W */;
        bit                 uart_rx_stop_clr /* uart_rx_stop_clr, W */;
        bit                 uart_tx_stop_clr /* uart_tx_stop_clr, W */;
        bit                 rx_werr_clr /* rx_werr_clr, W */;
        bit                 rx_rerr_clr /* rx_rerr_clr, W */;
        bit                 rx_full_clr /* rx_full_clr, W */;
        bit                 rx_empty_clr /* rx_empty_clr, W */;
        bit                 rx_thold_clr /* rx_thold_clr, W */;
        bit                 tx_werr_clr /* tx_werr_clr, W */;
        bit                 tx_rerr_clr /* tx_rerr_clr, W */;
        bit                 tx_full_clr /* tx_full_clr, W */;
        bit                 tx_empty_clr /* tx_empty_clr, W */;
        bit                 tx_thold_clr /* tx_thold_clr, W */;
    }bits;
    int unsigned u32 = {13'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
} U_USI_INTRCLR;

/* DMACTRL (0x00000064) - DMA_CTRL */
typedef union {
    struct packed {
        const bit[29:0]   /* rsvd_31_2 */ /* R */;
        bit                 rx_dma_en /* rx_dma_en, R/W */;
        bit                 tx_dma_en /* tx_dma_en, R/W */;
    }bits;
    int unsigned u32 = {30'h0, 1'h0, 1'h0};
} U_USI_DMACTRL;

/* DMATHRESHOLD (0x00000068) - DMA_THRESHOLD */
typedef union {
    struct packed {
        const bit[19:0]   /* rsvd_31_12 */ /* R */;
        bit[3:0]        rx_dma_th /* rx_dma_th, R/W */;
        const bit[3:0]   /* rsvd_7_4 */ /* R */;
        bit[3:0]        tx_dma_th /* tx_dma_th, R/W */;
    }bits;
    int unsigned u32 = {20'h0, 4'h0, 4'h0, 4'h0};
} U_USI_DMATHRESHOLD;

/* SPINSSDATA (0x0000006c) - SPI_NSS_DATA */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* R */;
        bit                 nss_data /* nss_data, R/W */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_USI_SPINSSDATA;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define USI_REG_BASE_ADDR						'h50028000

`define USI_USICTRL_REG_OFFSET					0x00000000
`define USI_MODESEL_REG_OFFSET					0x00000004
`define USI_RXFIFO_REG_OFFSET					0x00000008
`define USI_TXFIFO_REG_OFFSET					0x00000008
`define USI_FIFOSTA_REG_OFFSET					0x0000000c
`define USI_CLKDIV0_REG_OFFSET					0x00000010
`define USI_CLKDIV1_REG_OFFSET					0x00000014
`define USI_UARTCTRL_REG_OFFSET					0x00000018
`define USI_UARTSTA_REG_OFFSET					0x0000001c
`define USI_I2CMODE_REG_OFFSET					0x00000020
`define USI_I2CADDR_REG_OFFSET					0x00000024
`define USI_I2CMCTRL_REG_OFFSET					0x00000028
`define USI_I2CMCODE_REG_OFFSET					0x0000002c
`define USI_I2CSCTRL_REG_OFFSET					0x00000030
`define USI_I2CFMDIV_REG_OFFSET					0x00000034
`define USI_I2CHOLD_REG_OFFSET					0x00000038
`define USI_I2CSTA_REG_OFFSET					0x0000003c
`define USI_SPIMODE_REG_OFFSET					0x00000040
`define USI_SPICTRL_REG_OFFSET					0x00000044
`define USI_SPISTA_REG_OFFSET					0x00000048
`define USI_INTRCTRL_REG_OFFSET					0x0000004c
`define USI_INTREN_REG_OFFSET					0x00000050
`define USI_INTRSTA_REG_OFFSET					0x00000054
`define USI_RAWINTRSTA_REG_OFFSET					0x00000058
`define USI_INTRUNMASK_REG_OFFSET					0x0000005c
`define USI_INTRCLR_REG_OFFSET					0x00000060
`define USI_DMACTRL_REG_OFFSET					0x00000064
`define USI_DMATHRESHOLD_REG_OFFSET					0x00000068
`define USI_SPINSSDATA_REG_OFFSET					0x0000006c

`define USI_USICTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_USICTRL_REG_OFFSET)
`define USI_MODESEL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_MODESEL_REG_OFFSET)
`define USI_RXFIFO_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_RXFIFO_REG_OFFSET)
`define USI_TXFIFO_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_TXFIFO_REG_OFFSET)
`define USI_FIFOSTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_FIFOSTA_REG_OFFSET)
`define USI_CLKDIV0_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_CLKDIV0_REG_OFFSET)
`define USI_CLKDIV1_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_CLKDIV1_REG_OFFSET)
`define USI_UARTCTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_UARTCTRL_REG_OFFSET)
`define USI_UARTSTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_UARTSTA_REG_OFFSET)
`define USI_I2CMODE_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CMODE_REG_OFFSET)
`define USI_I2CADDR_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CADDR_REG_OFFSET)
`define USI_I2CMCTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CMCTRL_REG_OFFSET)
`define USI_I2CMCODE_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CMCODE_REG_OFFSET)
`define USI_I2CSCTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CSCTRL_REG_OFFSET)
`define USI_I2CFMDIV_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CFMDIV_REG_OFFSET)
`define USI_I2CHOLD_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CHOLD_REG_OFFSET)
`define USI_I2CSTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_I2CSTA_REG_OFFSET)
`define USI_SPIMODE_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_SPIMODE_REG_OFFSET)
`define USI_SPICTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_SPICTRL_REG_OFFSET)
`define USI_SPISTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_SPISTA_REG_OFFSET)
`define USI_INTRCTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_INTRCTRL_REG_OFFSET)
`define USI_INTREN_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_INTREN_REG_OFFSET)
`define USI_INTRSTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_INTRSTA_REG_OFFSET)
`define USI_RAWINTRSTA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_RAWINTRSTA_REG_OFFSET)
`define USI_INTRUNMASK_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_INTRUNMASK_REG_OFFSET)
`define USI_INTRCLR_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_INTRCLR_REG_OFFSET)
`define USI_DMACTRL_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_DMACTRL_REG_OFFSET)
`define USI_DMATHRESHOLD_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_DMATHRESHOLD_REG_OFFSET)
`define USI_SPINSSDATA_REG_ADDR					(`USI_REG_BASE_ADDR + `USI_SPINSSDATA_REG_OFFSET)


#endif //__USI_REG_DEF_SVH__
