#ifndef __WDT_REG_DEF_H__
#define __WDT_REG_DEF_H__

/*
 * ============================================================================
 * WDT Register Definition (C / BSP Header)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: APB/AHB/AXI byte-addressable, 32-bit data width.
 * Naming follows the project convention used by
 *     dv/simulation/verif_env/soc/header_files/<ip>RegDef.h
 *
 * Base address: 0x50008000.
 * ============================================================================
 */


/* ===== Section 4 ===== */

/* WDTCR (0x00000000) - WDT_CR */
typedef union
{
	struct
	{
		unsigned int wdt_en /* wdt_en, R/W, Once enabled, only cleared by system reset. `0` = WDT disabl */ : 1;
		unsigned int rmod /* rmod, R/W, `0` = Generate a system reset; `1` = First generate an inter */ : 1;
		unsigned int rpl /* rpl, R/W, 系统复位持续 pclk 周期数编码：<br>`000` = 2 pclk; `001` = 4; `010` = 8;  */ : 3;
		unsigned int /* rsvd_31_5 */ /* —, Reserved, read as zero */ : 27;
	}bits;
	unsigned int u32;
} U_WDT_WDTCR;

/* WDTTIMEOUT (0x00000004) - WDT_time_out */
typedef union
{
	struct
	{
		unsigned int top /* top, R/W, 后续 kick 使用的 timeout period 编码；变更在下一次 kick 后生效。范围与 `TOP_INIT` */ : 4;
		unsigned int top_init /* top_init, R/W, **首次** kick 时使用的 timeout period 编码。该字段在 WDT enabled 后才生效；之后  */ : 4;
		unsigned int /* rsvd_31_8 */ /* —, Reserved, read as zero */ : 24;
	}bits;
	unsigned int u32;
} U_WDT_WDTTIMEOUT;

/* WDTCURRENTVALUE (0x00000008) - WDT_current_value */
typedef union
{
	struct
	{
		unsigned int current_counter_value /* current_counter_value, R, 内部 32-bit counter 当前值（读取保持一致）。Reset: `32'h0000_FFFF` */ : 32;
	}bits;
	unsigned int u32;
} U_WDT_WDTCURRENTVALUE;

/* WDTRESTART (0x0000000c) - WDT_restart */
typedef union
{
	struct
	{
		unsigned int counter_restart_register /* counter_restart_register, W, 喂狗：必须写 `0x76` 才会重启 counter；同时清除 WDT 中断。读返回 0。Reset: `0` */ : 8;
		unsigned int /* rsvd_31_8 */ /* —, Reserved, read as zero */ : 24;
	}bits;
	unsigned int u32;
} U_WDT_WDTRESTART;

/* WDTINTSTATUS (0x00000010) - WDT_int_status */
typedef union
{
	struct
	{
		unsigned int interrupt_status /* interrupt_status, R, `1` = Interrupt is active; `0` = Interrupt is inactive. Rese */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_WDT_WDTINTSTATUS;

/* WDTINTCLR (0x00000014) - WDT_int_clr */
typedef union
{
	struct
	{
		unsigned int interrupt_clear /* interrupt_clear, R, 读清 WDT 中断；不影响 counter（不喂狗）。Reset: `0` */ : 1;
		unsigned int /* rsvd_31_1 */ /* —, Reserved, read as zero */ : 31;
	}bits;
	unsigned int u32;
} U_WDT_WDTINTCLR;


/* Address Base & Per-Register OFFSET / ADDR Macros */

#define WDT_REG_BASE_ADDR						0x50008000

#define WDT_WDTCR_REG_OFFSET					0x00000000
#define WDT_WDTTIMEOUT_REG_OFFSET					0x00000004
#define WDT_WDTCURRENTVALUE_REG_OFFSET					0x00000008
#define WDT_WDTRESTART_REG_OFFSET					0x0000000c
#define WDT_WDTINTSTATUS_REG_OFFSET					0x00000010
#define WDT_WDTINTCLR_REG_OFFSET					0x00000014

#define WDT_WDTCR_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTCR_REG_OFFSET)
#define WDT_WDTTIMEOUT_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTTIMEOUT_REG_OFFSET)
#define WDT_WDTCURRENTVALUE_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTCURRENTVALUE_REG_OFFSET)
#define WDT_WDTRESTART_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTRESTART_REG_OFFSET)
#define WDT_WDTINTSTATUS_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTINTSTATUS_REG_OFFSET)
#define WDT_WDTINTCLR_REG_ADDR						(WDT_REG_BASE_ADDR + WDT_WDTINTCLR_REG_OFFSET)

#endif //__WDT_REG_DEF_H__
