/* WDT Register Definition (SystemVerilog Header) */
#ifndef __WDT_REG_DEF_SVH__
#define __WDT_REG_DEF_SVH__

/*
 * ============================================================================
 * WDT Register Definition (SystemVerilog)
 * ---------------------------------------------------------------------------
 * Auto-generated by reg-def-gen skill from <unknown>
 * Layout: byte-addressable, 32-bit data width.
 *
 * Base address: 0x50008000.
 * ============================================================================
 */




/* ===== Section 4 ===== */

/* WDTCR (0x00000000) - WDT_CR */
typedef union {
    struct packed {
        const bit[26:0]   /* rsvd_31_5 */ /* — */;
        bit[2:0]        rpl /* rpl, R/W */;
        bit                 rmod /* rmod, R/W */;
        bit                 wdt_en /* wdt_en, R/W */;
    }bits;
    int unsigned u32 = {27'h0, 3'h0, 1'h0, 1'h0};
} U_WDT_WDTCR;

/* WDTTIMEOUT (0x00000004) - WDT_time_out */
typedef union {
    struct packed {
        const bit[23:0]   /* rsvd_31_8 */ /* — */;
        bit[3:0]        top_init /* top_init, R/W */;
        bit[3:0]        top /* top, R/W */;
    }bits;
    int unsigned u32 = {24'h0, 4'h0, 4'h0};
} U_WDT_WDTTIMEOUT;

/* WDTCURRENTVALUE (0x00000008) - WDT_current_value */
typedef union {
    struct packed {
        bit[31:0]        current_counter_value /* current_counter_value, R */;
    }bits;
    int unsigned u32 = {32'h0};
} U_WDT_WDTCURRENTVALUE;

/* WDTRESTART (0x0000000c) - WDT_restart */
typedef union {
    struct packed {
        const bit[23:0]   /* rsvd_31_8 */ /* — */;
        bit[7:0]        counter_restart_register /* counter_restart_register, W */;
    }bits;
    int unsigned u32 = {24'h0, 8'h0};
} U_WDT_WDTRESTART;

/* WDTINTSTATUS (0x00000010) - WDT_int_status */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 interrupt_status /* interrupt_status, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_WDT_WDTINTSTATUS;

/* WDTINTCLR (0x00000014) - WDT_int_clr */
typedef union {
    struct packed {
        const bit[30:0]   /* rsvd_31_1 */ /* — */;
        bit                 interrupt_clear /* interrupt_clear, R */;
    }bits;
    int unsigned u32 = {31'h0, 1'h0};
} U_WDT_WDTINTCLR;



/* Address Base & Per-Register OFFSET / ADDR Macros */

`define WDT_REG_BASE_ADDR						'h50008000

`define WDT_WDTCR_REG_OFFSET					0x00000000
`define WDT_WDTTIMEOUT_REG_OFFSET					0x00000004
`define WDT_WDTCURRENTVALUE_REG_OFFSET					0x00000008
`define WDT_WDTRESTART_REG_OFFSET					0x0000000c
`define WDT_WDTINTSTATUS_REG_OFFSET					0x00000010
`define WDT_WDTINTCLR_REG_OFFSET					0x00000014

`define WDT_WDTCR_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTCR_REG_OFFSET)
`define WDT_WDTTIMEOUT_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTTIMEOUT_REG_OFFSET)
`define WDT_WDTCURRENTVALUE_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTCURRENTVALUE_REG_OFFSET)
`define WDT_WDTRESTART_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTRESTART_REG_OFFSET)
`define WDT_WDTINTSTATUS_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTINTSTATUS_REG_OFFSET)
`define WDT_WDTINTCLR_REG_ADDR					(`WDT_REG_BASE_ADDR + `WDT_WDTINTCLR_REG_OFFSET)


#endif //__WDT_REG_DEF_SVH__
